### ISSUE TITLE
[Flaky] spec/system/admin/adjustments_spec.rb

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#10346]
### What we should change and why (this is tech debt)

```
Failures:

  1) 
    As an administrator
    I want to manage adjustments on orders
 on a canceled order displays adjustments
     Failure/Error: click_link 'Adjustments'
     
     Capybara::ElementNotFound:
       Unable to find link "Adjustments"
     
     
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_manage_adjustments_on_orders_on_a_canceled_order_displays_adjustments_485.png

     
     
     
     # ./spec/system/admin/adjustments_spec.rb:104:in `block (3 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:44:in `block (2 levels) in <top (required)>'
```
### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/4050833680/jobs/6968590356

**Comment by drummer83** [comment]
Probably another related occurrence here:
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5243855322/jobs/9469076769
