### ISSUE TITLE
[Flaky] spec/system/admin/orders_spec.rb

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#10408]
### What we should change and why (this is tech debt)

```
Failures:

  1) 
    As an administrator
    I want to manage orders
 with a complete order logging as superadmin and visiting the orders page ordering orders with different billing addresses orders by last name
     Failure/Error: find("a", text: 'NAME').click # sets ascending ordering
     
     Capybara::ElementNotFound:
       Unable to find visible css "a" with text "NAME"
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_manage_orders_with_a_complete_order_logging_as_superadmin_and_visiting_the_orders_page_ordering_orders_with_different_billing_addresses_orders_by_la_64.png

     
     # ./spec/system/admin/orders_spec.rb:330:in `block (6 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:44:in `block (2 levels) in <top (required)>'
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/4139474229/jobs/7157078713

**Comment by anshu1992** [comment]
@mkllnk I can fix it.

**Comment by jibees** [comment]
Hi @anshu1992 👋 
Fixing flaky spec is a good way to maintain a good quality code for our application: thanks a lot then!
I'll assign to you then ;)

**Comment by anshu1992** [comment]
Hi @jibees, here is the [PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/10446) to fix this test. Please let me know if any changes are required. Thank you!

**Comment by anshu1992** [comment]
Hey @jibees, made the change as requested.

**Comment by filipefurtad0** [comment]
Another occurrence [here](https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/4676217224/jobs/8282250906).
