### ISSUE TITLE
 [Flaky] ./spec/system/admin/bulk_order_management_spec.rb:1209

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#10785]
### What we should change and why (this is tech debt)

```
Failures:

  1) 
  As an Administrator
  I want to be able to manage orders in bulk
 listing orders searching by order number
     Failure/Error: expect(page).to have_text "Loading orders"
       expected to find text "Loading orders" in "Logged in as : lonna@collier.co.uk Account Logout Store DASHBOARD PRODUCTS ORDER CYCLES ORDERS REPORTS CONFIGURATION ENTERPRISES CUSTOMERS GROUPS USERS ORDERS BULK ORDER MANAGEMENT SUBSCRIPTIONS Bulk Order Management What's this? SEARCH PRODUCER All SHOP All ORDER CYCLE All DATE RANGE FILTER RESULTS CLEAR FILTERS ACTIONS Columns 15 per page 1 Results found. Viewing 1 to 1. NAME COMPLETED AT PRODUCER PRODUCT: UNIT QUANTITY MAX Wonka, Willy May 02, 2023 Enterprise 83 Product #46 - 8957: 1g, S 1 « FIRST PREVIOUS 1 NEXT LAST »"
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_be_able_to_manage_orders_in_bulk_listing_orders_searching_by_order_number_735.png

     
     # ./spec/system/admin/bulk_order_management_spec.rb:1209:in `expect_line_items_results'
     # ./spec/system/admin/bulk_order_management_spec.rb:211:in `block (4 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'

  2) 
  As an Administrator
  I want to be able to manage orders in bulk
 listing orders searching by phone number
     Failure/Error: expect(page).to have_text "Loading orders"
       expected to find text "Loading orders" in "Logged in as : keturah_jast@metz.com Account Logout Store DASHBOARD PRODUCTS ORDER CYCLES ORDERS REPORTS CONFIGURATION ENTERPRISES CUSTOMERS GROUPS USERS ORDERS BULK ORDER MANAGEMENT SUBSCRIPTIONS Bulk Order Management What's this? SEARCH PRODUCER All SHOP All ORDER CYCLE All DATE RANGE FILTER RESULTS CLEAR FILTERS ACTIONS Columns 15 per page 1 Results found. Viewing 1 to 1. NAME COMPLETED AT PRODUCER PRODUCT: UNIT QUANTITY MAX Wonka, Willy May 02, 2023 Enterprise 89 Product #52 - 9697: 1g, S 1 « FIRST PREVIOUS 1 NEXT LAST »"
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_be_able_to_manage_orders_in_bulk_listing_orders_searching_by_phone_number_222.png

     
     # ./spec/system/admin/bulk_order_management_spec.rb:1209:in `expect_line_items_results'
     # ./spec/system/admin/bulk_order_management_spec.rb:218:in `block (4 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/4806239373/jobs/8662835217

**Comment by filipefurtad0** [comment]
Thanks @drummer83.

We can close this one, as it will only occur in branches which are not up-to-date with master; it was fixed [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/10766).
