### ISSUE TITLE
Can't create a negative adjustment

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#10837]
## Description
<img width="660" alt="Capture d’écran 2023-05-12 à 15 58 48" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/701c393f-2f48-48f0-a84e-9ef813e89c55">

Associated bugsnag: https://app.bugsnag.com/open-food-france/coopcircuits/errors/645e376e3c8c3e0009582bba

```
app/models/calculator/default_tax.rb:97:in `deduced_total_by_rate': undefined method `/' for nil:NilClass (NoMethodError)
    from app/models/calculator/default_tax.rb:86:in `compute_item'
    from app/models/calculator/default_tax.rb:16:in `compute'
    from app/models/spree/tax_rate.rb:107:in `compute_amount'
    from app/models/spree/tax_rate.rb:89:in `adjust'
    from app/models/spree/tax_rate.rb:52:in `block (2 levels) in adjust'
    from app/models/spree/tax_rate.rb:51:in `each'
    from app/models/spree/tax_rate.rb:51:in `block in adjust'
    from app/models/spree/tax_rate.rb:48:in `each'
    from app/models/spree/tax_rate.rb:48:in `adjust'
    from app/controllers/spree/admin/adjustments_controller.rb:45:in `apply_tax'
```

## Expected Behavior
One can apply a negative adjustment.

## Actual Behaviour
A negative adjustment leads to a 500 error

## Steps to Reproduce

1. As an admin, on a order create a adjustment (with a tax category rate included in price and default tax i suppose dev. note)
2. See that form submitting leads to a 500 error

## Workaround
Deactivate number localization validation:
<img width="404" alt="Capture d’écran 2023-05-12 à 17 51 26" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/1c1e21bd-bfc9-4320-b8f4-9eb277251314">

## Severity
bug-s2: a non-critical feature is broken, no workaround

**Comment by jibees** [comment]
Found the _cause_: at this point, `@adjustment.amount` is nil (and should not be):

https://github.com/openfoodfoundation/openfoodnetwork/blob/3c7337b53a12660f8788c3b7ceef0014def46716/app/controllers/spree/admin/adjustments_controller.rb#L44-L46

**Comment by jibees** [comment]
It's due to localized number validation when `enable_localized_number` is active
<img width="404" alt="Capture d’écran 2023-05-12 à 17 51 26" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/499453af-3851-4c23-b456-d31f0fb084b8">
