### ISSUE TITLE
[Flaky] spec/system/consumer/split_checkout_tax_not_incl_spec.rb

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#10989]
### What we should change and why (this is tech debt)

```
Failures:

  1) As a consumer, I want to see adjustment breakdown a not-included tax for a customer with shipping address within the tax zone on legacy checkout will be charged tax on the order
     Failure/Error: expect(order_within_zone.additional_tax_total).to eq(1.3)
     
       expected: 1.3
            got: 0.0
     
       (compared using ==)
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_a_consumer_i_want_to_see_adjustment_breakdown_a_not_included_tax_for_a_customer_with_shipping_address_within_the_tax_zone_on_legacy_checkout_will_be_charged_tax_on_the_order_216.png

     
     # ./spec/system/consumer/split_checkout_tax_not_incl_spec.rb:111:in `block (5 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'

Finished in 2 minutes 29.9 seconds
26 examples, 1 failure

Failed examples:

rspec ./spec/system/consumer/split_checkout_tax_not_incl_spec.rb:97 # As a consumer, I want to see adjustment breakdown a not-included tax for a customer with shipping address within the tax zone on legacy checkout will be charged tax on the order
I, [2023-06-12T14:37:35.916600 #2976]  INFO -- : [knapsack_pro] To retry all the tests assigned to this CI node, please run the following command on your machine:
I, [2023-06-12T14:37:35.916682 #2976]  INFO -- : [knapsack_pro] bundle exec rspec --format progress --default-path spec "spec/system/consumer/split_checkout_tax_not_incl_spec.rb" "spec/system/consumer/shopping/orders_spec.rb" "spec/system/consumer/shopping/checkout_paypal_spec.rb" "spec/system/consumer/groups_spec.rb" "spec/system/consumer/account/payments_spec.rb"
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
Coverage report generated for RSpec to /home/runner/work/openfoodnetwork/openfoodnetwork/coverage. 7516 / 24211 LOC (31.04%) covered.
Error: Process completed with exit code 1.
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5244916759/jobs/9471599216

**Comment by mkllnk** [comment]
Here's another failure I'm getting consistently at the moment:
```
Failures:

  1) As a consumer, I want to see adjustment breakdown a not-included tax for a customer with shipping address within the tax zone when using a voucher moving between summary to summary via edit cart recalculate the tax component properly
     Failure/Error: expect(page).to have_button("Complete order")
       expected to find button "Complete order" that is not disabled but there were no matches
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_a_consumer_i_want_to_see_adjustment_breakdown_a_not_included_tax_for_a_customer_with_shipping_address_within_the_tax_zone_when_using_a_voucher_moving_between_summary_to_summar_3.png

     
     # ./spec/support/split_checkout_helper.rb:55:in `proceed_to_summary'
     # ./spec/system/consumer/split_checkout_tax_not_incl_spec.rb:170:in `block (6 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'


Finished in 2 minutes 13 seconds
20 examples, 1 failure, 2 pending

Failed examples:

rspec ./spec/system/consumer/split_checkout_tax_not_incl_spec.rb:162 # As a consumer, I want to see adjustment breakdown a not-included tax for a customer with shipping address within the tax zone when using a voucher moving between summary to summary via edit cart recalculate the tax component properly
```
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5970351373/job/16198222363?pr=11450
