### ISSUE TITLE
[Flaky] spec/system/admin/orders_spec.rb

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#11015]
### What we should change and why (this is tech debt)

```
Failures:

  1) 
    As an administrator
    I want to manage orders
 with a complete order bulk actions as a super admin can bulk send email to 2 orders
     Failure/Error:
       expect {
         find_button("Confirm").click
       }.to enqueue_job(ActionMailer::MailDeliveryJob).exactly(:twice)
     
       expected to enqueue exactly 2 jobs, but enqueued 0
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_manage_orders_with_a_complete_order_bulk_actions_as_a_super_admin_can_bulk_send_email_to_2_orders_225.png

     
     # ./spec/system/admin/orders_spec.rb:521:in `block (6 levels) in <main>'
     # ./spec/system/admin/orders_spec.rb:520:in `block (5 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'

  2) 
    As an administrator
    I want to manage orders
 with a complete order bulk actions as a super admin can bulk print invoices from 2 orders
     Failure/Error: expect(page).to have_content "Compiling Invoices"
       expected to find text "Compiling Invoices" in "Logged in as : danuta_berge@hirthesteuber.us Account Logout Store DASHBOARD PRODUCTS ORDER CYCLES ORDERS REPORTS CONFIGURATION ENTERPRISES CUSTOMERS GROUPS USERS ORDERS BULK ORDER MANAGEMENT SUBSCRIPTIONS Listing Orders NEW ORDER SEARCH DATE RANGE STATUS cart address delivery payment confirmation complete cancelled awaiting return returned resumed INVOICE NUMBER: EMAIL FIRST NAME BEGINS WITH LAST NAME BEGINS WITH ONLY SHOW COMPLETE ORDERS SHIPPING METHOD UPS Ground UPS Ground Pick-up at the farm UPS Ground Signed, sealed, delivered UPS Ground UPS Ground UPS Ground UPS Ground DISTRIBUTORS Enterprise 123 Enterprise 124 Enterprise 125 Enterprise 122 Enterprise 126 ORDER CYCLES Four Three Two Five FILTER RESULTS CLEAR FILTERS 2 orders selected ACTIONS Resend Confirmation Send Invoices Print Invoices Cancel Orders 50 per page 100 per page 15 per page 15 per page 4 Results found. Viewing 1 to 4. DISTRIBUTOR COMPLETED AT ▼ NUMBER STATE PAYMENT STATE SHIPMENT STATE EMAIL NAME TOTAL Enterprise 126 June 14, 2023 R068767214 COMPLETE PAID ($0.00) READY gisele.nolan@dooley.info Jospeh Raynor $50.00 Enterprise 125 June 14, 2023 R502322201 COMPLETE CREDIT OWED ($-10,000.00) READY george@reichertkohler.us Carlena Kertzmann $50.00 Enterprise 124 June 14, 2023 R132082112 COMPLETE CREDIT OWED ($-10,000.00) READY pamula@greenfelderwyman.name Josie Nicolas $50.00 Enterprise 123 June 12, 2023 R210465727 COMPLETE PAID ($0.00) READY hildred@johns.com Wm Kertzmann $50.00 ‹ PREV 1 NEXT ›"
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_manage_orders_with_a_complete_order_bulk_actions_as_a_super_admin_can_bulk_print_invoices_from_2_orders_900.png

     
     # ./spec/system/admin/orders_spec.rb:538:in `block (5 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'

  3) 
    As an administrator
    I want to manage orders
 with a complete order bulk actions as a super admin can bulk cancel 2 orders
     Failure/Error: expect(page).to have_content("CANCELLED", count: 2)
       expected to find text "CANCELLED" 2 times but found 0 times in "Logged in as : nikki.bogan@klein.co.uk Account Logout Store DASHBOARD PRODUCTS ORDER CYCLES ORDERS REPORTS CONFIGURATION ENTERPRISES CUSTOMERS GROUPS USERS ORDERS BULK ORDER MANAGEMENT SUBSCRIPTIONS Listing Orders NEW ORDER SEARCH DATE RANGE STATUS cart address delivery payment confirmation complete cancelled awaiting return returned resumed INVOICE NUMBER: EMAIL FIRST NAME BEGINS WITH LAST NAME BEGINS WITH ONLY SHOW COMPLETE ORDERS SHIPPING METHOD UPS Ground UPS Ground Pick-up at the farm UPS Ground Signed, sealed, delivered UPS Ground UPS Ground UPS Ground UPS Ground DISTRIBUTORS Enterprise 129 Enterprise 130 Enterprise 131 Enterprise 128 Enterprise 132 ORDER CYCLES Four Three Two Five FILTER RESULTS CLEAR FILTERS 2 orders selected ACTIONS 50 per page 100 per page 15 per page 15 per page 4 Results found. Viewing 1 to 4. DISTRIBUTOR COMPLETED AT ▼ NUMBER STATE PAYMENT STATE SHIPMENT STATE EMAIL NAME TOTAL Enterprise 132 June 14, 2023 R882634287 COMPLETE PAID ($0.00) READY aliza@bogisich.co.uk Rosalba Littel $50.00 Enterprise 131 June 14, 2023 R884688067 COMPLETE CREDIT OWED ($-10,000.00) READY aldo_wintheiser@kihncummings.info Lorriane Pfeffer $50.00 Enterprise 130 June 14, 2023 R638808542 COMPLETE CREDIT OWED ($-10,000.00) READY becky@kubjenkins.info Otis Hyatt $50.00 Enterprise 129 June 12, 2023 R812408247 COMPLETE PAID ($0.00) READY merlene_mosciski@greenfeldermarks.name Audie Cartwright $50.00 ‹ PREV 1 NEXT › This will cancel the current order. Are you sure you want to proceed? SEND A CANCELLATION EMAIL TO THE CUSTOMER RESTOCK ITEMS: RETURN ALL ITEMS TO STOCK". (However, it was found 1 time using a case insensitive search.)
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_manage_orders_with_a_complete_order_bulk_actions_as_a_super_admin_can_bulk_cancel_2_orders_1.png

     
     # ./spec/system/admin/orders_spec.rb:573:in `block (5 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'

  4) 
    As an administrator
    I want to manage orders
 with a complete order bulk actions as a super admin bulk print invoices with multiple orders with differents states can bulk print invoices but only for the 'complete' or 'resumed' ones
     Failure/Error:
       expect {
         find_button("Confirm").click
       }.to enqueue_job(ActionMailer::MailDeliveryJob).exactly(:twice)
     
       expected to enqueue exactly 2 jobs, but enqueued 0
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_manage_orders_with_a_complete_order_bulk_actions_as_a_super_admin_bulk_print_invoices_with_multiple_orders_with_differents_states_can_bulk_print_inv_500.png

     
     # ./spec/system/admin/orders_spec.rb:499:in `block (8 levels) in <main>'
     # ./spec/system/admin/orders_spec.rb:498:in `block (7 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'

  5) 
    As an administrator
    I want to manage orders
 with a complete order with a capturable order capture payment
     Failure/Error: expect(page).to have_css "i.success"
       expected to find css "i.success" but there were no matches
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_manage_orders_with_a_complete_order_with_a_capturable_order_capture_payment_584.png

     
     # ./spec/system/admin/orders_spec.rb:651:in `block (4 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'

  6) 
    As an administrator
    I want to manage orders
 with a complete order with a capturable order ship order from the orders index page
     Failure/Error: expect(page).to have_css "i.success"
       expected to find css "i.success" but there were no matches
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_manage_orders_with_a_complete_order_with_a_capturable_order_ship_order_from_the_orders_index_page_671.png

     
     # ./spec/system/admin/orders_spec.rb:668:in `block (4 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'

Finished in 4 minutes 53.3 seconds
34 examples, 6 failures, 1 pending

Failed examples:

rspec ./spec/system/admin/orders_spec.rb:509 # 
    As an administrator
    I want to manage orders
 with a complete order bulk actions as a super admin can bulk send email to 2 orders
rspec ./spec/system/admin/orders_spec.rb:529 # 
    As an administrator
    I want to manage orders
 with a complete order bulk actions as a super admin can bulk print invoices from 2 orders
rspec ./spec/system/admin/orders_spec.rb:544 # 
    As an administrator
    I want to manage orders
 with a complete order bulk actions as a super admin can bulk cancel 2 orders
rspec ./spec/system/admin/orders_spec.rb:481 # 
    As an administrator
    I want to manage orders
 with a complete order bulk actions as a super admin bulk print invoices with multiple orders with differents states can bulk print invoices but only for the 'complete' or 'resumed' ones
rspec ./spec/system/admin/orders_spec.rb:643 # 
    As an administrator
    I want to manage orders
 with a complete order with a capturable order capture payment
rspec ./spec/system/admin/orders_spec.rb:661 # 
    As an administrator
    I want to manage orders
 with a complete order with a capturable order ship order from the orders index page
```

### Context

First occurrence after merging:

* #10455

Logs:
* https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5271642816/jobs/9532823318
* https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5271782395/jobs/9533143532
* https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5273039791/jobs/9536005987

**Comment by mkllnk** [comment]
I can't reproduce this locally. :disappointed:

**Comment by rioug** [comment]
`rspec ./spec/system/admin/orders_spec.rb:544` was broken, I fixed it here: #11080

I couldn't reproduce the other flacky specs, I tried up to 120 runs ...

**Comment by RachL** [comment]
@mkllnk @rioug should we close this one if we can't reproduce it?

**Comment by mkllnk** [comment]
> should we close this one if we can't reproduce it?

The problem is that it fails on CI. Let's have a quick review of the last ten fails:

- spec/services/order_invoice_comparator_spec.rb
- Docker pull failed
- spec/system/admin/order_spec.rb
- spec/system/admin/reports_spec.rb
- spec/system/admin/bulk_product_update_spec.rb Ferrum::TimeoutError
- Node failed
- spec/system/admin/subscriptions_spec.rb
- Node failed
- spec/system/admin/reports/enterprise_summary_fees/enterprise_summary_fee_with_tax_report_by_producer_spec.rb Ferrum::PendingConnectionsError
- spec/system/admin/payment_method_spec.rb Ferrum::TimeoutError

It's not in there. That's covering a few weeks. So maybe let's close it for now.
