### ISSUE TITLE
StandardError in db:migrate: The bucket does not allow ACLs

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#11073]
## Description

Deployment of v4.3.13 failed.

## Expected Behavior

Migration succeds.

## Actual Behaviour

```
TASK [deploy : migrate database] **********************************************************************************************************************************************************************************
fatal: [csicsoka.org]: FAILED! => {"changed": true, "cmd": ["bash", "-lc", "bundle exec rake db:migrate RAILS_ENV=production"], "delta": "0:00:05.576315", "end": "2023-06-19 00:11:54.599461", "msg": "non-zero return code", "rc": 1, "start": "2023-06-19 00:11:49.023146", "stderr": "rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

The bucket does not allow ACLs
/home/openfoodnetwork/.gem/ruby/3.0.0/gems/aws-sdk-core-3.174.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'
...
/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2023-06-19-000742/db/migrate/20230504001141_public_images.rb:38:in `block in set_objects_to_readable'
...
/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2023-06-19-000742/db/migrate/20230504001141_public_images.rb:38:in `set_objects_to_readable'
/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2023-06-19-000742/db/migrate/20230504001141_public_images.rb:8:in `up'
...

Caused by:
Aws::S3::Errors::AccessControlListNotSupported: The bucket does not allow ACLs
/home/openfoodnetwork/.gem/ruby/3.0.0/gems/aws-sdk-core-3.174.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'
...
/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2023-06-19-000742/db/migrate/20230504001141_public_images.rb:38:in `block in set_objects_to_readable'
...
Tasks: TOP => db:migrate
(See full trace by running task with --trace)",

-- change_column_null(:adjustment_metadata, :adjustment_id, false)
   -> 0.0017s
-- change_column_null(:adjustment_metadata, :enterprise_id, false)
   -> 0.0004s
== 20230503060530 RequireAdjustmentAndEnterpriseOnAdjustmentMetadata: migrated (0.0025s) 

== 20230504001141 PublicImages: migrating =====================================", "stdout_lines": ["== 20230503060530 RequireAdjustmentAndEnterpriseOnAdjustmentMetadata: migrating ", "-- change_column_null(:adjustment_metadata, :adjustment_id, false)", "   -> 0.0017s", "-- change_column_null(:adjustment_metadata, :enterprise_id, false)", "   -> 0.0004s", "== 20230503060530 RequireAdjustmentAndEnterpriseOnAdjustmentMetadata: migrated (0.0025s) ", "", "== 20230504001141 PublicImages: migrating ====================================="]}
Monday 19 June 2023  10:11:54 +1000 (0:00:01.025)       0:04:40.059 *********** 
```

## Steps to Reproduce

1. Deploy v4.3.13 to csicsoka.org

## Severity

Blocking deployments.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Configure AWS S3.
https://stackoverflow.com/questions/71080354/getting-the-bucket-does-not-allow-acls-error

**Comment by sigmundpetersen** [comment]
Can this be closed?

**Comment by mkllnk** [comment]
> Can this be closed?

Ah, yes, thanks.
