### ISSUE TITLE
[Flaky] ./spec/system/admin/enterprise_fees_spec.rb

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11330]
### What we should change and why (this is tech debt)

```

   1) 
    As an administrator
    I want to manage enterprise fees
 editing an enterprise fee editing two enterprise fees handles updating two enterprise fees
     Failure/Error: expect(page).to have_selector "input[value='World!']"
       expected to find css "input[value='World!']" but there were no matches
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_manage_enterprise_fees_editing_an_enterprise_fee_editing_two_enterprise_fees_handles_updating_two_enterprise_fees_355.png

     
     # ./spec/system/admin/enterprise_fees_spec.rb:191:in `block (4 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'


Finished in 4 minutes 44.2 seconds
49 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/system/admin/enterprise_fees_spec.rb:181 # 
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5752485014/job/15593590173

**Comment by abdellani** [comment]
another occurrence
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5750882112/job/15588542877

**Comment by filipefurtad0** [comment]
Another one
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5760948180/job/15617907655

**Comment by sigmundpetersen** [comment]
Also reported in #11461 . Closing here
