### ISSUE TITLE
[Flaky] /spec/system/admin/orders_spec.rb

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11462]
### What we should change and why (this is tech debt)

```
Failures:

  1) 
    As an administrator
    I want to manage orders
 with a complete order filters filter by customer first and last names
     Failure/Error: expect(page).to_not have_content order2.number
       expected not to find text "R524340736" in "Logged in as : kristina_rutherford@treutel.com Account Logout Store DASHBOARD PRODUCTS ORDER CYCLES ORDERS REPORTS CONFIGURATION ENTERPRISES CUSTOMERS GROUPS USERS ORDERS BULK ORDER MANAGEMENT SUBSCRIPTIONS Listing Orders NEW ORDER SEARCH DATE RANGE STATUS cart address delivery payment confirmation complete cancelled awaiting return returned resumed ORDER NUMBER: EMAIL FIRST NAME BEGINS WITH LAST NAME BEGINS WITH ONLY SHOW COMPLETE ORDERS SHIPPING METHOD UPS Ground Signed, sealed, delivered UPS Ground UPS Ground UPS Ground UPS Ground UPS Ground UPS Ground Pick-up at the farm DISTRIBUTORS Enterprise 32 Enterprise 33 Enterprise 34 Enterprise 31 Enterprise 35 ORDER CYCLES Four Three Two Five FILTER RESULTS CLEAR FILTERS No order selected ACTIONS 50 per page 100 per page 15 per page 15 per page 2 Results found. Viewing 1 to 2. DISTRIBUTOR COMPLETED AT ▼ NUMBER STATE PAYMENT STATE SHIPMENT STATE EMAIL NAME TOTAL Enterprise 34 August 23, 2023 R755401772 COMPLETE CREDIT OWED ($-10,000.00) READY delorse_bosco@gorczany.name Kihn, Maggie $50.00 Enterprise 32 August 21, 2023 R524340736 COMPLETE PAID ($0.00) READY yvone.stehr@gloverokon.co.uk Kihn, Shaunda $50.00 ‹ PREV 1 NEXT ›"
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_manage_orders_with_a_complete_order_filters_filter_by_customer_first_and_last_names_52.png

     
     # ./spec/system/admin/orders_spec.rb:173:in `block (4 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'


Finished in 4 minutes 51.5 seconds
60 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/system/admin/orders_spec.rb:157 # 
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5947037243/job/16128512534?pr=11427

**Comment by filipefurtad0** [comment]
`rspec ./spec/system/admin/order_spec.rb:334 # `

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5998114028/job/16265781760?pr=11457

**Comment by drummer83** [comment]
Another occurrence here:
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/6366503670/job/17284252910

**Comment by filipefurtad0** [comment]
rspec ./spec/system/admin/order_spec.rb:518

Another occurrence here:
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/6947846664/job/18902554415?pr=11645

**Comment by filipefurtad0** [comment]
Another occurrence:
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/10570335139/job/29284642729?pr=12790
