### ISSUE TITLE
[Flaky] ./spec/system/admin/enterprise_fees_spec.rb

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11461]
### What we should change and why (this is tech debt)

```
Failures:

  1) 
    As an administrator
    I want to manage enterprise fees
 editing an enterprise fee editing two enterprise fees handles updating two enterprise fees
     Failure/Error: expect(page).to have_selector "input[value='World!']"
       expected to find css "input[value='World!']" but there were no matches
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_manage_enterprise_fees_editing_an_enterprise_fee_editing_two_enterprise_fees_handles_updating_two_enterprise_fees_696.png

     
     # ./spec/system/admin/enterprise_fees_spec.rb:191:in `block (4 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'


Finished in 4 minutes 42.8 seconds
70 examples, 1 failure

Failed examples:

rspec ./spec/system/admin/enterprise_fees_spec.rb:181 # 
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5947037243/job/16128512211?pr=11427

**Comment by mkllnk** [comment]
I'm seeing this quite often now.

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/6021162928/job/16333581339?pr=11471

**Comment by mkllnk** [comment]
This is an interesting one. I can make it fail reliably with rspec-slow-repeat or by adding `sleep`. I think that the spec generally fails and only passes when executed so fast that the update requests are not handled yet.
