### ISSUE TITLE
[Flaky] rspec ./spec/lib/reports/orders_and_fulfillment/orders_cycle_supplier_totals_report_spec.rb

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11473]
### What we should change and why (this is tech debt)

```
Failures:

  1) Reporting::Reports::OrdersAndFulfillment::OrderCycleSupplierTotals total_units column is summarised
     Failure/Error: expect(report_table[0][4]).to eq 0.6 # kg (= 3 * 0.2kg)
     
       expected: 0.6
            got: 0.1e-2
     
       (compared using ==)
     # ./spec/lib/reports/orders_and_fulfillment/orders_cycle_supplier_totals_report_spec.rb:80:in `block (3 levels) in <top (required)>'

Finished in 2 minutes 54.5 seconds (files took 9.35 seconds to load)
459 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/lib/reports/orders_and_fulfillment/orders_cycle_supplier_totals_report_spec.rb:68 # Reporting::Reports::OrdersAndFulfillment::OrderCycleSupplierTotals total_units column is summarised
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/6024808376/job/16344253418?pr=11309

**Comment by filipefurtad0** [comment]
This seems order dependent, running:
`
bundle exec rspec "spec/lib/reports/enterprise_fee_summary/enterprise_fee_summary_report_spec.rb" "spec/lib/reports/customers_report_spec.rb" "engines/order_management/spec/services/order_management/subscriptions/proxy_order_syncer_spec.rb" "spec/lib/open_food_network/enterprise_fee_calculator_spec.rb" "spec/lib/open_food_network/scope_variant_to_hub_spec.rb" "spec/lib/reports/orders_and_fulfillment/orders_cycle_supplier_totals_report_spec.rb"`

leads to:

```
Failures:

  1) Reporting::Reports::OrdersAndFulfillment::OrderCycleSupplierTotals total_units column is blank when line items miss a unit
     Failure/Error: variant.update_columns(unit_value: nil, unit_description: "vacuum")
     
     ActiveRecord::NotNullViolation:
       PG::NotNullViolation: ERROR:  null value in column "unit_value" violates not-null constraint
       DETAIL:  Failing row contains (1590, 87777b515e7f70e1b6a9408b46fde9c5, 0.00, 113.40, 53.47, 167.45, null, 1139, AUD, null, vacuum, null, null, null, items, 1container, 2023-08-30 16:54:18.815115, 2023-08-30 16:54:18.815115, null, 1047).
     # ./spec/lib/reports/orders_and_fulfillment/orders_cycle_supplier_totals_report_spec.rb:61:in `block (3 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # PG::NotNullViolation:
     #   ERROR:  null value in column "unit_value" violates not-null constraint
     #   DETAIL:  Failing row contains (1590, 87777b515e7f70e1b6a9408b46fde9c5, 0.00, 113.40, 53.47, 167.45, null, 1139, AUD, null, vacuum, null, null, null, items, 1container, 2023-08-30 16:54:18.815115, 2023-08-30 16:54:18.815115, null, 1047).
     #   ./spec/lib/reports/orders_and_fulfillment/orders_cycle_supplier_totals_report_spec.rb:61:in `block (3 levels) in <main>'

  2) Reporting::Reports::OrdersAndFulfillment::OrderCycleSupplierTotals total_units column is summarised
     Failure/Error: expect(report_table[0][4]).to eq 0.6 # kg (= 3 * 0.2kg)
     
       expected: 0.6
            got: 0.1e-2
     
       (compared using ==)
     # ./spec/lib/reports/orders_and_fulfillment/orders_cycle_supplier_totals_report_spec.rb:80:in `block (3 levels) in <main>'

  3) Reporting::Reports::OrdersAndFulfillment::OrderCycleSupplierTotals total_units column is blank in summary when one line item misses a unit and another not
     Failure/Error: variant.update_columns(unit_value: nil, unit_description: "vacuum")
     
     ActiveRecord::NotNullViolation:
       PG::NotNullViolation: ERROR:  null value in column "unit_value" violates not-null constraint
       DETAIL:  Failing row contains (1596, 33d735893c6800915a31ceaa1a76b2d7, 0.00, 41.36, 185.47, 0.72, null, 1142, AUD, null, vacuum, null, null, null, items, 1container, 2023-08-30 16:54:20.960746, 2023-08-30 16:54:20.960746, null, 1049).
     # ./spec/lib/reports/orders_and_fulfillment/orders_cycle_supplier_totals_report_spec.rb:92:in `block (3 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # PG::NotNullViolation:
     #   ERROR:  null value in column "unit_value" violates not-null constraint
     #   DETAIL:  Failing row contains (1596, 33d735893c6800915a31ceaa1a76b2d7, 0.00, 41.36, 185.47, 0.72, null, 1142, AUD, null, vacuum, null, null, null, items, 1container, 2023-08-30 16:54:20.960746, 2023-08-30 16:54:20.960746, null, 1049).
     #   ./spec/lib/reports/orders_and_fulfillment/orders_cycle_supplier_totals_report_spec.rb:92:in `block (3 levels) in <main>'

Finished in 1 minute 52.76 seconds (files took 7.08 seconds to load)
138 examples, 3 failures

Failed examples:

rspec ./spec/lib/reports/orders_and_fulfillment/orders_cycle_supplier_totals_report_spec.rb:56 # Reporting::Reports::OrdersAndFulfillment::OrderCycleSupplierTotals total_units column is blank when line items miss a unit
rspec ./spec/lib/reports/orders_and_fulfillment/orders_cycle_supplier_totals_report_spec.rb:68 # Reporting::Reports::OrdersAndFulfillment::OrderCycleSupplierTotals total_units column is summarised
rspec ./spec/lib/reports/orders_and_fulfillment/orders_cycle_supplier_totals_report_spec.rb:85 # Reporting::Reports::OrdersAndFulfillment::OrderCycleSupplierTotals total_units column is blank in summary when one line item misses a unit and another not
```

**Comment by filipefurtad0** [comment]
I have not fully figured it out, but - the report table looks like this, when the spec is green:

```
=> [["Enterprise 2",
  "Product #1 - 1109",
  "200g",
  3,
  0.6e0,
  0.1e2,
  0.3e2,
  "e9768f307f1622ec33803e1a76bec35e",
  "No",
  "none"],
 ["Enterprise 2",
  "Product #2 - 2769",
  "1g",
  1,
  0.1e-2,
  0.1e2,
  0.1e2,
  "93053f1a54400f8f0508ab729b3545d3",
  "No",
  "none"],
 ["", "", "TOTAL", 4, 0.601e0, "", 0.4e2, "", "", ""]]
```

and like this, when the spec fails:
```

=> [["Enterprise 293",
  "Product #100 - 3775",
  "1g",
  1,
  0.1e-2,
  0.1e2,
  0.1e2,
  "b419c8317868d93d9fd244f20de20cbd",
  "No",
  "none"],
 ["Enterprise 293",
  "Product #99 - 3629",
  "200g",
  3,
  0.6e0,
  0.1e2,
  0.3e2,
  "4c0fb6a709f4fad70bf2cc2c795f0972",
  "No",
  "none"],
 ["", "", "TOTAL", 4, 0.601e0, "", 0.4e2, "", "", ""]]
```

**Comment by dacook** [comment]
Hi @filipefurtad0 , I didn't look too closely, but I suspect the problem here is that the products are ordered alphabetically. With alphabetic ordering, "Product #100 - 3775" gets ordered before "Product #99 - 3629". 
I'm guessing these are the names automatically genreated by the test factory. They can be given names like "Product A" and "Product B" to behave more predictably.

(and if I'm wrong, sorry for wasting your time 😉  )

**Comment by filipefurtad0** [comment]
Thanks @dacook I'll try that out :+1:

**Comment by dacook** [comment]
It looks a bit tricky in this one, because it's created automatically with `completed_order_with_totals`. Perhaps you can do something like `order.line_items.first.variant.update! name: "Product A"`

**Comment by filipefurtad0** [comment]
Thanks @dacook ,
For your pragmatic view and approach. I seemed to have spent too much time understanding why the table order changes as a function of spec order, etc... Renaming the product seems to work. I've pinged you on the PR for review.
