### ISSUE TITLE
[Flaky] ./spec/system/admin/order_spec.rb

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11553]
### What we should change and why (this is tech debt)

```
  1) 
    As an administrator
    I want to create and edit orders
 can't add more items than are available
     Failure/Error: click_button("OK")
     
     Capybara::Cuprite::ObsoleteNode:
       The element you are trying to interact with is either not part of the DOM, or is not currently visible on the page (perhaps display: none is set). It is possible the element has been replaced by another element and you meant to interact with the new element. If so you need to do a new find in order to get a reference to the new element.
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_create_and_edit_orders_can_t_add_more_items_than_are_available_698.png

     
     # ./spec/system/admin/order_spec.rb:353:in `block (2 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Ferrum::NodeNotFoundError:
     #   No node with given id found
     #   ./spec/system/admin/order_spec.rb:353:in `block (2 levels) in <main>'


Finished in 4 minutes 20.2 seconds
65 examples, 1 failure

Failed examples:

rspec ./spec/system/admin/order_spec.rb:334 # 

```
### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/6196489364/attempts/1?pr=11539

**Comment by filipefurtad0** [comment]
Duplicate from https://github.com/openfoodfoundation/openfoodnetwork/issues/11462.

**Comment by filipefurtad0** [comment]
rspec ./spec/system/admin/order_spec.rb:518

Another occurrence here:
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/6947846664/job/18902554415?pr=11645
