### ISSUE TITLE
[Flaky] ./spec/system/admin/reports/orders_and_fulfillment_spec.rb

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11581]
### What we should change and why (this is tech debt)

```
Failures:

  1) Orders And Fulfillment reports Saving report rendering options Revisiting a report after logout Columns to show should store columns after logout
     Failure/Error: click_link "Report"
     
     Capybara::ElementNotFound:
       Unable to find link "Report"
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_orders_and_fulfillment_reports_saving_report_rendering_options_revisiting_a_report_after_logout_columns_to_show_should_store_columns_after_logout_974.png

     
     # ./spec/system/admin/reports/orders_and_fulfillment_spec.rb:611:in `block (6 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'


Finished in 3 minutes 54.4 seconds
57 examples, 1 failure, 3 pending

Failed examples:

rspec ./spec/system/admin/reports/orders_and_fulfillment_spec.rb:598 # Orders And Fulfillment reports Saving report rendering options Revisiting a report after logout Columns to show should store columns after logout
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/6276344174/job/17045813441?pr=11185

**Comment by mkllnk** [comment]
Another one here:

* https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/6897425118/job/18765559403

**Comment by drummer83** [comment]
Another one:
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/6942310386/attempts/1?pr=11732
