### ISSUE TITLE
[Flaky] spec/system/consumer/caching/shops_caching_spec.rb

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#11656]
### What we should change and why (this is tech debt)

```
Failures:

  1) Shops caching API action caching on taxons and properties keeps data cached for a short time on subsequent requests
     Failure/Error: expect(page).to have_content property.presentation # Property list is unchanged
       expected to find text "Cached Property" in "SHOPS MAP PRODUCERS GROUPS ABOUT Español Login Shopping @ Enterprise 20 Cart 0 Close Your cart is empty Enterprise 20 Herndon Shop About Producers Contact Next order closing in 7 days Ready for time 0 Product #34 - 7430 Nam sunt excepturi repellendus eos fuga laborum distinctio ratione. Blanditiis laborum quam quidem ex. Optio impedit sunt ut veniam accusantium sequi. Fugiat molestiae laborum facilis numquam eligendi explicabo illum qui. Aperiam reiciendis maiores ut aut. In atque consequatur porro blanditiis distinctio. Eius vel error eveniet unde nam assumenda quaerat tempore. Minus pariatur corporis a iste. Nemo iste totam minima animi beatae facilis. Debitis quas quos ipsam exercitationem. Aliquam nisi expedita ab dolore nostrum sequi illo velit. Unde tempora voluptate porro doloremque voluptates. Similique debitis asperiores vitae iure aperiam. Incidunt est qui distinctio explicabo voluptatem quisquam. Odit quas aut quos assumenda voluptatibus provident. Quis ipsum soluta veniam consequatur sunt. from Enterprise 20 New Property 1g $19.99 $19,990.00 / kg $0.00 Add Filter by Cached Taxon New Property Interested in getting on the Open Food Network? Register here Secure and trusted. Open Food Network uses SSL encryption (2048 bit RSA) everywhere to keep your shopping and payment information private. Our servers do not store your credit card details and payments are processed by PCI-compliant services. Keep in touch Email us Newsletter sign-up News Calendar Navigate Shops Map Producers Groups About Join us Create a listing, shop or group directory on the Open Food Network. Tell me more! Find us on GitHub Open Food Network is a free and open source software platform. Our content is licensed with CC BY-SA 3.0 and our code with AGPL 3. We take good care of your data. See our cookies policy". (However, it was found 6 times including non-visible text.)
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_shops_caching_api_action_caching_on_taxons_and_properties_keeps_data_cached_for_a_short_time_on_subsequent_requests_712.png

     
     # ./spec/system/consumer/caching/shops_caching_spec.rb:101:in `block (4 levels) in <top (required)>'
     # ./spec/system/consumer/caching/shops_caching_spec.rb:89:in `block (3 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'
     # ./spec/base_spec_helper.rb:98:in `block (2 levels) in <main>'


Finished in 1 minute 58.34 seconds
17 examples, 1 failure, 2 pending

Failed examples:

rspec ./spec/system/consumer/caching/shops_caching_spec.rb:87 # Shops caching API action caching on taxons and properties keeps data cached for a short time on subsequent requests
```

### Context

* https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/6488612073/job/17621379862?pr=11655

**Comment by filipefurtad0** [comment]
Another one here:
`rspec ./spec/system/consumer/caching/shops_caching_spec.rb:77 # Shops caching API action caching on taxons and properties caches rendered response for taxons and properties, with the provided options`
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/6961970851/job/18944706373?pr=11645

**Comment by drummer83** [comment]
Another one here: https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/7119437695/job/19384543352

**Comment by filipefurtad0** [comment]
Another one here: https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/7794355561/job/21255543978

**Comment by sigmundpetersen** [comment]
Should we merge this and #11010 ?

**Comment by filipefurtad0** [comment]
Yes, indeed they point to the same file. Closing here - thanks @sigmundpetersen :-)
