### ISSUE TITLE
[Invoices] Error on bulk invoice printing

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11791]
## Description

If the legal invoices feature is activated, bulk invoice printing does not generate the expected *.pdf file.

## Expected Behavior

Bulk invoice printing should work with the invoices feature enabled.

## Actual Behaviour

Bulk invoice printing is not working with the invoices feature enabled.

## Steps to Reproduce

1. Enable the legal invoices feature.
2. Visit the orders page (/admin/orders)
3. Select some complete orders and try to bulk print them

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/1a929e3f-05ec-42d5-b75e-63f64964cabc)

**Comment by abdellani** [comment]
```ruby
2023-11-13T09:34:28.219Z pid=4038162 tid=2dw3m class=BulkInvoiceJob jid=8acece8068f7da13fce99bb7 elapsed=0.321 INFO: fail
2023-11-13T09:34:28.219Z pid=4038162 tid=2dw3m WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"BulkInvoiceJob","args":[{"job_class":"BulkInvoiceJob","job_id":"f3e89b2f-bb36-402d-b692-5e96c44e065a","provider_job_id":null,"queue_name":"default","priority":null,"arguments":[["5"],"tmp/invoices/1699867980-50dc.pdf",{"channel":"SessionChannel:7cf283050cb499dc88fee0962dc8cc34","current_user_id":1,"_aj_ruby2_keywords":["channel","current_user_id"]}],"executions":0,"exception_executions":{},"locale":"en","timezone":"Melbourne","enqueued_at":"2023-11-13T09:33:00Z"}],"jid":"8acece8068f7da13fce99bb7","created_at":1699867980.4665105,"enqueued_at":1699868067.8939912,"error_message":"undefined method `host' for nil:NilClass\n\n        host: request.host,\n                     ^^^^^","error_class":"ActionView::Template::Error","failed_at":1699867980.73491,"retry_count":2,"retried_at":1699868033.2894433}}
2023-11-13T09:34:28.219Z pid=4038162 tid=2dw3m WARN: ActionView::Template::Error: undefined method `host' for nil:NilClass

        host: request.host,
                     ^^^^^
2023-11-13T09:34:28.221Z pid=4038162 tid=2dw3m WARN: app/helpers/terms_and_conditions_helper.rb:5:in `link_to_platform_terms'
app/views/spree/admin/orders/invoice4.html.haml:103
app/services/invoice_renderer.rb:11:in `render_to_string'
app/jobs/bulk_invoice_job.rb:41:in `generate_invoice'
app/jobs/bulk_invoice_job.rb:13:in `each'
app/jobs/bulk_invoice_job.rb:13:in `perform'
2023-11-13T09:34:28.221Z pid=4038162 tid=2dw3m INFO: DEPRECATION: Sidekiq exception handlers now take three arguments, see #<Proc:0x00007f488b88f3f8 /home/work/.rvm/gems/ruby-3.1.4@openfoodnetwork/gems/bugsnag-6.26.0/lib/bugsnag/integrations/sidekiq.rb:53>

```
It seems that the problem concerns rending the `terms of service` link from the Sidekiq job.
The `request` object isn't accessible from the background process.
