### ISSUE TITLE
[Flaky] spec/system/admin/order_cycles/complex_editing_multiple_product_pages_spec.rb

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#12727]
### What we should change and why (this is tech debt)

```
Failures:

  1) 
    As an administrator
    I want to manage complex order cycles
 editing an order cycle with multiple pages of products select all products
     Failure/Error: expect(page).not_to have_content new_product.name
       expected not to find text "Product #11 - 2247" in "The hubs Enterprise 30, Enterprise 31 are listed in an active order cycle, but do not have valid shipping and payment methods. Until you set these up, customers will not be able to shop at these hubs. Dismiss Logged in as : alexandria@grady.info Account Logout Store Dashboard Products Order cycles Orders Reports Configuration Enterprises Customers Groups Users Edit Order Cycle Advanced Settings 1. GENERAL SETTINGS 2. INCOMING PRODUCTS 3. OUTGOING PRODUCTS 4. CHECKOUT OPTIONS Incoming Supplier Products ( Expand all ) Receival Details Fees Enterprise 28 1 / 2 selected Enterprise 28 Enterprise 29 Enterprise 30 Enterprise 31 Enterprise 27 Enterprise fee 7 Remove 1 of 2 Variants Loaded Load All Variants Select All 2 Variants Product #11 - 2247 1g Load More Variants Load All Variants Enterprise 29 1 / 1 selected Enterprise 28 Enterprise 29 Enterprise 30 Enterprise 31 Enterprise 27 Enterprise fee 8 Remove"
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_manage_complex_order_cycles_editing_an_order_cycle_with_multiple_pages_of_products_select_all_products_222.png

     
     # ./spec/system/admin/order_cycles/complex_editing_multiple_product_pages_spec.rb:29:in `block (3 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:39:in `block (2 levels) in <top (required)>'
     # ./spec/base_spec_helper.rb:144:in `block (3 levels) in <main>'
     # ./spec/base_spec_helper.rb:144:in `block (2 levels) in <main>'

Finished in 3 minutes 56.5 seconds (files took 3.78 seconds to load)
46 examples, 1 failure, 5 pending

Failed examples:

rspec ./spec/system/admin/order_cycles/complex_editing_multiple_product_pages_spec.rb:38
```

### Context

* https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/10207854525/job/28245432196?pr=12726

### Impact and timeline

I retried the build three times on my pull request and it failed every time while it passed locally.

**Comment by mkllnk** [comment]
This seems to be an order dependent issue. I could reproduce the failure with:
```
rspec "spec/system/admin/product_import_spec.rb" "spec/system/admin/products_v3/index_spec.rb" "spec/system/admin/order_cycles/complex_editing_multiple_product_pages_spec.rb"
```

**Comment by mkllnk** [comment]
Products are listed alphabetically by name. In this example the result was:

1. `Product #11`
2. `Product #8`

I hope to resolve the issue with a given, deterministic product name.
