### ISSUE TITLE
Remove query without WHERE constraint

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#1948]
## What?

By checking the order cycle list I found a query to the `order_cycles` table without any `WHERE` constraint which can potentially crash the database or the app server:

```log
Started GET "/admin/order_cycles" for 127.0.0.1 at 2017-11-06 17:39:21 +0100                                                                
Creating scope :available. Overwriting existing method Spree::PaymentMethod.available.                                                      
Creating scope :accessible_by. Overwriting existing method OrderCycle.accessible_by.                                                        
Processing by Admin::OrderCyclesController#index as HTML 
(...)
Query Trace > app/models/order_cycle_set.rb:3:in `initialize'
     from app/controllers/admin/order_cycles_controller.rb:130:in `new'
     from app/controllers/admin/order_cycles_controller.rb:130:in `load_data_for_index'
  OrderCycle Load (0.4ms)  SELECT "order_cycles".* FROM "order_cycles"

```

The root cause is https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/models/order_cycle_set.rb#L3, which calls ActiveRecord's `.all`.

We need to understand what is that `Set` doing and refactor it before it blows up an OFN instance.

**Comment by sauloperez** [comment]
I got that `Query Trace` with https://github.com/ruckus/active-record-query-trace and adding:

```ruby
ActiveRecordQueryTrace.enabled = true
ActiveRecordQueryTrace.colorize = 'yellow'
```

In a `config/initializers/active_record_query_trace.rb`.

**Comment by enricostano** [comment]
Need to clarify severity with @sauloperez

**Comment by enricostano** [comment]
We keep the severity as `s2` but we suggest to wait for now since we don't have numbers to demonstrate that instances crash due to this.

**Comment by enricostano** [comment]
We lowered the severity of this to `s3` since we didn't hear any direct complain about it and we still don't have a monitoring infrastructure to get some meaningful data from.

**Comment by frank-west-iii** [comment]
@sauloperez, was this possibly fixed here: https://github.com/openfoodfoundation/openfoodnetwork/commit/18f7ec992d3be5ba4e16837473021c4867a870f7#diff-623e49508fae6bfca49330824ca9c39eL3

The `.all` is no longer present.

**Comment by sauloperez** [comment]
Very likely. Would you mind checking it if you happen to have your dev machine at hand?

**Comment by frank-west-iii** [comment]
Checking...
