### ISSUE TITLE
Make load_sample_data not dependent on Australia

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2071]
## Description

When running the rake task `dev:load_sample_data` from an instance where `DEFAULT_COUNTRY_CODE` is other than `AUS` (specified in https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/application.yml.example#L9) an error is raised and thus no sample data can be created.

## Expected Behavior

`dev:load_sample_data` should work in any instance and any stage (development, staging, production) regardless of the values specified in `config/application.yml`.

## Actual Behavior

When `dev:load_sample_data` is run with a `config/application.yml` containing the following:

```
# Add application configuration variables here, as shown below.
#
# Change this, it has serious security implications.
# Minimum 30 but usually 128 characters. To obtain run 'rake secret', or faster, 'openssl rand -hex 128'
SECRET_TOKEN: <classified>

TIMEZONE: Madrid
# Default country for dropdowns etc. See for codes: http://en.wikipedia.org/wiki/ISO_3166-1
DEFAULT_COUNTRY_CODE: ES
# Locale for translation.
LOCALE: es

# Find currency codes at http://en.wikipedia.org/wiki/ISO_4217.
CURRENCY: EUR
# Spree zone.
CHECKOUT_ZONE: Europe

GOOGLE_MAPS_API_KEY: <classified>
S3_ACCESS_KEY: 
S3_SECRET: 

STRIPE_CLIENT_ID: 
STRIPE_INSTANCE_SECRET_KEY: 
```

The error below is raised:

```
openfoodnetwork@staging-katuma:~/apps/openfoodnetwork/current$ bundle exec rake openfoodnetwork:dev:load_sample_data
[openfoodnetwork:dev:load_sample_data] Seeding shipping / payment information
rake aborted!
ActiveRecord::RecordInvalid: La validación falló: Provincia ó Estado no puede estar en blanco
/home/openfoodnetwork/.gem/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/validations.rb:56:in `save!'
/home/openfoodnetwork/.gem/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
```

## Steps to Reproduce

1. Log into the staging/development machine you want to use
2. Edit the contents of `config/application.yml` to have `DEFAULT_COUNTRY_CODE: ES` and `LOCALE: es`
2. Run `yes '' | bundle exec rake db:reset openfoodnetwork:dev:load_sample_data` from the app's root folder.

## Animated Gif/Screenshot

![failure](https://user-images.githubusercontent.com/762088/36096610-68941868-0ff7-11e8-9758-59b579a61f81.png)

## Context

This is blocking any testing in stagings other than the Australian one as all these sample data has to be added by hand and we can't ensure its replicability across deploys. This leads to slightly different data in DB and so we're not testing the exact same scenarios.

## Severity
Putting s2 as preventing any other dev outside Australia to provision staging servers, so blocking the process.

## Your Environment

It does not apply in this case.

## Possible Fix

Go failure by failure checking what data it relies upon and abstracting the explicit conditionals so that they don't rely on Australia only.

**Comment by sauloperez** [comment]
The actual reason why this rake task fails is because it's not localized while `db:seed` is. When deploying, the ansible task `seed database` inserts the appropriate states from the `states.yml` specific to that OFN instance.

The `openfoodnetwork:dev:load_sample_data` then tries to create factories relying on `Australia` being there. 

The line, for instance:

https://github.com/openfoodfoundation/openfoodnetwork/blob/d30362b78c0be055cd1903d4214e966447ee84da/lib/tasks/dev.rake#L41

Fails due to `Victoria` not being in the DB:

https://github.com/openfoodfoundation/openfoodnetwork/blob/d30362b78c0be055cd1903d4214e966447ee84da/spec/factories.rb#L463-L466.

**Comment by sauloperez** [comment]
- [ ] write acquired knowledge and state of the nation in the wiki
