### ISSUE TITLE
Deleted variants stay in order cycle

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#2111]
When a variant is soft deleted, it should be removed from all order cycles via `Spree::Product#delete` or `Spree::Variant#delete`. This does not always happen.

## Description

Production servers are meant to run a test to check if variants are removed from an order cycle properly after they got deleted. That test was failing for a while without us noticing. We have 194 variants on Aus production that are deleted, but are still associated to an order cycle.

## Expected Behavior

`RAILS_ENV=production bundle exec script/rails runner lib/open_food_network/integrity_checker.rb` should run and check for ghost variants.

It should find that `ExchangeVariant.joins(:variant).where('spree_variants.deleted_at IS NOT NULL').count` is `0`.

## Actual Behavior

`RAILS_ENV=production bundle exec script/rails runner lib/open_food_network/integrity_checker.rb` fails with:
```
bundler: failed to load command: script/rails (script/rails)
LoadError: cannot load such file -- rspec/rails
  /home/openfoodnetwork/.gem/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
  /home/openfoodnetwork/.gem/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
  /home/openfoodnetwork/.gem/ruby/2.1.0/gems/skylight-1.5.0/lib/skylight/probes.rb:81:in `require'
  /home/openfoodnetwork/.gem/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
  /home/openfoodnetwork/.gem/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
  /home/openfoodnetwork/.gem/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
  lib/open_food_network/integrity_checker.rb:1:in `<top (required)>'
  /home/openfoodnetwork/.gem/ruby/2.1.0/gems/railties-3.2.21/lib/rails/commands/runner.rb:52:in `eval'
  /home/openfoodnetwork/.gem/ruby/2.1.0/gems/railties-3.2.21/lib/rails/commands/runner.rb:52:in `<top (required)>'
  /home/openfoodnetwork/.gem/ruby/2.1.0/gems/railties-3.2.21/lib/rails/commands.rb:64:in `require'
  /home/openfoodnetwork/.gem/ruby/2.1.0/gems/railties-3.2.21/lib/rails/commands.rb:64:in `<top (required)>'
  script/rails:6:in `require'
  script/rails:6:in `<top (required)>'
```

And `ExchangeVariant.joins(:variant).where('spree_variants.deleted_at IS NOT NULL').count` is `194`.

## Steps to Reproduce

Run the commands above.

## Context

Rohan introduced this test in 9ccdd3b4e0a3919e9e4f16595682868012cca631 four years ago. It was the first use of the whenever gem running tasks via cron. Failed cron jobs should email the result to Rohan, but apparently that didn't happen. Moving to a new server with a working email setup, I received error messages about this failing job.

## Severity

I'm not sure if this actually affects users. It may be the cause for some other bugs. It is at least s4. Inconsistent data is always a bit scary, because we don't know why this happens. Without any action, I will receive an error message via email once a day. That is annoying.

## Your Environment

The old and new Aus production servers.

## Possible Fix

Find why the current code is failing to delete this data properly and fix it. We should also fix the cron job that should warn us about this happening so that we know if the problem is fixed.

**Comment by myriamboure** [comment]
@mkllnk is it connected to https://github.com/openfoodfoundation/openfoodnetwork/issues/2091 ? Because I ranked it s2 ;-)

**Comment by myriamboure** [comment]
No sorry nothing to do, got confused... deleting those messages.

**Comment by mkllnk** [comment]
I checked this again on Australian production and we still have 194 exchanges of deleted variants. Since it's the same number as a year ago I thought the problem may be fixed. But looking at the `updated_at` column shows dates within the last month. So this is still an issue.
