### ISSUE TITLE
Copy and run migrations

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2236]
## Description

We have to copy over the migrations from Spree and run them for our `db/schema.rb` to be updated. This is required for things like using new models from the rails console.

This doesn't avoid the necessary work of carefully investigating what these migrations do in an upcoming step.

## Expected Behavior
When using models added by Spree 2.0, such as `Spree::StockLocation`, Rails should not complain about the missing database table.

## Actual Behavior

As it is, Rails complains about the underlying database table not being present.

## Steps to Reproduce

Open a new rails console with `bundle exec rails console` and type the following:

```
irb(main):001:0> Spree::StockLocation.create
```

## Possible Fix
The actual commands to this are listed in https://guides.spreecommerce.org/developer/one-dot-three-to-two-dot-oh.html#copy-and-run-migrations

**Comment by sauloperez** [comment]
`bundle exec rake db:migrate` reports the following:

```shell
➜  openfoodnetwork copy-and-run-migrations ✗ b rake db:migrate
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
[SKYLIGHT] [1.6.1] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
rake aborted!
NoMethodError: undefined method `content_tag' for Spree:Module
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/line_item.rb:18:in `<class:LineItem>'
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/line_item.rb:2:in `<module:Spree>'
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/line_item.rb:1:in `<top (required)>'
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/variant/scopes.rb:4:in `<class:Variant>'
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/variant/scopes.rb:2:in `<module:Spree>'
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/variant/scopes.rb:1:in `<top (required)>'
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/variant.rb:194:in `<top (required)>'
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/product.rb:44:in `<class:Product>'
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/product.rb:22:in `<module:Spree>'
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/product.rb:21:in `<top (required)>'
/Users/pau/dev/openfoodnetwork/lib/spree/product_filters.rb:4:in `<module:ProductFilters>'
/Users/pau/dev/openfoodnetwork/lib/spree/product_filters.rb:2:in `<module:Spree>'
/Users/pau/dev/openfoodnetwork/lib/spree/product_filters.rb:1:in `<top (required)>'
/Users/pau/dev/openfoodnetwork/config/initializers/spree.rb:9:in `<top (required)>'
/Users/pau/dev/openfoodnetwork/config/environment.rb:5:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.1.5/bin/bundle:23:in `load'
/usr/local/opt/rbenv/versions/2.1.5/bin/bundle:23:in `<main>'
I18n::MissingTranslationData: translation missing: en.spree.validation.must_be_int
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/line_item.rb:18:in `<class:LineItem>'
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/line_item.rb:2:in `<module:Spree>'
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/line_item.rb:1:in `<top (required)>'
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/variant/scopes.rb:4:in `<class:Variant>'
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/variant/scopes.rb:2:in `<module:Spree>'
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/variant/scopes.rb:1:in `<top (required)>'
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/variant.rb:194:in `<top (required)>'
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/product.rb:44:in `<class:Product>'
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/product.rb:22:in `<module:Spree>'
/usr/local/Cellar/rbenv/1.1.1/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spree_core-2.0.4/app/models/spree/product.rb:21:in `<top (required)>'
/Users/pau/dev/openfoodnetwork/lib/spree/product_filters.rb:4:in `<module:ProductFilters>'
/Users/pau/dev/openfoodnetwork/lib/spree/product_filters.rb:2:in `<module:Spree>'
/Users/pau/dev/openfoodnetwork/lib/spree/product_filters.rb:1:in `<top (required)>'
/Users/pau/dev/openfoodnetwork/config/initializers/spree.rb:9:in `<top (required)>'
/Users/pau/dev/openfoodnetwork/config/environment.rb:5:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.1.5/bin/bundle:23:in `load'
/usr/local/opt/rbenv/versions/2.1.5/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

**Comment by sauloperez** [comment]
First, good news. https://github.com/spree/spree/commit/3fd1535e75d383fa7119d2f3b985f8c12731302c fixes this issue and after it, the app boots!! :tada: 

There are also bad news though. Said commit is present in Spree v2.0.8 according to

```shell
➜  spree (eabfb1f75) g tag --contains 3fd1535e75d383fa7119d2f3b985f8c12731302c
v2.0.10
v2.0.11
v2.0.12
v2.0.8
```

while we're at v2.0.4. So we either bring this patch to our fork or point to v2.0.8 for the upgrade. We need to weight pros and cons of both and decide.

**Comment by sauloperez** [comment]
After some thought, I lean towards `we either bring this patch to our fork`. 

## Cons
We had the dream of being able to get rid of our fork but I'm not sure yet if this will be possible, at least now. If we leave for when we get to the latest 2.0 version, that's good enough for me.

If we document we got this patch from that exact commit on the fork's README, it would make it a bit easier to spot and so easier to maintain.

## Pros
We keep the upgrade as small as possible and so as affordable as possible. Also, as it seems the app is able to boot once this patch is applied, this lets us see some light at the end of the tunnel.

thoughts @enricostano @HugsDaniel ?

**Comment by mkllnk** [comment]
Looks like a good patch.

**Comment by sauloperez** [comment]
I opened https://github.com/coopdevs/spree/pull/7 to explain this.
