### ISSUE TITLE
Refactor #shipping_address_from_distributor

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2287]
## Description

We currently set the distributor's address as the shipping address of the order when the shipping method does not require ship address. I wasn't around when this was introduced but it looks like the order model might have a presence validation for the `ship_address` attribute.

Besides, this relies on `Order#shipping_method` which is gone in Spree 2.0. Therefore, this logic needs to be refactored to work on that Spree version.

Lots of tests fail due to `#shipping_method` not being available. Like https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-2285/builds/2:

```
 311) OrderSyncer changing the ship address when a ship address is not required does not change the ship address
       Failure/Error: if shipping_method.andand.require_ship_address == false
       
       NameError:
         undefined local variable or method `shipping_method' for #<Spree::Order:0x0055fa2c8364f0>
       # ./app/models/spree/order_decorator.rb:345:in `shipping_address_from_distributor'
       # ./app/services/order_factory.rb:33:in `create_order'
       # ./app/services/order_factory.rb:12:in `create'
       # ./app/models/proxy_order.rb:52:in `initialise_order!'
       # ./spec/services/order_syncer_spec.rb:218:in `block (3 levels) in <top (required)>'
```

**Comment by sauloperez** [comment]
> it looks like the order model might have a presence validation for the ship_address attribute.

There's no such validation neither in Spree version we currently use nor in 2.0.4.

**Comment by daniellemoorhead** [comment]
@sauloperez it's been a couple of weeks any update on this - are you still working on it, or should it be put back to dev ready until you're back online?

#tidyingupthedeliverytrain

![train](https://user-images.githubusercontent.com/10949052/40818336-04ef6828-659a-11e8-8a2d-aa88ed7c2cb0.gif)

**Comment by sauloperez** [comment]
![](https://media.giphy.com/media/l0MYBbEvqqi1kfuyA/giphy.gif)

I'm back!
