### ISSUE TITLE
[Spree Upgrade] Fix reference to on_hand from products/new/replace_form.html.haml.deface 

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2688]
## Description

Our customization of the new product form still relies on the `on_hand` attribute which no longer exists. This obviously causes a 500 error as follows:

```
...
Deface: 1 overrides found for 'spree/admin/products/new'
Deface: 'replace_form' matched 0 times with 'fieldset[data-hook='new_product']'
  Rendered /home/pau/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/spree-94b1f395bbf2/backend/app/views/spree/admin/products/new.html.erb (53.5ms)
  Rendered spree/admin/products/new.js.erb (76.4ms)
Completed 500 Internal Server Error in 402.2ms (ActiveRecord: 3.0ms)
** [Bugsnag] No API key configured, couldn't notify

ActionView::Template::Error (undefined method `on_hand' for #<Spree::Product:0x00558288b3ec90>):
    1: <%# This chunk is just a copy of Spree's core/app/views/spree/admin/products/new.js.erb %>
    2: $("#new_product").html('<%= escape_javascript(render :template => "spree/admin/products/new", :formats => [:html], :handlers => [:erb]) %>');
    3: handle_date_picker_fields();
    4: <% unless Rails.env.test? %>
    5:   $('.select2').select2();
  app/views/spree/admin/products/new.js.erb:2:in `_d71e80e8183475430b44c0b1b27ac8a2'


  Rendered /home/pau/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.5ms)
...
```

## Expected Behavior
`products/new` page should render successfully without errors and allow users to specify a value for the stock level.

## Actual Behavior
The page fails to render raising the error showed above.

## Steps to Reproduce

1. Go to `/admin/products`
2. Click on `+ NEW PRODUCT`
3. an "undefined method `on_hand' for #<Spree::Product:0x0055828543c0f8> raises"

## Possible Fix
Looks like Spree 2.0 allows setting the stock level from one the section of the product form through https://github.com/openfoodfoundation/spree/blob/2-0-4-stable/api/app/controllers/spree/api/stock_items_controller.rb#L16-L32 or https://github.com/openfoodfoundation/spree/blob/2-0-4-stable/backend/app/controllers/spree/admin/stock_items_controller.rb#L13-L26.

**Comment by sauloperez** [comment]
This will fix errors like

```ruby
  66) 
    As an admin
    I want to set a supplier and distributor(s) for a product
 creating a product creating an on-demand product
      Failure/Error: $("#new_product").html('<%= escape_javascript(render :template => "spree/admin/products/new", :formats => [:html], :handlers => [:erb]) %>');
      
      ActionView::Template::Error:
        undefined method `on_hand' for #<Spree::Product:0x007faff2ea5b10>
      # ./app/views/spree/admin/products/new.js.erb:2:in `_3f3603e4e03c3ef66e22879bd1a1e5c0'
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `call'
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `respond_with'
      # ./lib/open_food_network/rack_request_blocker.rb:37:in `call'
      # ------------------
      # --- Caused by: ---
      # Capybara::ElementNotFound:
      #   Unable to find visible field "product_name" that is not disabled
      #   ./spec/features/admin/products_spec.rb:68:in `block (3 levels) in <top (required)>'
```

**Comment by sauloperez** [comment]
This got fixed already
