### ISSUE TITLE
[Spree Upgrade][BackOffice] Fix reference to Product#on_hand= in bulk_product_update_spec (7 broken tests)

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2804]
## Description
Originally this issue included 3 similar errors in product_spec. 2 were fixed in #3125 and one was moved to a new separate issue #3137

Now this issue is only related to `spec/features/admin/bulk_product_update_spec.rb`
This spec creates products providing an `on_hand` value. As this method no longer exists. This results in the following type of error:

```ruby
  33) 
  As an Administrator
  I want to be able to manage products in bulk
 listing products displays an on hand count in a span for each product
      Failure/Error: p1 = FactoryBot.create(:product, on_hand: 15)
      
      NoMethodError:
        undefined method `on_hand=' for #<Spree::Product:0x0055d1b1522dc0>
      # ./spec/features/admin/bulk_product_update_spec.rb:58:in `block (3 levels) in <top (required)>'
```

There are currently 7 broken tests with this error (see in a comment below).

## Possible Fix

Similar to `VariantStock`, we need to provide an adapter that provides backward compatibility between our code and Spree 2.0's `Product`.
Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/2802.

**Comment by luisramos0** [comment]
We need to validate if this method is needed in live code (controllers?). If not needed, the specs should be adapted to set these values on the variant.

**Comment by luisramos0** [comment]
List of errors:
```
 28) Spree::Product validations and defaults does not save when master is invalid
      Failure/Error: product.on_hand = "10,000"
      
      NoMethodError:
        undefined method `on_hand=' for #<Spree::Product:0x0055806be4e620>
      # ./spec/models/spree/product_spec.rb:29:in `block (3 levels) in <module:Spree>'

  29) Spree::Product validations and defaults when the product has variants saving a new product copies the properties on master variant to the first standard variant
      Failure/Error: product.on_hand = 3
      
      NoMethodError:
        undefined method `on_hand=' for #<Spree::Product:0x007effe2b67dd8>
      # ./spec/models/spree/product_spec.rb:109:in `block (5 levels) in <module:Spree>'

  30) Spree::Product validations and defaults when the product has variants saving a new product only duplicates master with after_save when no standard variants exist
      Failure/Error: product.on_hand = 3
      
      NoMethodError:
        undefined method `on_hand=' for #<Spree::Product:0x007effe342c2c0>
      # ./spec/models/spree/product_spec.rb:109:in `block (5 levels) in <module:Spree>'


17) 
  As an Administrator
  I want to be able to manage products in bulk
 updating a product with variants
      Failure/Error:
        p = FactoryBot.create(:product, supplier: s1, available_on: Date.current, variant_unit: 'volume', variant_unit_scale: 0.001,
          price: 3.0, on_hand: 9, unit_value: 0.25, unit_description: '(bottle)' )
      
      NoMethodError:
        undefined method `on_hand=' for #<Spree::Product:0x007effddf197d8>
      # ./spec/features/admin/bulk_product_update_spec.rb:311:in `block (2 levels) in <top (required)>'

  18) 
  As an Administrator
  I want to be able to manage products in bulk
 listing products displays an on hand count in a span for each product
      Failure/Error: p1 = FactoryBot.create(:product, on_hand: 15)
      
      NoMethodError:
        undefined method `on_hand=' for #<Spree::Product:0x007effde5f51b0>
      # ./spec/features/admin/bulk_product_update_spec.rb:58:in `block (3 levels) in <top (required)>'

  21) 
  As an Administrator
  I want to be able to manage products in bulk
 as an enterprise manager shows only products that I supply
      Failure/Error: let!(:product_supplied) { create(:product, supplier: supplier_managed1, price: 10.0, on_hand: 6) }
      
      NoMethodError:
        undefined method `on_hand=' for #<Spree::Product:0x0055806d9ee0b0>
      # ./spec/features/admin/bulk_product_update_spec.rb:633:in `block (3 levels) in <top (required)>'

  22) 
  As an Administrator
  I want to be able to manage products in bulk
 as an enterprise manager shows only suppliers that I manage or have permission to
      Failure/Error: let!(:product_supplied) { create(:product, supplier: supplier_managed1, price: 10.0, on_hand: 6) }
      
      NoMethodError:
        undefined method `on_hand=' for #<Spree::Product:0x005580684143d8>
      # ./spec/features/admin/bulk_product_update_spec.rb:633:in `block (3 levels) in <top (required)>'

 23) 
  As an Administrator
  I want to be able to manage products in bulk
 as an enterprise manager shows inactive products that I supply
      Failure/Error: let!(:product_supplied) { create(:product, supplier: supplier_managed1, price: 10.0, on_hand: 6) }
      
      NoMethodError:
        undefined method `on_hand=' for #<Spree::Product:0x005580637fc0b8>
      # ./spec/features/admin/bulk_product_update_spec.rb:633:in `block (3 levels) in <top (required)>'

  24) 
  As an Administrator
  I want to be able to manage products in bulk
 as an enterprise manager allows me to create a product
      Failure/Error: let!(:product_supplied) { create(:product, supplier: supplier_managed1, price: 10.0, on_hand: 6) }
      
      NoMethodError:
        undefined method `on_hand=' for #<Spree::Product:0x007effdece8ad0>
      # ./spec/features/admin/bulk_product_update_spec.rb:633:in `block (3 levels) in <top (required)>'

  25) 
  As an Administrator
  I want to be able to manage products in bulk
 as an enterprise manager allows me to update a product
      Failure/Error: let!(:product_supplied) { create(:product, supplier: supplier_managed1, price: 10.0, on_hand: 6) }
      
      NoMethodError:
        undefined method `on_hand=' for #<Spree::Product:0x007effcc021480>
      # ./spec/features/admin/bulk_product_update_spec.rb:633:in `block (3 levels) in <top (required)>'


```

**Comment by luisramos0** [comment]
So, I asked the question: can we make OFN more simple and like Spree remove completely product.on_hand? I think the answer is yes. So I just went and fixed the specs with this approach. If you want to set on_hand values, you need a variant.
If later on we find it's not possible or too difficult, we can re-think this approach.

**Comment by sauloperez** [comment]
How will we deal with the new product's form on_hand field? Do we assign it to the master variant? If I'm not mistaken that's what we said last time: forget about the licky abstraction of product attributes that actually belong to variants; either master or non-master.

Did we write this down somewhere?

**Comment by luisramos0** [comment]
I dont think it's written anywhere apart from this conversation now :-)
I am just waiting for https://github.com/openfoodfoundation/openfoodnetwork/issues/3051 to be merged into 2-0 so we can test/fix the new product page. That is scope for #3018.

**Comment by luisramos0** [comment]
I just confirmed in the 2-0-stable build and with both 3139 and 3132 merged, all 7 tests are passing.
