### ISSUE TITLE
[Product Import] Importing products with special characters fails

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#2836]
## Description

The product import expects CSV files in UTF-8 character encoding. If the uploaded file is in a different encoding and contains characters like German umlauts, the application crashes (500 server error).

## Expected Behavior

Uploading an invalid file results in a validation error being displayed.

## Actual Behavior

The generic snail page is displayed. The log contains:
```
ArgumentError (invalid byte sequence in UTF-8):
  app/models/product_import/product_importer.rb:223:in `rows'
  app/models/product_import/product_importer.rb:245:in `build_entries'
  app/models/product_import/product_importer.rb:180:in `init_product_importer'
  app/models/product_import/product_importer.rb:38:in `initialize'
  app/controllers/admin/product_import_controller.rb:15:in `new'
  app/controllers/admin/product_import_controller.rb:15:in `import'
```

## Steps to Reproduce

1. Go to the product import, e.g. https://openfoodnetwork.de/admin/product_import
2. Select a file containing special characters in a local encoding. 
[KL test 181005 3.txt](https://github.com/openfoodfoundation/openfoodnetwork/files/2454719/KL.test.181005.3.txt) (rename to `.csv`)
3. Click "Upload"

## Context

Kirsten was testing the product import for the first German enterprises with a test file. They are pulling the data from another database.

## Severity

s3 as product import is not officially released and it affects only some users. The workaround is to use UTF8-encoded CSV files.

## Your Environment

* Version used: 58a99a7f8993cf609d930a68d82b382fccce8ea4

## Possible Fix

Rescue the `ArgumentError` and display a helpful message: "Please check the language setting of your source file and ensure it is saved in UTF-8.csv encoding".

**Comment by kirstenalarsen** [comment]
thanks @mkllnk - I had saved this file as a csv so not sure why it was a .txt? 

I have just gone back and saved the original file to comma delimited csv utf-8 and now it has even weirder stuff appearing in the file e.g.

![image](https://user-images.githubusercontent.com/2911176/46593037-de591f80-cb13-11e8-9221-7fc050e0e965.png)

I'm a bit unclear on next steps here - do I need to ask them to generate a different source file or I need to wait until this issue is dealt with before we can import these characters? 

Also I am not sure if we need to create an additional issue - the way this bug is written suggests that we just need a validation error, but we don't need just a validation error, we need to be able to actually import the characters?

**Comment by kirstenalarsen** [comment]
Ah ha!! I just need to change the language on the file before I save as utf-8 csv!! yippeee we're good to go :) @mkllnk

**Comment by kirstenalarsen** [comment]
So perhaps when dealing with this issue . . we could include in the validation warning some info like "please check the language setting of your source file and ensure it is saved in UTF-8.csv encoding"

**Comment by myriamboure** [comment]
@kirstenalarsen when you say "check the language setting of your source code", what do you mean, should each language be set to the appropriate one before encoding to UTF-8? Just to be sure I get it.

**Comment by kirstenalarsen** [comment]
I just used Excel, Tools, Language and changed it to German .. then saving my files as UTF-8 csv worked

**Comment by myriamboure** [comment]
Can you check this remaining issue in product import project @Matt-Yorkley ? The solution proposed by Maikel seems pretty straightforward and might avoid user support issues in lots of countries... if that could be solved before official release event better, but probably won't prevent the release.

**Comment by Matt-Yorkley** [comment]
Sure, I'll see if I can add an encoding check during the file upload.

**Comment by Matt-Yorkley** [comment]
I've investigated this issue a bit, but it's a tricky one to work with. It seems to revolve around the fact that Microsoft Excel doesn't always use UTF-8, but often defaults to obscure Windows character sets.

It also seems like there is no simple way to find out the character encoding for a given file?

**Comment by Matt-Yorkley** [comment]
@kirstenalarsen can you send me a copy of a CSV with the wrong encoding in Slack? I can't even make a broken one to test with.

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley @RachL it's been 18 days since this went back to the In Dev column and no activity since.

Is this a bigger priority than the other work on Matt's list at the moment? Should we be prioritising the product import work (finally) being done and dusted and not thought about anymore, over bulk invoice printing and other things? I'd like to think the answer is yes, but will leave it to you both to decide.

#toomanythingsinthepipe
#toottoot

**Comment by myriamboure** [comment]
Agree with you @daniellemoorhead I commented on the PR as we are kind of stuck on how to move forward on this one, but I'm putting some reminder of the last other remaining issues for @Matt-Yorkley to tackle them :-)
