### ISSUE TITLE
[Spree Upgrade] Line Items Controller Spec (2 broken tests)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2929]
Fix this spec:

```
36) LineItemsController destroying a line item on a completed order where shipping and payment fees apply updates the fees
      Failure/Error: expect(order.adjustment_total).to eq initial_fees
      
        expected: 16
             got: 10.0 (#<BigDecimal:7f73235acab0,'0.1E2',9(18)>)
      
        (compared using ==)
      # ./spec/controllers/line_items_controller_spec.rb:107:in `block (4 levels) in <top (required)>'
```

**Comment by luisramos0** [comment]
This spec is now broken like this. The original error is gone. We need to see if #2930 is still needed.

```
27) LineItemsController listing bought items lists items bought by the user from the same shop in the same order_cycle
      Failure/Error: expect(json_response[0]['id']).to eq completed_order.line_items.first.id
      
        expected: 149
             got: 153
      
        (compared using ==)
      # ./spec/controllers/line_items_controller_spec.rb:26:in `block (3 levels) in <top (required)>'

  28) LineItemsController destroying a line item on a completed order with shipping and payment fees updates the fees
      Failure/Error: expect(order.shipments.last.adjustment.included_tax).to eq 1.2
      
        expected: 1.2
             got: 0.0 (#<BigDecimal:7f5e3286bae0,'0.0',9(18)>)
      
        (compared using ==)
      # ./spec/controllers/line_items_controller_spec.rb:110:in `block (4 levels) in <top (required)>'

  29) LineItemsController destroying a line item on a completed order with enterprise fees updates the fees
      Failure/Error: expect(order.reload.adjustment_total).to eq enterprise_fee.calculator.preferred_amount
      
        expected: 1.0 (#<BigDecimal:7f5e30764590,'0.1E1',9(18)>)
             got: 5.0 (#<BigDecimal:7f5e30765990,'0.5E1',9(18)>)
      
        (compared using ==)
      # ./spec/controllers/line_items_controller_spec.rb:146:in `block (4 levels) in <top (required)>'
```

**Comment by luisramos0** [comment]
Merge from master fixed the first broken spec. I will rebase now and see the impact.
