### ISSUE TITLE
[Spree Upgrade][Admin/Orders/Edit] Fix translation issue in Admin Orders Spec (3 broken tests)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2935]
Translation issue on variant autocomplete.

Fix this issue:

```
24) 
    As an administrator
    I want to manage orders
 can add a product to an existing order
      Failure/Error: targetted_select2_search @product.name, from: '#add_variant_id', dropdown_css: '.select2-drop'
      
      Capybara::Poltergeist::JavascriptError:
        One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
      
        No translation found for on_hand. Does it exist within spree/admin/shared/_translations.html.erb?
        No translation found for on_hand. Does it exist within spree/admin/shared/_translations.html.erb?
            at http://127.0.0.1:39343/assets/admin/all.js:76886
      # ./spec/features/admin/orders_spec.rb:93:in `block (2 levels) in <top (required)>'

```

This comes from app/views/spree/admin/variants/_autocomplete.js.erb
This problem should be addressed in #2416 but should be verified. the autocomplete template should be a normal ofn assets template and use normal ofn js translations.

**Comment by luisramos0** [comment]
A very bad quick fix for this error is to add this line:
`    :on_hand                  => Spree.t(:on_hand),`
to 
spree/app/views/spree/admin/shared/_translations.html.erb

**Comment by luisramos0** [comment]
Adding here two more broken tests with the same error.
In the same admin/orders_spec:

```
  7) 
    As an administrator
    I want to manage orders
 as an enterprise manager creating an order with distributor and order cycle
     Failure/Error: targetted_select2_search product.name, from: '#add_variant_id', dropdown_css: '.select2-drop'
     
     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
     
       No translation found for on_hand. Does it exist within spree/admin/shared/_translations.html.erb?
       No translation found for on_hand. Does it exist within spree/admin/shared/_translations.html.erb?
           at http://127.0.0.1:35234/assets/admin/all.js:76886
     # ./spec/features/admin/orders_spec.rb:319:in `block (3 levels) in <top (required)>'
```

and also in admin/variant_overrides_spec.rb:

```
5) 
  As an Administrator
  With products I can add to my hub's inventory
  I want to override the stock level and price of those products
  Without affecting other hubs that share the same products
 as an enterprise user when manually placing an order shows the overridden price
     Failure/Error: targetted_select2_search product.name, from: '#add_variant_id', dropdown_css: '.select2-drop'
     
     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
     
       No translation found for on_hand. Does it exist within spree/admin/shared/_translations.html.erb?
       No translation found for on_hand. Does it exist within spree/admin/shared/_translations.html.erb?
           at http://127.0.0.1:43743/assets/admin/all.js:76886
     # ./spec/features/admin/variant_overrides_spec.rb:339:in `block (4 levels) in <top (required)>'

```

**Comment by HugsDaniel** [comment]
@luisramos0 I don't get the same error here : 
```
 1) 
  As an Administrator
  With products I can add to my hub's inventory
  I want to override the stock level and price of those products
  Without affecting other hubs that share the same products
 as an enterprise user when manually placing an order shows the overridden price
     Failure/Error: click_link 'Add'
     
     Capybara::ElementNotFound:
       Unable to find visible link "Add"
     # ./spec/features/admin/variant_overrides_spec.rb:340:in `block (4 levels) in <top (required)>'
```

Same for the three specs. It's related to the new way of adding products to an order in 2-0. There's no "Add" button anymore, now it's done in JS as soon as you select the product to add.

These will be fixed when we implement the new views for admin order #new and #edit. Seems like a good opportunity to tackle that, what do you think ?

**Comment by luisramos0** [comment]
There must be something wrong with your local.
the source of truth:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/2-0-stable/builds/125
Look for variant_overrides_spec.rb:339 in job #4

**Comment by luisramos0** [comment]
but anyway, yes! The Add problem will arise afterwards anyway and we will tackle it as part of #3018 right?
Let's wait for #2955 to be merged into master to then merge master again into 2-0-stable. after that we can see how are the product new and edit pages on 2-0-stable.

**Comment by luisramos0** [comment]
@HugsDaniel looks like this error is gone :-D

**Comment by luisramos0** [comment]
I think we can close.
