### ISSUE TITLE
[Spree Upgrade][Broken Test][Admin/Orders/List] Fix the Edit Orders button test problem

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2939]
Fix this spec:

```
1)
    As an administrator
    I want to manage orders
 displays error when incorrect distribution for products is chosen
     Failure/Error: end

     Capybara::Ambiguous:
       Ambiguous match, found 2 elements matching visible css ".icon-edit"
     # /Users/luisramos/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/capybara-2.18.0/lib/capybara/node/finders.rb:311:in `block in synced_resolve'
     # /Users/luisramos/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/capybara-2.18.0/lib/capybara/node/base.rb:85:in `synchronize'
     # /Users/luisramos/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/capybara-2.18.0/lib/capybara/node/finders.rb:302:in `synced_resolve'
     # /Users/luisramos/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/capybara-2.18.0/lib/capybara/node/finders.rb:37:in `find'
     # /Users/luisramos/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/capybara-2.18.0/lib/capybara/session.rb:808:in `block (2 levels) in <class:Session>'
     # /Users/luisramos/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/capybara-2.18.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # /Users/luisramos/dev/ofn/spree/core/lib/spree/testing_support/capybara_ext.rb:7:in `click_icon'
     # ./spec/features/admin/orders_spec.rb:357:in `click_edit'
     # ./spec/features/admin/orders_spec.rb:115:in `block (2 levels) in <top (required)>'
     # /Users/luisramos/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:123:in `block in run'
     # /Users/luisramos/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `loop'
     # /Users/luisramos/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `run'
     # /Users/luisramos/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/rspec-retry-0.6.1/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /Users/luisramos/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:37:in `block (2 levels) in setup'

```

This is the source of the problem:

  ```
# Working around intermittent click failing
  # Possible causes of failure:
  #  - the link moves
  #  - the missing content (font icon only)
  #  - the screen is not big enough
  # However, some operations before the click or a second click on failure work.
  #
  # A lot of people had similar problems:
  # https://github.com/teampoltergeist/poltergeist/issues/520
  # https://github.com/thoughtbot/capybara-webkit/issues/494
  def click_edit
    click_result = click_icon :edit
    unless click_result['status'] == 'success'
      click_icon :edit
    end
  end

```

The click is successful but click_result['status'] is not present and so it tries to click again and fails with the error above.
The quick fix is to comment out the unless statement in this method above.

We have two options:
- replace status == success with something that works in spree 2 (why did it stop working?)
- Remove this fix and risk having the build unstable on these specs (we can have a look at this when the build starts to fail regularly, may not be the case as it’s a diff version of spree and OFN)

**Comment by luisramos0** [comment]
@mkllnk I think you are the last committer on this method, you may have some idea how to get around this or what to do with this :-)

**Comment by mkllnk** [comment]
The error message says that there are two edit buttons. We have to check the screen to see if they are both the same. If they are the same, we can decide if we want to get rid of one. If they are not the same, we need a way to distinguish between them to click the right one.

That method is just to get around an intermittent click fail, possibly a browser bug. Maybe we don't need it anymore. But maybe we need to keep it until we upgrade to headless chrome in tests.

**Comment by Matt-Yorkley** [comment]
I've made a PR and it looks like it gets past that error, and moves onto a new error in the next line... :tada:
