### ISSUE TITLE
[Spree Upgrade][Admin/Orders/Edit] Fix Actions menu on order edit page (1 broken test)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2941]
Actions dropdown on orders edit page are not showing up.

```
 10) 
    As an administrator
    I want to manage orders
 as an enterprise manager viewing the edit page shows the dropdown menu
      Failure/Error: find("#links-dropdown .ofn-drop-down").click
      
      Capybara::ElementNotFound:
        Unable to find visible css "#links-dropdown .ofn-drop-down"
      # ./spec/features/admin/orders_spec.rb:264:in `block (4 levels) in <top (required)>'

  11) 
    As an administrator
    I want to manage orders
 as an enterprise manager viewing the edit page can print an order's ticket
      Failure/Error: find("#links-dropdown .ofn-drop-down").click
      
      Capybara::ElementNotFound:
        Unable to find visible css "#links-dropdown .ofn-drop-down"
      # ./spec/features/admin/orders_spec.rb:276:in `block (4 levels) in <top (required)>'
```

**Comment by luisramos0** [comment]
Looks like there's only one error now:
```
  9) 
    As an administrator
    I want to manage orders
 as an enterprise manager viewing the edit page shows the dropdown menu
     Failure/Error: expect(page).to have_link "Edit", href: spree.edit_admin_order_path(@order)
       expected to find visible link "Edit" within #<Capybara::Node::Element tag="li" path="//HTML[1]/BODY[1]/DIV[1]/DIV[1]/DIV[3]/DIV[1]/DIV[1]/DIV[1]/DIV[2]/UL[1]/LI[3]"> but there were no matches
     # ./spec/features/admin/orders_spec.rb:266:in `block (5 levels) in <top (required)>'
     # ./spec/features/admin/orders_spec.rb:265:in `block (4 levels) in <top (required)>'
```
