### ISSUE TITLE
[Spree Upgrade][Broken Test] Model - Fix Enterprise spec

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2942]
Some kind of "delete cascade" not working properly on enterprise_spec, it should delete products but instead it's failing with a constraint error:

```
12) Enterprise associations destroys supplied products upon destroy
      Failure/Error: s.destroy
      
      ActiveRecord::InvalidForeignKey:
        PG::ForeignKeyViolation: ERROR:  update or delete on table "enterprises" violates foreign key constraint "spree_products_supplier_id_fk" on table "spree_products"
        DETAIL:  Key (id)=(389) is still referenced from table "spree_products".
        : DELETE FROM "enterprises" WHERE "enterprises"."id" = $1
      # ./spec/models/enterprise_spec.rb:40:in `block (3 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # PG::ForeignKeyViolation:
      #   ERROR:  update or delete on table "enterprises" violates foreign key constraint "spree_products_supplier_id_fk" on table "spree_products"
      #   DETAIL:  Key (id)=(389) is still referenced from table "spree_products".
      #   ./spec/models/enterprise_spec.rb:40:in `block (3 levels) in <top (required)>'

```

**Comment by Matt-Yorkley** [comment]
We've figured this one out now, it's the paranoia gem interrupting the real deletion of the product whilst deleting the enterprise.
