### ISSUE TITLE
[Spree Upgrade][Models] Fix line Item spec (4 broken tests)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2943]
Quite a few different errors in spec/models/spree/line_item_spec.rb
Most of the broken tests in line item spec are related to variant overrides and scoping. First we need to take care of #2559 

PR #3132 fixed one of the originally 11 broken tests (spec/models/spree/line_item_spec.rb:96).

The remaining 10 broken tests are:

```
  8) Spree::LineItem capping quantity at stock level caps at zero when stock is negative
     Failure/Error: update_attributes!(quantity: variant.on_hand) if quantity > variant.on_hand
     
     ActiveRecord::RecordInvalid:
       Validation failed: Quantity "Product #168 - 8121 (1g, S)" is out of stock.
     # ./app/models/spree/line_item_decorator.rb:65:in `cap_quantity_at_stock!'
     # ./spec/models/spree/line_item_spec.rb:102:in `block (3 levels) in <module:Spree>'

  9) Spree::LineItem capping quantity at stock level when a variant override is in place caps quantity to override stock level
     Failure/Error: li.remove_instance_variable(:@scoper)
     
     NameError:
       instance variable @scoper not defined
     # ./spec/models/spree/line_item_spec.rb:115:in `remove_instance_variable'
     # ./spec/models/spree/line_item_spec.rb:115:in `block (4 levels) in <module:Spree>'

  10) Spree::LineItem capping quantity at stock level when a variant override is in place when count on hand is negative caps at zero
      Failure/Error: li.remove_instance_variable(:@scoper)
      
      NameError:
        instance variable @scoper not defined
      # ./spec/models/spree/line_item_spec.rb:115:in `remove_instance_variable'
      # ./spec/models/spree/line_item_spec.rb:115:in `block (4 levels) in <module:Spree>'

  11) Spree::LineItem tracking stock when quantity is changed when the order is already complete when a variant override applies draws stock from the variant override
      Failure/Error: expect{line_item.increment!(:quantity)}.to_not change{Spree::Variant.find(variant.id).on_hand}
        expected `Spree::Variant.find(variant.id).on_hand` not to have changed, but did change from 4 to 3
      # ./spec/models/spree/line_item_spec.rb:147:in `block (5 levels) in <module:Spree>'

  12) Spree::LineItem tracking stock when a line item is destroyed when the order is already complete when a variant override applies restores stock to the variant override
      Failure/Error: expect(vo.reload.count_on_hand).to eq 4
      
        expected: 4
             got: 3
      
        (compared using ==)
      # ./spec/models/spree/line_item_spec.rb:173:in `block (5 levels) in <module:Spree>'

  13) Spree::LineItem tracking stock when a line item is destroyed when the order is already complete when a variant override does not apply restores stock to the variant
      Failure/Error: expect{line_item.destroy}.to change{Spree::Variant.find(variant.id).on_hand}.by(1)
        expected `Spree::Variant.find(variant.id).on_hand` to have changed by 1, but was changed by 0
      # ./spec/models/spree/line_item_spec.rb:179:in `block (5 levels) in <module:Spree>'

  14) Spree::LineItem determining if sufficient stock is present when stock on the variant is sufficient 
      Failure/Error: li.remove_instance_variable(:@scoper)
      
      NameError:
        instance variable @scoper not defined
      # ./spec/models/spree/line_item_spec.rb:194:in `remove_instance_variable'
      # ./spec/models/spree/line_item_spec.rb:194:in `block (3 levels) in <module:Spree>'

  15) Spree::LineItem determining if sufficient stock is present when the stock on the variant is not sufficient when no variant override is in place 
      Failure/Error: li.remove_instance_variable(:@scoper)
      
      NameError:
        instance variable @scoper not defined
      # ./spec/models/spree/line_item_spec.rb:194:in `remove_instance_variable'
      # ./spec/models/spree/line_item_spec.rb:194:in `block (3 levels) in <module:Spree>'

  16) Spree::LineItem determining if sufficient stock is present when the stock on the variant is not sufficient when a variant override is in place and stock on the variant override is sufficient 
      Failure/Error: li.remove_instance_variable(:@scoper)
      
      NameError:
        instance variable @scoper not defined
      # ./spec/models/spree/line_item_spec.rb:194:in `remove_instance_variable'
      # ./spec/models/spree/line_item_spec.rb:194:in `block (3 levels) in <module:Spree>'

  17) Spree::LineItem determining if sufficient stock is present when the stock on the variant is not sufficient when a variant override is in place and stock on the variant override is not sufficient 
      Failure/Error: li.remove_instance_variable(:@scoper)
      
      NameError:
        instance variable @scoper not defined
      # ./spec/models/spree/line_item_spec.rb:194:in `remove_instance_variable'
      # ./spec/models/spree/line_item_spec.rb:194:in `block (3 levels) in <module:Spree>'
```

**Comment by pfac** [comment]
@luisramos0 can you provide more information on this issue?

Just ran `bundle exec rspec spec/models/spree/line_item_spec.rb`, got no errors, just some deprecation warnings:

```
Knapsack adapter is off!
The PGconn, PGresult, and PGError constants are deprecated, and will be removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from .../ruby/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/postgresql_adapter.rb:28:in `new' (eval):1: warning: encountered \r in middle of line, treated as a mere space
The factory_girl gem has been deprecated and has been replaced by factory_bot. Please switch to factory_bot as soon as possible.
DEPRECATION WARNING: `#ignore` is deprecated and will be removed in 5.0. Please use `#transient` instead. (called from block (2 levels) in <top (required)> at .../openfoodnetwork/spec/factories.rb:299)
Run options: exclude {:skip=>true, :future=>true, :to_figure_out=>true}
 54/54 |====================================================================================== 100 ======================================================================================>| Time: 00:01:02

Deprecation Warnings:

Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from .../openfoodnetwork/spec/models/spree/line_item_spec.rb:32:in `block (3 levels) in <module:Spree>'.

Using `stub` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead. Called from .../openfoodnetwork/spec/models/spree/line_item_spec.rb:231:in `block (3 levels) in <module:Spree>'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

2 deprecation warnings total

Finished in 1 minute 2.93 seconds (files took 30.42 seconds to load)
54 examples, 0 failures
Coverage report generated for RSpec to .../openfoodnetwork/coverage. 4765 / 10761 LOC (44.28%) covered.
```

**Comment by luisramos0** [comment]
sure, there's some high level context missing :-)

Spree is the main dependency of OFN: https://github.com/spree/spree
OFN has it's own spree fork but not too far from spree itself:
https://github.com/openfoodfoundation/spree
Currently ofn master depends on spree step-6a here which is spree 1.x: 
https://github.com/openfoodfoundation/spree/tree/step-6a

All issues with [Spree Upgrade] are related to the spree upgrade branch where we are working on upgrading to spree 2.0.4.
So, this issue is related to OFN branch https://github.com/openfoodfoundation/openfoodnetwork/tree/2-0-stable
that depends on Spree 2-0-4:
https://github.com/openfoodfoundation/spree/tree/2-0-4-stable

the build is currently broken with "only" 5% of the tests broken, this issue represents an example.

For your reference, you can see the build results here:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/2-0-stable/builds/73

I have added an example error in the issue description.

**Comment by luisramos0** [comment]
I am not sure I was clear but this is a tricky place to start. I'd start with something easier and then move into more challenging things.
Isolated issues are the best place to start, if you have experience with the tech stack, I have just flagged this issue as an interesting challenge, for example: https://github.com/openfoodfoundation/openfoodnetwork/issues/2944

**Comment by luisramos0** [comment]
The broken specs are separate and will require some investigation so I created separate issues for them. #3204 and #3205. Closing this one.
