### ISSUE TITLE
[Spree Upgrade] Fix accessing new product

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2982]
## Description

When clicking on `+ NEW PRODUCT`, a 500 error is returned with the following error:

```
Completed 500 Internal Server Error in 438.5ms (ActiveRecord: 1.8ms)
** [Bugsnag] No API key configured, couldn't notify

ActionView::Template::Error (undefined method `backorderable?' for nil:NilClass):
    1: <%# This chunk is just a copy of Spree's core/app/views/spree/admin/products/new.js.erb %>
    2: $("#new_product").html('<%= escape_javascript(render :template => "spree/admin/products/new", :formats => [:html], :handlers => [:erb]) %>');
    3: handle_date_picker_fields();
    4: <% unless Rails.env.test? %>
    5:   $('.select2').select2();
  app/models/concerns/variant_stock.rb:87:in `on_demand'
  app/models/concerns/variant_stock.rb:31:in `on_hand'
  app/models/spree/product_decorator.rb:138:in `on_hand'
  app/views/spree/admin/products/new.js.erb:2:in `_ac8cba3fd61d6e0362ef0d2ce3c49503'


  Rendered /home/pau/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.1ms)
  Rendered /home/pau/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (1.1ms)
  Rendered /home/pau/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/templates/rescues/template_error.erb within rescues/layout (14.7ms)
  Rendered /home/pau/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/templates/rescues/layout.erb (15.8ms)
```

## Expected Behavior

Clicking this button should show the order creation page.

## Actual Behavior

The 500 error decribed above gets raised and nothing happens on the page.

## Possible Fix

According to the comment present on `app/views/spree/admin/products/new.js.erb`

```
 This chunk is just a copy of Spree's core/app/views/spree/admin/products/new.js.erb
```

but it turns out this view got moved in https://github.com/openfoodfoundation/spree/commit/e1e175c1c

**Comment by sauloperez** [comment]
I'm trying to understand and maybe fix this in order to try out the solution I came up with https://github.com/openfoodfoundation/openfoodnetwork/issues/2870

**Comment by luisramos0** [comment]
Note: "undefined method `backorderable?' for nil:NilClass" means variant.stock_items.first is Nil. Something to do with creating stock items for the new product's master variant?

**Comment by luisramos0** [comment]
I have created an issue #3018 to represent the same error in the specs.

**Comment by sauloperez** [comment]
Let's not forget to check https://github.com/openfoodfoundation/openfoodnetwork/issues/2689 after working on this one.

**Comment by sigmundpetersen** [comment]
@sauloperez can we unblock as #3049 is closed?

**Comment by luisramos0** [comment]
yes, ready for dev. thanks @sigmundpetersen
