### ISSUE TITLE
[Spree Upgrade][FrontOffice] Fix cart_controller_specs errors related to on_hand numbers (3 broken tests)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3017]
Fix the 3 broken tests in cart_controller_spec.

Probably some detail related to the new variant.on_hand adapter introduced in #2615.

```
  24) CartController returning stock levels in JSON on success generating stock levels returns a hash with variant id, quantity, max_quantity and stock on hand
      Failure/Error:
        expect(controller.stock_levels(order, [v.id])).to eq(
          {v.id => {quantity: 2, max_quantity: 3, on_hand: 4}}
        )
      
        expected: {1523=>{:quantity=>2, :max_quantity=>3, :on_hand=>4}}
             got: {1523=>{:quantity=>2, :max_quantity=>3, :on_hand=>5}}
      
        (compared using ==)
      
        Diff:
        @@ -1,2 +1,2 @@
        -1523 => {:quantity=>2, :max_quantity=>3, :on_hand=>4},
        +1523 => {:quantity=>2, :max_quantity=>3, :on_hand=>5},
        
      # ./spec/controllers/cart_controller_spec.rb:36:in `block (4 levels) in <top (required)>'

  25) CartController returning stock levels in JSON on success generating stock levels includes all line items, even when the variant_id is not specified
      Failure/Error:
        expect(controller.stock_levels(order, [])).to eq(
          {v.id => {quantity: 2, max_quantity: 3, on_hand: 4}}
        )
      
        expected: {1529=>{:quantity=>2, :max_quantity=>3, :on_hand=>4}}
             got: {1529=>{:quantity=>2, :max_quantity=>3, :on_hand=>5}}
      
        (compared using ==)
      
        Diff:
        @@ -1,2 +1,2 @@
        -1529 => {:quantity=>2, :max_quantity=>3, :on_hand=>4},
        +1529 => {:quantity=>2, :max_quantity=>3, :on_hand=>5},
        
      # ./spec/controllers/cart_controller_spec.rb:42:in `block (4 levels) in <top (required)>'

  26) CartController returning stock levels in JSON on success generating stock levels includes an empty quantity entry for variants that aren't in the order
      Failure/Error:
        expect(controller.stock_levels(order, [v.id, v2.id])).to eq(
          {v.id  => {quantity: 2, max_quantity: 3, on_hand: 4},
           v2.id => {quantity: 0, max_quantity: 0, on_hand: 2}}
        )
      
        expected: {1535=>{:quantity=>2, :max_quantity=>3, :on_hand=>4}, 1538=>{:quantity=>0, :max_quantity=>0, :on_hand=>2}}
             got: {1535=>{:quantity=>2, :max_quantity=>3, :on_hand=>5}, 1538=>{:quantity=>0, :max_quantity=>0, :on_hand=>5}}
      
        (compared using ==)
      
        Diff:
        @@ -1,3 +1,3 @@
        -1535 => {:quantity=>2, :max_quantity=>3, :on_hand=>4},
        -1538 => {:quantity=>0, :max_quantity=>0, :on_hand=>2},
        +1535 => {:quantity=>2, :max_quantity=>3, :on_hand=>5},
        +1538 => {:quantity=>0, :max_quantity=>0, :on_hand=>5},
        
      # ./spec/controllers/cart_controller_spec.rb:48:in `block (4 levels) in <top (required)>'

```

**Comment by luisramos0** [comment]
yes, thanks @sigmundpetersen I confirmed, these tests are passing in 2-0-stable.
