### ISSUE TITLE
[Spree Upgrade][BackOffice] Fix New Product page specs - "undefined method `backorderable?'" in features/admin/products_spec and bulk_product_update_spec (5 broken tests)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3018]
Same error as in #2982 but in the specs.
Variant.stock_item is null in these cases. It can never be null.

```ruby
  15) 
  As an Administrator
  I want to be able to manage products in bulk
 creating a new product
      Failure/Error: stock_items.first.backorderable?
      
      ActionView::Template::Error:
        undefined method `backorderable?' for nil:NilClass
      # ./app/models/concerns/variant_stock.rb:88:in `on_demand'
      # ./app/models/concerns/variant_stock.rb:32:in `on_hand'
      # ./app/models/spree/product_decorator.rb:138:in `on_hand'
      # ./app/views/spree/admin/products/new.js.erb:2:in `_7257b43a6e016831f9b0f141204d36c3'
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `call'
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `respond_with'
      # ./lib/open_food_network/rack_request_blocker.rb:37:in `call'
      # ------------------
      # --- Caused by: ---
      # Capybara::ElementNotFound:
      #   Unable to find visible field "product_name" that is not disabled
      #   ./spec/features/admin/bulk_product_update_spec.rb:180:in `block (2 levels) in <top (required)>'

18)
  As an Administrator
  I want to be able to manage products in bulk
 as an enterprise manager allows me to create a product
     Failure/Error: stock_item.backorderable?

     ActionView::Template::Error:
       undefined method `backorderable?' for nil:NilClass
     # ./app/models/concerns/variant_stock.rb:88:in `on_demand'
     # ./app/models/concerns/variant_stock.rb:32:in `on_hand'
     # ./app/models/spree/product_decorator.rb:138:in `on_hand'
  ... bulk_product_update_spec:688

 34) 
    As an admin
    I want to set a supplier and distributor(s) for a product
 creating a product assigning important attributes
      Failure/Error: stock_items.first.backorderable?
      
      ActionView::Template::Error:
        undefined method `backorderable?' for nil:NilClass
      # ./app/models/concerns/variant_stock.rb:88:in `on_demand'
      # ./app/models/concerns/variant_stock.rb:32:in `on_hand'
      # ./app/models/spree/product_decorator.rb:138:in `on_hand'
      # ./app/views/spree/admin/products/new.js.erb:2:in `_7257b43a6e016831f9b0f141204d36c3'
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `call'
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `respond_with'
      # ./lib/open_food_network/rack_request_blocker.rb:37:in `call'
      # ------------------
      # --- Caused by: ---
      # Capybara::ElementNotFound:
      #   Unable to find visible select box "product_supplier_id" that is not disabled
      #   ./spec/features/admin/products_spec.rb:29:in `block (3 levels) in <top (required)>'

  35) 
    As an admin
    I want to set a supplier and distributor(s) for a product
 creating a product creating an on-demand product
      Failure/Error: stock_items.first.backorderable?
      
      ActionView::Template::Error:
        undefined method `backorderable?' for nil:NilClass
      # ./app/models/concerns/variant_stock.rb:88:in `on_demand'
      # ./app/models/concerns/variant_stock.rb:32:in `on_hand'
      # ./app/models/spree/product_decorator.rb:138:in `on_hand'
      # ./app/views/spree/admin/products/new.js.erb:2:in `_7257b43a6e016831f9b0f141204d36c3'
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `call'
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `respond_with'
      # ./lib/open_food_network/rack_request_blocker.rb:37:in `call'
      # ------------------
      # --- Caused by: ---
      # Capybara::ElementNotFound:
      #   Unable to find visible field "product_name" that is not disabled
      #   ./spec/features/admin/products_spec.rb:68:in `block (3 levels) in <top (required)>'

 39) 
    As an admin
    I want to set a supplier and distributor(s) for a product
 as an enterprise user products do not require a tax category creating a new product
      Failure/Error: stock_items.first.backorderable?
      
      ActionView::Template::Error:
        undefined method `backorderable?' for nil:NilClass
      # ./app/models/concerns/variant_stock.rb:88:in `on_demand'
      # ./app/models/concerns/variant_stock.rb:32:in `on_hand'
      # ./app/models/spree/product_decorator.rb:138:in `on_hand'
      # ./app/views/spree/admin/products/new.js.erb:2:in `_7257b43a6e016831f9b0f141204d36c3'
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `call'
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `respond_with'
      # ./lib/open_food_network/rack_request_blocker.rb:37:in `call'
      # ------------------
      # --- Caused by: ---
      # Capybara::ElementNotFound:
      #   Unable to find visible field "product_name" that is not disabled
      #   ./spec/features/admin/products_spec.rb:112:in `block (5 levels) in <top (required)>'

```

**Comment by daniellemoorhead** [comment]
Hey @luisramos0  now that all referenced PRs are merged can this be closed, or will further work be done on it and therefore it should be back to the In Dev column?

#toottoot

**Comment by luisramos0** [comment]
It's fixed!
