### ISSUE TITLE
[Spree Upgrade] Fix spree api products_controller spec (10 broken tests)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3034]
Fix broken specs in spec/controllers/spree/api/products_controller_spec.rb

```
29) Spree::Api::ProductsController as a normal user should deny me access to managed products
      Failure/Error: assert_unauthorized!
      
        expected: {"error"=>"You are not authorized to perform that action."}
             got: {"exception"=>"stubbed models are not allowed to access the database - Spree::User#save!()"} (using ==)
        Diff:
        @@ -1,2 +1,2 @@
        -"error" => "You are not authorized to perform that action.",
        +"exception" => "stubbed models are not allowed to access the database - Spree::User#save!()",
        
      # ./spec/controllers/spree/api/products_controller_spec.rb:27:in `block (3 levels) in <module:Spree>'

  30) Spree::Api::ProductsController as an administrator retrieves a list of managed products
      Failure/Error: keys = json_response.first.keys.map{ |key| key.to_sym }
      
      NoMethodError:
        undefined method `keys' for #<Array:0x007fd3cf1de750>
      # ./spec/controllers/spree/api/products_controller_spec.rb:67:in `block (3 levels) in <module:Spree>'

  31) Spree::Api::ProductsController as an administrator retrieves a list of products with appropriate attributes
      Failure/Error: keys = json_response.first.keys.map{ |key| key.to_sym }
      
      NoMethodError:
        undefined method `keys' for #<Array:0x007fd3ce716750>
      # ./spec/controllers/spree/api/products_controller_spec.rb:73:in `block (3 levels) in <module:Spree>'

  32) Spree::Api::ProductsController as an administrator sorts products in ascending id order
      Failure/Error: ids = json_response.map{ |product| product['id'] }
      
      TypeError:
        no implicit conversion of String into Integer
      # ./spec/controllers/spree/api/products_controller_spec.rb:83:in `[]'
      # ./spec/controllers/spree/api/products_controller_spec.rb:83:in `block (4 levels) in <module:Spree>'
      # ./spec/controllers/spree/api/products_controller_spec.rb:83:in `each'
      # ./spec/controllers/spree/api/products_controller_spec.rb:83:in `map'
      # ./spec/controllers/spree/api/products_controller_spec.rb:83:in `block (3 levels) in <module:Spree>'

  33) Spree::Api::ProductsController as an administrator formats available_on to 'yyyy-mm-dd hh:mm'
      Failure/Error: json_response.map{ |product| product['available_on'] }.all?{ |a| a.match("^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$") }.should == true
      
      TypeError:
        no implicit conversion of String into Integer
      # ./spec/controllers/spree/api/products_controller_spec.rb:90:in `[]'
      # ./spec/controllers/spree/api/products_controller_spec.rb:90:in `block (4 levels) in <module:Spree>'
      # ./spec/controllers/spree/api/products_controller_spec.rb:90:in `each'
      # ./spec/controllers/spree/api/products_controller_spec.rb:90:in `map'
      # ./spec/controllers/spree/api/products_controller_spec.rb:90:in `block (3 levels) in <module:Spree>'

  34) Spree::Api::ProductsController as an administrator returns permalink as permalink_live
      Failure/Error: json_response.detect{ |product| product['id'] == product1.id }['permalink_live'].should == product1.permalink
      
      TypeError:
        no implicit conversion of String into Integer
      # ./spec/controllers/spree/api/products_controller_spec.rb:95:in `[]'
      # ./spec/controllers/spree/api/products_controller_spec.rb:95:in `block (4 levels) in <module:Spree>'
      # ./spec/controllers/spree/api/products_controller_spec.rb:95:in `each'
      # ./spec/controllers/spree/api/products_controller_spec.rb:95:in `detect'
      # ./spec/controllers/spree/api/products_controller_spec.rb:95:in `block (3 levels) in <module:Spree>'

  35) Spree::Api::ProductsController as an administrator soft deletes a product
      Failure/Error: response.status.should == 204
      
        expected: 204
             got: 422 (using ==)
      # ./spec/controllers/spree/api/products_controller_spec.rb:112:in `block (3 levels) in <module:Spree>'

  36) Spree::Api::ProductsController#clone as a normal user denies access
      Failure/Error: assert_unauthorized!
      
        expected: {"error"=>"You are not authorized to perform that action."}
             got: {"exception"=>"stubbed models are not allowed to access the database - Spree::User#save!()"} (using ==)
        Diff:
        @@ -1,2 +1,2 @@
        -"error" => "You are not authorized to perform that action.",
        +"exception" => "stubbed models are not allowed to access the database - Spree::User#save!()",
        
      # ./spec/controllers/spree/api/products_controller_spec.rb:127:in `block (4 levels) in <module:Spree>'

  37) Spree::Api::ProductsController#clone as an administrator responds with a successful response
      Failure/Error: expect(response.status).to eq(201)
      
        expected: 201
             got: 422
      
        (compared using ==)
      # ./spec/controllers/spree/api/products_controller_spec.rb:158:in `block (4 levels) in <module:Spree>'

  38) Spree::Api::ProductsController#clone as an administrator clones the product
      Failure/Error: expect(json_response['name']).to eq("COPY OF #{product1.name}")
      
        expected: "COPY OF Product #447 - 856"
             got: nil
      
        (compared using ==)
      # ./spec/controllers/spree/api/products_controller_spec.rb:163:in `block (4 levels) in <module:Spree>'

```

**Comment by luisramos0** [comment]
Thanks @sigmundpetersen

**Comment by sigmundpetersen** [comment]
Yeah there is something not working right with Zenhub, it should close the connected issue automatically when merging the PR.

**Comment by sigmundpetersen** [comment]
OK thanks for the update, didn't know that! Is that intentional or could we configure these issues to be closed as well? Or is it a limitation in Zenhub?

**Comment by luisramos0** [comment]
I dont know :-)
Maybe it's possible to fix this in zenhub.

**Comment by sigmundpetersen** [comment]
I could check it out but I don't have the rights 🙂 @sauloperez @daniellemoorhead what is needed to configure Zenhub? Admin rights for the GH org?

**Comment by sauloperez** [comment]
@daniellemoorhead is the ZenHub master, I have no idea how it works.
