### ISSUE TITLE
[Spree Upgrade][FrontOffice] Fix Insufficient stock specs in shopping/cart_spec and shopping/shopping_spec (3 broken test)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3077]
Fix these specs in the spree build:
```
  12) full-page cart viewing the cart updating quantities with insufficient stock available prevents me from entering an invalid value
      Failure/Error:
        accept_alert 'Insufficient stock available, only 2 remaining' do
          fill_in "order_line_items_attributes_0_quantity", with: '4'
        end
      
      Capybara::ModalNotFound:
        Unable to find modal dialog with Insufficient stock available, only 2 remaining
      # ./spec/features/consumer/shopping/cart_spec.rb:111:in `block (4 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # Capybara::ModalNotFound:
      #   Capybara::ModalNotFound
      #   ./spec/features/consumer/shopping/cart_spec.rb:111:in `block (4 levels) in <top (required)>'

  13) full-page cart viewing the cart updating quantities with insufficient stock available shows the quantities saved, not those submitted
      Failure/Error: expect(page).to have_content "Insufficient stock available, only 2 remaining"
        expected to find text "Insufficient stock available, only 2 remaining" in "SHOPS MAP PRODUCERS GROUPS ABOUT English Castellano English Login Shopping @ ENTERPRISE 152 4 items Enterprise 152 Herndon Your shopping cart Order ready for time ABOUT ENTERPRISE 152 PRODUCERS CONTACT GROUPS Item Price Qty Total Product #62 - 6033 (1g) $110.00 $440.00 Update Empty cart Produce subtotal $440.00 Total $440.00 (includes tax) $40.00 Continue shopping Checkout Interested in getting on the Open Food Network? Register here OFN Global Home | News | About | Contact OFN Sites Developer | Community | User Guide Secure and trusted. Open Food Network uses SSL encryption (2048 bit RSA) everywhere to keep your shopping and payment information private. Our servers do not store your credit card details and payments are processed by PCI-compliant services. Keep in touch Email us Newsletter sign-up News Calendar Navigate Shops Map Producers Groups About Join us Create a listing, shop or group directory on the Open Food Network. Tell me more! Read our Terms and conditions | Find us on GitHub Open Food Network is a free and open source software platform. Our content is licensed with CC BY-SA 3.0 and our code with AGPL 3. We take good care of your data. See our cookies policy"
      # ./spec/features/consumer/shopping/cart_spec.rb:127:in `block (4 levels) in <top (required)>'

4) As a consumer I want to shop with a distributor Viewing a distributor adding and removing products from cart alerts us when we enter a quantity greater than the stock available
     Failure/Error:
       accept_alert 'Insufficient stock available, only 5 remaining' do
         fill_in "variants[#{variant.id}]", with: '10'
       end
     
     Capybara::ModalNotFound:
       Unable to find modal dialog with Insufficient stock available, only 5 remaining
     # ./spec/features/consumer/shopping/shopping_spec.rb:307:in `block (4 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Capybara::ModalNotFound:
     #   Capybara::ModalNotFound
     #   ./spec/features/consumer/shopping/shopping_spec.rb:307:in `block (4 levels) in <top (required)>'
```

Could be related to #3036

**Comment by daniellemoorhead** [comment]
Hey @luisramos0  now that #3207 is merged can this be closed, or will further work be done on it and therefore it should be back to the In Dev column?

#toottoot

**Comment by luisramos0** [comment]
Fixed :-)
