### ISSUE TITLE
[Spree Upgrade][FrontOffice] Fix shopping/orders_spec - guest order (1 broken test)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3078]
Fix this spec:

```
1) Order Management viewing a completed order when checking out as an anonymous guest allows the user to see the details
     Failure/Error:
       create(:order_with_credit_payment,
         customer: customer,
         user: user,
         distributor: distributor,
         order_cycle: order_cycle
       )

     NoMethodError:
       undefined method `email' for nil:NilClass
     # /Users/luisramos/.rvm/gems/ruby-2.1.5@openfoodnetwork/bundler/gems/spree-f55722b38db7/core/lib/spree/testing_support/factories/order_factory.rb:6:in `block (3 levels) in <top (required)>'
….   
     # ./spec/features/consumer/shopping/orders_spec.rb:17:in `block (3 levels) in <top (required)>'

```

The new default spree order factory fetches user.email from order.email
https://github.com/openfoodfoundation/spree/blob/master/core/lib/spree/testing_support/factories/order_factory.rb#L6
This causes the error because the spec is using a nil user.

It will be related to this method
https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/controllers/spree/orders_controller_decorator.rb#L133
@kristinalim you may have a special insight into this one.
I believe the code is correct, we just need to adapt the test and/or the factories used.

**Comment by luisramos0** [comment]
@sauloperez if you are looking for another spree upgrade issue, I think you will handle this one really quickly
