### ISSUE TITLE
[Spree Upgrade][BackOffice] Fix issue in Product edit variants - related to deface override in admin/variants_spec and admin/bulk_product_update (3 broken tests)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3091]
There is something wrong in app/overrides/spree/admin/variants/_form/hide_unit_option_types.html.haml.deface
My best hypothesis is that this override is no longer compatible with the product/variants edit page flow. Needs further investigation.

```
 33) 
    As an admin
    I want to manage product variants
 creating a new variant
      Failure/Error: super
      
      ActionView::Template::Error:
        undefined local variable or method `option' for #<#<Class:0x007fe319974678>:0x007fe32a1df2d0>
      # ./app/helpers/application_helper.rb:20:in `method_missing'
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `call'
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `respond_with'
      # ./lib/open_food_network/rack_request_blocker.rb:37:in `call'
      # ./spec/features/admin/variants_spec.rb:17:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # NameError:
      #   undefined local variable or method `option' for #<#<Class:0x007fe319974678>:0x007fe32a1df2d0>
      #   ./app/helpers/application_helper.rb:20:in `method_missing'

  34) 
    As an admin
    I want to manage product variants
 editing unit value and description for a variant
      Failure/Error: super
      
      ActionView::Template::Error:
        undefined local variable or method `option' for #<#<Class:0x007fe319974678>:0x007fe31b0840e8>
      # ./app/helpers/application_helper.rb:20:in `method_missing'
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `call'
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `respond_with'
      # ./lib/open_food_network/rack_request_blocker.rb:37:in `call'
      # ------------------
      # --- Caused by: ---
      # Capybara::ExpectationNotMet:
      #   expected to find visible field "unit_value_human" that is not disabled with value "1" but there were no matches
      #   ./spec/features/admin/variants_spec.rb:46:in `block (2 levels) in <top (required)>'
```

**Comment by luisramos0** [comment]
This also happens in admin/bulk_product_update_spec:

```
 20) 
  As an Administrator
  I want to be able to manage products in bulk
 using action buttons using edit buttons shows an edit button for variants, which takes the user to the standard edit page for that variant
      Failure/Error: super
      
      ActionView::Template::Error:
        undefined local variable or method `option' for #<#<Class:0x007f7e293ff580>:0x007f7e2a31ef98>
      # ./app/helpers/application_helper.rb:20:in `method_missing'
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `call'
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `respond_with'
      # ./lib/open_food_network/rack_request_blocker.rb:37:in `call'
      # ------------------
      # --- Caused by: ---
      # Capybara::CapybaraError:
      #   Your application server raised an error - It has been raised in your test code because Capybara.raise_server_errors == true
      #   ./spec/spec_helper.rb:92:in `block (2 levels) in <top (required)>'
```

**Comment by luisramos0** [comment]
Maybe one more candidate for de-deface, or maybe just needs a de-deface specialist to sort it out @Matt-Yorkley @HugsDaniel
