### ISSUE TITLE
[Spree Upgrade] Changing distributor and OC in the Edit Orders page (3 broken specs)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3103]
Expected behaviour: if an order is not complete, the order edit page should let manager change the distributor and the OC.

Related broken specs:
```
  3) 
    As an administrator
    I want to manage orders
 displays error when incorrect distribution for products is chosen
     Failure/Error: targetted_select2(value, options)
     
     Capybara::ElementNotFound:
       Unable to find visible css "#s2id_order_distributor_id"
     # ./spec/support/request/web_helper.rb:163:in `select2_select'
     # ./spec/features/admin/orders_spec.rb:116:in `block (2 levels) in <top (required)>'

  4) 
    As an administrator
    I want to manage orders
 can't change distributor or order cycle once order has been finalized
     Failure/Error: expect(page).to have_selector 'p', text: "Distributor: #{@order.distributor.name}"
       expected to find visible css "p" with text "Distributor: Enterprise 25" but there were no matches
     # ./spec/features/admin/orders_spec.rb:144:in `block (2 levels) in <top (required)>'

```

**Comment by luisramos0** [comment]
Looks like there's only one error now:
```
 2) 
    As an administrator
    I want to manage orders
 displays error when incorrect distribution for products is chosen
     Failure/Error: targetted_select2(value, options)
     
     Capybara::ElementNotFound:
       Unable to find visible css "#s2id_order_distributor_id"
     # ./spec/support/request/web_helper.rb:163:in `select2_select'
     # ./spec/features/admin/orders_spec.rb:116:in `block (2 levels) in <top (required)>'
```

**Comment by luisramos0** [comment]
After PR 3286, these are the 3 errors related to OC and distributor:

```
  1) 
    As an administrator
    I want to manage orders
 creating an order with distributor and order cycle
     Failure/Error: expect(page).to have_selector 'h1', text: 'Customer Details'
       expected to find visible css "h1" with text "Customer Details" but there were no matches. Also found "Order # R268713701", which matched the selector but not all filters.
     # ./spec/features/admin/orders_spec.rb:81:in `block (2 levels) in <top (required)>'

  2) 
    As an administrator
    I want to manage orders
 displays error when incorrect distribution for products is chosen
     Failure/Error: targetted_select2(value, options)
     
     Capybara::ElementNotFound:
       Unable to find visible css "#s2id_order_distributor_id"
     # ./spec/support/request/web_helper.rb:163:in `select2_select'
     # ./spec/features/admin/orders_spec.rb:116:in `block (2 levels) in <top (required)>'

 5) 
    As an administrator
    I want to manage orders
 as an enterprise manager creating an order with distributor and order cycle
     Failure/Error: expect(page).to have_selector 'td', text: product.name
       expected to find visible css "td" with text "Product #29 - 516" but there were no matches. Also found "Subtotal :", "$0.00", "", "TOTAL ORDER :", "$0.00", "", which matched the selector but not all filters.
     # ./spec/features/admin/orders_spec.rb:327:in `block (3 levels) in <top (required)>'
```

**Comment by luisramos0** [comment]
after #3194, only the spec that tests this specific behaviour is broken: spec/features/admin/orders_spec.rb:98
When the order is not complete, we must be able to edit distributor and OC.
