### ISSUE TITLE
[Spree Upgrade][BackOffice] Fix admin/bulk_product_update spec (1 broken test)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3114]
admin/bulk_product_update has a few errors in #2804, #3018 and #3091.
Apart from these, there is this error in bulk_product_update related to creating a variant directly on the bulk product edit page:

```ruby
  16) 
  As an Administrator
  I want to be able to manage products in bulk
 creating new variants
      Failure/Error: raise message if stock_items.empty?
      
      RuntimeError:
        You need to save the variant to create a stock item before you can set stock levels.
      # ./app/models/concerns/variant_stock.rb:125:in `raise_error_if_no_stock_item_available'
      # ./app/models/concerns/variant_stock.rb:77:in `count_on_hand='
      # ./app/models/concerns/variant_stock.rb:58:in `on_hand='
      # ./app/models/spree/product_set.rb:83:in `update_variant'
      # ./app/models/spree/product_set.rb:71:in `block in update_variants_attributes'
      # ./app/models/spree/product_set.rb:70:in `each'
      # ./app/models/spree/product_set.rb:70:in `update_variants_attributes'
      # ./app/models/spree/product_set.rb:61:in `update_product_variants'
      # ./app/models/spree/product_set.rb:32:in `update_attributes'
      # ./app/models/spree/product_set.rb:95:in `block in save'
      # ./app/models/spree/product_set.rb:94:in `each_value'
      # ./app/models/spree/product_set.rb:94:in `each'
      # ./app/models/spree/product_set.rb:94:in `all?'
      # ./app/models/spree/product_set.rb:94:in `save'
      # ./app/controllers/spree/admin/products_controller_decorator.rb:46:in `bulk_update'
      # ./lib/open_food_network/rack_request_blocker.rb:37:in `call'
      # ------------------
      # --- Caused by: ---
      # Capybara::ExpectationNotMet:
      #   expected to find text "Changes saved." in "Saving failed.Save failed due to invalid data:500"
      #   ./spec/features/admin/bulk_product_update_spec.rb:225:in `block (2 levels) in <top (required)>'
```

**Comment by luisramos0** [comment]
The current error is this:

```
 1)
  As an Administrator
  I want to be able to manage products in bulk
 creating new variants
     Failure/Error: expect(updated_variant.on_hand).to eq 10

       expected: 10
            got: Infinity

       (compared using ==)
     # ./spec/features/admin/bulk_product_update_spec.rb:238:in `block (2 levels) in <top (required)>'
```

The process of adding, editing and deleting variants in the bulk product update page is still not working. I believe that's the reason why this spec is failing. Could be related to some problem in handling on_hand and on_demand correctly.

**Comment by luisramos0** [comment]
3246 was reverted, this spec is still failing. reopening.

**Comment by luisramos0** [comment]
thanks @sigmundpetersen
