### ISSUE TITLE
[Spree Upgrade][BackOffice] Fix features/admin/products_spec (3 broken tests)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3122]
Apart from #3018, fix features/admin/products_spec

```ruby
  36) 
    As an admin
    I want to set a supplier and distributor(s) for a product
 as an enterprise user editing a product
      Failure/Error: select 'Permitted Supplier', from: 'product_supplier_id'
      
      Capybara::ElementNotFound:
        Unable to find visible select box "product_supplier_id" that is not disabled
      # ./spec/features/admin/products_spec.rb:141:in `block (3 levels) in <top (required)>'

  37) 
    As an admin
    I want to set a supplier and distributor(s) for a product
 as an enterprise user deleting product properties
      Failure/Error: page.all('a.remove_fields').first.click
      
      NoMethodError:
        undefined method `click' for nil:NilClass
      # ./spec/features/admin/products_spec.rb:211:in `block (3 levels) in <top (required)>'

  38) 
    As an admin
    I want to set a supplier and distributor(s) for a product
 as an enterprise user deleting product images
      Failure/Error: defined_response.call
      
      NoMethodError:
        undefined method `admin_images_url' for #<ActionDispatch::Routing::RoutesProxy:0x007fb8577566f8>
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `call'
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `respond_with'
      # ./lib/open_food_network/rack_request_blocker.rb:37:in `call'
      # ------------------
      # --- Caused by: ---
      # Capybara::ExpectationNotMet:
      #   expected not to find visible css "table[data-hook='images_table'] td img", found 1 match: ""
      #   ./spec/features/admin/products_spec.rb:233:in `block (3 levels) in <top (required)>'
```

**Comment by luisramos0** [comment]
#3197 fixed the first test, the two remaining ones are fixed in #3203

**Comment by daniellemoorhead** [comment]
Shall we move this issue back to In Dev column then @luisramos0, because you're likely to have more PRs for it? I don't think there's anything to review on it right now.

#toottoot

**Comment by luisramos0** [comment]
It's fixed!
