### ISSUE TITLE
[Spree Upgrade] Fix reference to backorderable_default from admin/products/new.html.haml

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#3253]
## Description

Our VariantStock module relies on the `Spree::StockLocation.first.backorderable_default` but in `2-0-stable` we don't create the default stock location yet.

This obviously causes a 500 error as follows:

```
...
Completed 500 Internal Server Error in 929.8ms (ActiveRecord: 34.8ms)
** [Bugsnag] No API key configured, couldn't notify

ActionView::Template::Error (undefined method `backorderable_default' for nil:NilClass):
    1: <%# This chunk is just a copy of Spree's backend/app/views/spree/admin/products/new.js.erb %>
    2: $("#new_product").html('<%= escape_javascript(render :template => "spree/admin/products/new", :formats => [:html], :handlers => [:haml]) %>');
    3: handle_date_picker_fields();
    4: <% unless Rails.env.test? %>
    5:   $('.select2').select2();
  app/models/concerns/variant_stock.rb:91:in `on_demand'
  app/models/concerns/variant_stock.rb:32:in `on_hand'
  app/models/concerns/product_stock.rb:19:in `on_hand'
  app/views/spree/admin/products/new.html.haml:57:in `block (2 levels) in _6397cc2bb50734c9d7283660ebd313d6'
  app/views/spree/admin/products/new.html.haml:53:in `block in _6397cc2bb50734c9d7283660ebd313d6'
  app/views/spree/admin/products/new.html.haml:3:in `_6397cc2bb50734c9d7283660ebd313d6'
  app/views/spree/admin/products/new.js.erb:2:in `_80cf50a20567230ea7daadc245fd7326'
  lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `call'
  lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `respond_with'
...
```

## Expected Behavior
`products/new` page should render successfully without errors and allow users to specify a value for the stock level.

## Actual Behavior
The page fails to render raising the error showed above.

## Steps to Reproduce
1. Go to `/admin/products`
2. Click on `+ NEW PRODUCT`

## Possible Fix

We need to add a data migration that creates that default StockLocation. Once executed this should be fixed.

**Comment by sigmundpetersen** [comment]
Close issue?
