### ISSUE TITLE
[Spree 2.1] DatabaseCleaner issue (~1100 specs)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3705]
The [2-1-stable branch]([ofn/2-1-stable](https://github.com/openfoodfoundation/openfoodnetwork/compare/2-0-stable...2-1-stable?expand=1)) is based on spree 2.1.

The build ([see here](https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/2-1-stable/builds/17)) has some problem with database cleaner or something related to the data in the DB while the tests are running or between tests....

I tried commenting out databasecleaner in spec_helper and the errors become different.

Looks like spec/features/admin/orders_spec.rb is a good place to replicate this locally.

The error:
```
As an administrator
    I want to manage orders
 can add a product to an existing order
     Failure/Error: @product = create(:simple_product)
     
     ActiveRecord::InvalidForeignKey:
       PG::ForeignKeyViolation: ERROR:  insert or update on table "spree_products" violates foreign key constraint "spree_products_supplier_id_fk"
       DETAIL:  **Key (supplier_id)=(1) is not present in table "enterprises".**
       : INSERT INTO "spree_products" ("available_on", "created_at", "description", "name", "permalink", "primary_taxon_id", "shipping_category_id", "supplier_id", "updated_at", "variant_unit", "variant_unit_name", "variant_unit_scale") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING "id"
     # ./spec/features/admin/orders_spec.rb:14:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # PG::ForeignKeyViolation:
     #   ERROR:  insert or update on table "spree_products" violates foreign key constraint "spree_products_supplier_id_fk"
     #   DETAIL:  Key (supplier_id)=(1) is not present in table "enterprises".
     #   ./spec/features/admin/orders_spec.rb:14:in `block (2 levels) in <top (required)>'
```

**Comment by luisramos0** [comment]
I have explored a bit further with spec/features/admin/orders_spec.rb

Locally, every single spec run individually passes. I only need to run two specs in a row to get the error.
The problem happens when the background/before block executes for the second spec, for some reason, it looks like it is reusing data from the previous run.
The error I saw is that create enterprise fails because owner is invalid (there's an id but no object for that id in the db), and owner is invalid because the enterprise factory instead of creating a new user, it looks like it re-uses the user from the previous run which has been deleted by database cleaner.

the factory:
https://github.com/openfoodfoundation/openfoodnetwork/blob/c5720bede5d7f199ede875181672d1c89e50489b/spec/factories.rb#L214-215

**Comment by luisramos0** [comment]
Investigated this in the gathering with @mkllnk to isolate the issue and share it with other devs.
@sauloperez was incredible fast at pointing us to this :clap:

![Screenshot 2019-05-25 at 22 13 26](https://user-images.githubusercontent.com/1640378/58374692-586ed500-7f3a-11e9-974b-506d75841038.png)
