### ISSUE TITLE
Error 500 when accessing order cycle management reports on French prod

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3834]
## Description
Some users in France have a direct error 500 when accessing admin/reports/order_cycle_management or the two sub reports directly.

It is not happening with all French users...

## Steps to Reproduce
1. Log in as one of the users (I can give you access in PM)
2. Go to admin/reports/order_cycle_management
3. Have a direct error 500

## Animated Gif/Screenshot
https://github.com/openfoodfoundation/ofn-install/pull/408

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v1.31
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): Desktop Windows 10

**Comment by luisramos0** [comment]
these are the logs for this problem:
```
Completed 500 Internal Server Error in 1230.6ms (ActiveRecord: 233.4ms)
Notifying https://notify.bugsnag.com of NoMethodError

ActionView::Template::Error (undefined method `payment_method' for nil:NilClass):
    12:
    13:   .row
    14:     .alpha.two.columns= label_tag nil, t(:report_payment)
    15:     .omega.fourteen.columns= select_tag(:payment_method_in, options_for_select(report_payment_method_options(@report.orders), params[:payment_method_in]), {class: "select2 fullwidth", multiple: true})
    16:
    17:   .row
    18:     .alpha.two.columns= label_tag nil, "#{t(:shipping_methods)}: "
  app/helpers/spree/reports_helper.rb:15:in `block in report_payment_method_options'
  app/helpers/spree/reports_helper.rb:14:in `report_payment_method_options'
  app/views/spree/admin/reports/order_cycle_management.html.haml:15:in `block in _08188c449f48fb3fb3f2401b06f0b40d'
  app/views/spree/admin/reports/order_cycle_management.html.haml:1:in `_08188c449f48fb3fb3f2401b06f0b40d'

```

**Comment by luisramos0** [comment]
line 15:
https://github.com/openfoodfoundation/openfoodnetwork/blob/6d62f4c4b4b7e47db34a0bd8d836dcd4512f65b8/app/helpers/spree/reports_helper.rb#L13-L18

there are lots of orders in the system without payments, so I dont really understand why/how this code should work...

**Comment by RachL** [comment]
@luisramos0 when you say:

> there are lots of orders in the system without payments, so I dont really understand why/how this code should work...

You mean a lot of orders which stayed at the cart stage? Do you need the name of the hub?

**Comment by luisramos0** [comment]
ah, awesome tip! completed orders without payment!
there is only one from yesterday morning... LOVE BIO...  R075336663
it's payment_state is failed

**Comment by RachL** [comment]
@luisramos0 thx !! I will see with the bug manager to add a payment and see if it works afterwards and how the payment failed.
Is there a way to add a cleaner error message in this case? (I can open a new issue for this)

**Comment by luisramos0** [comment]
ok, lets confirm that's the issue and lets try to see what happened with the payment.

if this is the problem we can make sure there's always a payment complete orders or we can adapt the report

**Comment by RachL** [comment]
Yes will let you know asap!

**Comment by RachL** [comment]
@luisramos0 here is the story :
"Le jardin de deux main" is a producer that sells directly AND through the hub "Love Bio Bayeux"

the person behind the order wanted to buy directly at the producer but ended up doing an order on the hub. She called the hub saying she don't know want happened because the order went through without the products. - _I suspect she tried to cancel the order herself (and didn't do it properly...?) when she saw that she did a mistake, but that is just a guess_
The hub then created another order for her directly on the producer shop, but forgot to cancel the order with payment failure (actually he didn't not see it directly).
Anyway now he cancelled the order and his report is back in business :muscle: 

I think the best is to close this issue and open a new one regarding the report? Not sure if the solution of a payment complete can work most of our users don't capture their cash payments...

**Comment by luisramos0** [comment]
nice investigation!!!
I think we need this or other issue for this.

was it the failed payment or was it order cancelation?

**Comment by RachL** [comment]
@luisramos0 I'm not cleared on what cause the failed payment. Did she tried to remove all of her products or something or to cancel while the payment was creating? This is unclear for me, and I guess the person who did the order is unclear as well on what happened. 

The order cancelation is the solution we did to avoid the report having an error.

**Comment by luisramos0** [comment]
yeah, I see.

**Comment by lin-d-hop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Stroudco: packing reports](https://trello.com/c/jPd9HQUH/449-stroudco-packing-reports)

**Comment by lbwright22** [comment]
Hi @luisramos0 Tamar Valley and StroudCo in the Uk are having the same difficult with their Delivery Report.
Are you able to look at the DB to identify the failed payments so we can put in place a work around for the time being for these enterprises?  I can't distinguish between failed payments and those who have opted for cash or pay on collection etc.
Many thanks

**Comment by luisramos0** [comment]
Hello! There are no recent completed orders without payments in uk live according to my query:
`select e.* from spree_orders o left join enterprises e on (e.id = o.distributor_id) where state = 'complete' and not exists (select 1 from spree_payments where order_id = o.id);`

I dont see a reason to think your problem is related to this issue. We should probably track your problem as a separate issue and go from there.

**Comment by lin-d-hop** [comment]
I just tried to run the report myself then looked at the logs and got the same error as above. The error also impacts a user that has management permissions with an effected enterprise. It would be great to tidy this up in any case.

I ran the following query to get the order numbers:
`select e.name, o.number from spree_orders o left join enterprises e on (e.id = o.distributor_id) where state = 'complete' and not exists (select 1 from spree_payments where order_id = o.id);`
(thanks Luis)

@lbwright22 I've posted the results from that query in your Slack. Would you take a look at each of the orders and see if you can remedy as Rachel did above? Then we can try again.

Thanks for all the detective work!

**Comment by luisramos0** [comment]
wait, those orders are all old orders, I think the report will only fail with "completed orders without payment" inside the date range selected in the report.

also, what error do you see in the reports? I cant find this one on uk live logs:
ActionView::Template::Error (undefined method `payment_method' for nil:NilClass):

**Comment by lin-d-hop** [comment]
CLosing. We can reopen if still an issue on new reports code
