### ISSUE TITLE
Delete product breaks subscriptions list page

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3948]
## Description
Deleting a product used in a subscription will break the subscriptions list page.

## Expected Behavior
The subscription list page loads existing subscriptions.

## Actual Behaviour
The subscriptions list page shows spinning wheel and "Loading subscription" with a server side error seen in the logs:

```
Completed 500 Internal Server Error in 93.3ms (ActiveRecord: 24.9ms)
Not notifying due to an invalid api_key

NoMethodError (undefined method `product' for nil:NilClass):
  app/serializers/api/admin/subscription_line_item_serializer.rb:8:in `description'
  app/controllers/spree/admin/base_controller_decorator.rb:79:in `render_as_json'
  app/controllers/admin/subscriptions_controller.rb:25:in `block (2 levels) in index'
  app/controllers/admin/subscriptions_controller.rb:14:in `index'


  Rendered /Users/luisramos/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/templates/rescues/_trace.erb (2.3ms)
  Rendered /Users/luisramos/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (2.4ms)
  Rendered /Users/luisramos/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (78.2ms)
  Rendered /Users/luisramos/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/templates/rescues/layout.erb (82.3ms)

```

## Steps to Reproduce
1. Create a subscription and add a product
2. Delete the product
3. Go to the subscription list page
4. It doesn't load correctly

## Context
Testing subs.

## Severity

* Version used: v2.1.0
* Browser name and version: chrome
* Operating System and version (desktop or mobile): maxos
* OFN Platform instance where you discovered the bug, and which version of the software they are using: local instance with master

## Possible Fix

The open question is: when a product is deleted, the product should be removed from all open subscriptions?

Make subs code handle soft deleted products...

**Comment by luisramos0** [comment]
closing this one, duplicated in #4062
