### ISSUE TITLE
AddAddressInstancesToExistingEnterpriseGroups fails if migrating on a empty database

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#438]
I'm attempting this on staging and get:

```
==  AddAddressInstancesToExistingEnterpriseGroups: migrating ==================

stderr:
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `states' for nil:NilClass/home/ubuntu/apps/openfoodnetwork/current/db/migrate/20150115050936_add_address_instances_to_existing_enterprise_groups.rb:4:in `change'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:407:in `block (2 levels) in migrate'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:407:in `block in migrate'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:389:in `migrate'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:528:in `migrate'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:775:in `call'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:775:in `block in ddl_transaction'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:775:in `ddl_transaction'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:719:in `block in migrate'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:700:in `each'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:700:in `migrate'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:570:in `up'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:551:in `migrate'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/railties/databases.rake:193:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Any ideas?

**Comment by pmackay** [comment]
I think its because given the UK locale, this fails:

```
    country = Spree::Country.find_by_name(ENV['DEFAULT_COUNTRY'])
    state = country.states.first
```

**Comment by pmackay** [comment]
I've renamed this - is this migration assuming that there is a list of countries, which wouldnt be the case if running `db:migrate` on a clean db?

**Comment by mkllnk** [comment]
Thank you for bringing this forward. I didn't think of a clean database when I wrote that migration. If you don't have countries, you don't have addresses and therefore no groups. The whole migration can be skipped in that case.

Would you like to make a pull request?

**Comment by myriamboure** [comment]
@enricostano @sauloperez any connexion to the staging issues we are facing? Else is there any point to keep open as an issue? Or is it a feature candidate for an icebox item on "enable smooth staging deployments everywhere"? ;-)

**Comment by enricostano** [comment]
I think it's too old to say anything.

> on the staging server there are no countries

This is related to the seed data issue on staging, yep.

Let's close it, it's covered in "enable smooth staging deployments everywhere"
