### ISSUE TITLE
rake db:setup fails on 0.7.4

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#439]
While trying to update UK staging and rebuild database to ensure countries are present (need to work out why werent before, could be an ansible issue) ran `rake db:setup`:

```
ubuntu@staging:~/apps/openfoodnetwork/current$ bundle exec rake db:setup
openfoodnetwork already exists
openfoodnetwork already exists
-- create_table("adjustment_metadata", {:force=>true})
NOTICE:  CREATE TABLE will create implicit sequence "adjustment_metadata_id_seq" for serial column "adjustment_metadata.id"
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "adjustment_metadata_pkey" for table "adjustment_metadata"
   -> 0.0606s
-- add_index("adjustment_metadata", ["adjustment_id"], {:name=>"index_adjustment_metadata_on_adjustment_id"})
   -> 0.0065s
-- add_index("adjustment_metadata", ["enterprise_id"], {:name=>"index_adjustment_metadata_on_enterprise_id"})
   -> 0.0059s
-- create_table("carts", {:force=>true})
rake aborted!
ActiveRecord::StatementInvalid: PG::Error: ERROR:  cannot drop table carts because other objects depend on it
DETAIL:  constraint spree_orders_cart_id_fk on table spree_orders depends on table carts
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
: DROP TABLE "carts"
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `async_exec'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `block in execute'
```

**Comment by pmackay** [comment]
I also then tried `rake db:drop db:create db:migrate`:

```
==  AddPermalinkToEnterprises: migrating ======================================
-- add_column(:enterprises, :permalink, :string)
   -> 0.0007s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `find_by_permalink' for #<Class:0x00000008c19f00>/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/dynamic_matchers.rb:27:in `method_missing'
/home/ubuntu/apps/openfoodnetwork/current/db/migrate/20141219034321_add_permalink_to_enterprises.rb:9:in `block in up'
/home/ubuntu/apps/openfoodnetwork/current/db/migrate/20141219034321_add_permalink_to_enterprises.rb:5:in `each'
/home/ubuntu/apps/openfoodnetwork/current/db/migrate/20141219034321_add_permalink_to_enterprises.rb:5:in `up'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:410:in `block in migrate'
/home/ubuntu/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
```

**Comment by pmackay** [comment]
Have added #440 related to AddPermalinkToEnterprises issue above.

**Comment by pmackay** [comment]
After discussion, not going to look further into 1st issue above. Not likely to encounter often.
