### ISSUE TITLE
open-food-network-beta-black.png isn't precompiled

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#457]
Getting this on UK staging:

```
ActionView::Template::Error (open-food-network-beta-black.png isn't precompiled):
    15:             %table{:bgcolor => "#f2f2f2"}
    16:               %tr
    17:                 %td
    18:                   %img{:src => "#{ asset_path 'open-food-network-beta-black.png' }", :width => "200", :height => "49"}/
    19:                 %td{:align => "right"}
    20:                   %h6.collapse
    21:                     Open Food Network
  app/views/layouts/mailer.html.haml:18:in `_b71a3f2449294a92aba1eb7a2d0a35f1'
  app/mailers/spree/user_mailer_decorator.rb:5:in `signup_confirmation'
  app/models/spree/user_decorator.rb:34:in `send_signup_confirmation'
  app/controllers/user_registrations_controller.rb:6:in `create'
```

Need to investigate.... It is preventing new users registering.

**Comment by pmackay** [comment]
Think this was just that last staging deployment didnt complete via using ofn_deployment.
