### ISSUE TITLE
[Spree 2.1] Fix problem with shipment.shipping_method in subscriptions (90 specs)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4820]
## Description
There are 90 broken specs all related to subs with the following error on shipment validation:
```
 60) OrderSyncer changing the billing address when a ship address is required when the bill_address on the order doesn't match that on the subscription does not update bill_address or ship_address on the order
      Failure/Error: payment_method.create_adjustment(adjustment_label, order, self, true)
      
      NoMethodError:
        undefined method `create_adjustment' for nil:NilClass
      # ./app/models/spree/payment_decorator.rb:26:in `ensure_correct_adjustment'
      # ./app/services/order_factory.rb:82:in `create_payment'
      # ./app/services/order_factory.rb:20:in `create'
      # ./app/models/proxy_order.rb:55:in `initialise_order!'
      # ./spec/services/order_syncer_spec.rb:146:in `block (3 levels) in <top (required)>'
```

## Possible Fix
The logic implemented to define the ship_method on the subs orders must be broken with spree 2.1.

**Comment by luisramos0** [comment]
this is fixed by 4827 (it was a problem with strong params)
