### ISSUE TITLE
[Spree 2.1] Admin login in tests

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#4842]
A bunch of feature specs for reports are broken here. The root cause is actually that `login_to_admin_as user` fails before the tests start, the login is getting an authorization failure. This could also be the cause of other broken feature specs. It looks like logging in as a superadmin user works though (in this example it's an enterprise user)...

Examples:
```
44) 
    As an administrator
    I want numbers, all the numbers!
 Permissions for different reports As an enterprise user does not show super admin only report
      Failure/Error: click_link "Reports"
      
      Capybara::ElementNotFound:
        Unable to find visible link "Reports"
      # ./spec/features/admin/reports_spec.rb:19:in `block (4 levels) in <top (required)>'

  45) 
    As an administrator
    I want numbers, all the numbers!
 sales tax report reports
      Failure/Error: expect(page).to     have_select 'q_distributor_id_eq', with_options: [user1.enterprises.first.name]
      
      NoMethodError:
        undefined method `name' for nil:NilClass
      # ./spec/features/admin/reports_spec.rb:212:in `block (3 levels) in <top (required)>'
```

**Comment by Matt-Yorkley** [comment]
Ok, this is partly related to the issue fixed in #4821, there's just a few places where tests build enterprise users in an odd way that avoids the new fix... :see_no_evil:
