### ISSUE TITLE
[Spree 2.1] Fix models/order_spec and models/spree/tax_rate_spec - tax rates and tax_adjustments (5 broken specs)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4875]
I tried to fix this problem but I couldnt understand...
"cost of quality" - we pay the price of the complicated code...

order.tax_adjustment_totals + TaxRateFinder :see_no_evil: 
Some serious [primitive obsession](http://wiki.c2.com/?PrimitiveObsession) going on here
These order adjustment_totals methods that build the hashes should be creating objects instead and the code itself should be in a service...

We just need to fix the tests :face_with_head_bandage: :
```
3) Spree::Order getting a hash of all taxes returns a hash with all 3 taxes
     Failure/Error: expect(order.tax_adjustment_totals.size).to eq(4)
     
       expected: 4
            got: 2
     
       (compared using ==)
     # ./spec/models/spree/order_spec.rb:301:in `block (3 levels) in <top (required)>'

  4) Spree::Order getting a hash of all taxes contains tax on line_item
     Failure/Error: expect(order.tax_adjustment_totals[tax_rate10]).to eq(4.0)
     
       expected: 4.0
            got: nil
     
       (compared using ==)
     # ./spec/models/spree/order_spec.rb:305:in `block (3 levels) in <top (required)>'

  5) Spree::Order getting a hash of all taxes contains tax on enterprise_fee
     Failure/Error: expect(order.tax_adjustment_totals[tax_rate20]).to eq(8.0)
     
       expected: 8.0
            got: nil
     
       (compared using ==)
     # ./spec/models/spree/order_spec.rb:313:in `block (3 levels) in <top (required)>'
```

**Comment by Matt-Yorkley** [comment]
I think I noticed other specs failing due to adjustments not being calculated and final prices being slightly off...

**Comment by luisramos0** [comment]
this is probably related, adding 2 more specs to this issue:
```
 49) Spree::TaxRate selecting tax rates to apply to an order when the order's hub charges sales tax selects all tax rates
      Failure/Error: expect(TaxRate.match(order)).to eq([tax_rate])
      
        expected: [#<Spree::TaxRate id: 2, amount: #<BigDecimal:565276b35078,'0.1E3',9(36)>, zone_id: 2, tax_category_i...020-03-02 18:47:53", included_in_price: true, name: nil, show_rate_in_label: true, deleted_at: nil>]
             got: []
      
        (compared using ==)
      
        Diff:
        @@ -1,2 +1,2 @@
        -[#<Spree::TaxRate id: 2, amount: #<BigDecimal:565276b35078,'0.1E3',9(36)>, zone_id: 2, tax_category_id: 241, created_at: "2020-03-02 18:47:53", updated_at: "2020-03-02 18:47:53", included_in_price: true, name: nil, show_rate_in_label: true, deleted_at: nil>]
        +[]
        
      # ./spec/models/spree/tax_rate_spec.rb:12:in `block (4 levels) in <module:Spree>'

  50) Spree::TaxRate selecting tax rates to apply to an order when the order does not have a hub selects all tax rates
      Failure/Error: expect(TaxRate.match(order)).to eq([tax_rate])
      
        expected: [#<Spree::TaxRate id: 4, amount: #<BigDecimal:5652787d0138,'0.1E3',9(36)>, zone_id: 4, tax_category_i...020-03-02 18:47:53", included_in_price: true, name: nil, show_rate_in_label: true, deleted_at: nil>]
             got: []
      
        (compared using ==)
      
        Diff:
        @@ -1,2 +1,2 @@
        -[#<Spree::TaxRate id: 4, amount: #<BigDecimal:5652787d0138,'0.1E3',9(36)>, zone_id: 4, tax_category_id: 243, created_at: "2020-03-02 18:47:53", updated_at: "2020-03-02 18:47:53", included_in_price: true, name: nil, show_rate_in_label: true, deleted_at: nil>]
        +[]
        
      # ./spec/models/spree/tax_rate_spec.rb:28:in `block (4 levels) in <module:Spree>'
```
