### ISSUE TITLE
[Spree 2.1] Fix enterprise_fee_report route issue (5 specs)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4877]
For some reason the routes in the order_management engine are not being loaded.
This causes 5 specs to fail:

```
  36) Spree::Admin::Reports::EnterpriseFeeSummariesController#new renders the report form
      Failure/Error: get :new
      
      ActionController::UrlGenerationError:
        No route matches {:action=>"new", :controller=>"spree/admin/reports/enterprise_fee_summaries"}
      # ./spec/controllers/spree/admin/reports/enterprise_fee_summaries_controller_spec.rb:16:in `block (3 levels) in <top (required)>'

  37) Spree::Admin::Reports::EnterpriseFeeSummariesController#create when the parameters are valid sends the generated report in the correct format
      Failure/Error: post :create, report: { start_at: "2018-10-09 07:30:00" }, report_format: "csv"
      
      ActionController::UrlGenerationError:
        No route matches {:action=>"create", :controller=>"spree/admin/reports/enterprise_fee_summaries", :report=>{:start_at=>"2018-10-09 07:30:00"}, :report_format=>"csv"}
      # ./spec/controllers/spree/admin/reports/enterprise_fee_summaries_controller_spec.rb:26:in `block (4 levels) in <top (required)>'

  38) Spree::Admin::Reports::EnterpriseFeeSummariesController#create when the parameters are invalid renders the report form with an error
      Failure/Error: post :create, report: { start_at: "invalid date" }, report_format: "csv"
      
      ActionController::UrlGenerationError:
        No route matches {:action=>"create", :controller=>"spree/admin/reports/enterprise_fee_summaries", :report=>{:start_at=>"invalid date"}, :report_format=>"csv"}
      # ./spec/controllers/spree/admin/reports/enterprise_fee_summaries_controller_spec.rb:36:in `block (4 levels) in <top (required)>'

  39) Spree::Admin::Reports::EnterpriseFeeSummariesController#create when some parameters are now allowed renders the report form with an error
      Failure/Error: post :create, report: { distributor_ids: [other_distributor.id] }, report_format: "csv"
      
      ActionController::UrlGenerationError:
        No route matches {:action=>"create", :controller=>"spree/admin/reports/enterprise_fee_summaries", :report=>{:distributor_ids=>["1772"]}, :report_format=>"csv"}
      # ./spec/controllers/spree/admin/reports/enterprise_fee_summaries_controller_spec.rb:50:in `block (4 levels) in <top (required)>'

  40) Spree::Admin::Reports::EnterpriseFeeSummariesController#create filtering results based on permissions applies permissions to report
      Failure/Error: post :create, report: {}, report_format: "csv"
      
      ActionController::UrlGenerationError:
        No route matches {:action=>"create", :controller=>"spree/admin/reports/enterprise_fee_summaries", :report=>{}, :report_format=>"csv"}
      # ./spec/controllers/spree/admin/reports/enterprise_fee_summaries_controller_spec.rb:67:in `block (4 levels) in <top (required)>'

```

**Comment by Matt-Yorkley** [comment]
Ok... if I navigate manually to those pages (new and create) for `enterprise_fee_summary`, it finds the routes with no problem. The report works. If I grep with `rake routes`, the "missing" routes are present. So it seems like it's only the tests that are having trouble finding the routes, and not the app itself...
