### ISSUE TITLE
[Spree 2.1] Routes in order_management engine

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#4878]
The routes declared in [engines/order_management/config/routes.rb](https://github.com/openfoodfoundation/openfoodnetwork/blob/97a65d760f217cab03f414ae13863a5d3eb1f97a/engines/order_management/config/routes.rb) are not being loaded as expected, resulting in the following failing specs:

```
  36) Spree::Admin::Reports::EnterpriseFeeSummariesController#new renders the report form
      Failure/Error: get :new

      ActionController::UrlGenerationError:
        No route matches {:action=>"new", :controller=>"spree/admin/reports/enterprise_fee_summaries"}
      # ./spec/controllers/spree/admin/reports/enterprise_fee_summaries_controller_spec.rb:16:in `block (3 levels) in <top (required)>'

  37) Spree::Admin::Reports::EnterpriseFeeSummariesController#create when the parameters are valid sends the generated report in the correct format
      Failure/Error: post :create, report: { start_at: "2018-10-09 07:30:00" }, report_format: "csv"

      ActionController::UrlGenerationError:
        No route matches {:action=>"create", :controller=>"spree/admin/reports/enterprise_fee_summaries", :report=>{:start_at=>"2018-10-09 07:30:00"}, :report_format=>"csv"}
      # ./spec/controllers/spree/admin/reports/enterprise_fee_summaries_controller_spec.rb:26:in `block (4 levels) in <top (required)>'

  38) Spree::Admin::Reports::EnterpriseFeeSummariesController#create when the parameters are invalid renders the report form with an error
      Failure/Error: post :create, report: { start_at: "invalid date" }, report_format: "csv"

      ActionController::UrlGenerationError:
        No route matches {:action=>"create", :controller=>"spree/admin/reports/enterprise_fee_summaries", :report=>{:start_at=>"invalid date"}, :report_format=>"csv"}
      # ./spec/controllers/spree/admin/reports/enterprise_fee_summaries_controller_spec.rb:36:in `block (4 levels) in <top (required)>'

  39) Spree::Admin::Reports::EnterpriseFeeSummariesController#create when some parameters are now allowed renders the report form with an error
      Failure/Error: post :create, report: { distributor_ids: [other_distributor.id] }, report_format: "csv"

      ActionController::UrlGenerationError:
        No route matches {:action=>"create", :controller=>"spree/admin/reports/enterprise_fee_summaries", :report=>{:distributor_ids=>["1772"]}, :report_format=>"csv"}
      # ./spec/controllers/spree/admin/reports/enterprise_fee_summaries_controller_spec.rb:50:in `block (4 levels) in <top (required)>'

  40) Spree::Admin::Reports::EnterpriseFeeSummariesController#create filtering results based on permissions applies permissions to report
      Failure/Error: post :create, report: {}, report_format: "csv"

      ActionController::UrlGenerationError:
        No route matches {:action=>"create", :controller=>"spree/admin/reports/enterprise_fee_summaries", :report=>{}, :report_format=>"csv"}
      # ./spec/controllers/spree/admin/reports/enterprise_fee_summaries_controller_spec.rb:67:in `block (4 levels) in <top (required)>'
```

**Comment by Matt-Yorkley** [comment]
Duplicate of #4877 opened ~20 minutes before it :see_no_evil:
