### ISSUE TITLE
[Spree 2.1] Fix models/shipment_spec (1 broken spec)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4885]
Shipment model spec is failing for deleted variants. Maybe this is related to #4881 ?

Error:
```
 31) Spree::Shipment manifest when the variant is soft-deleted can still access the variant
      Failure/Error: expect(variants.sort_by(&:id)).to eq([deleted_variant, other_variant].sort_by(&:id))
      
        expected: [#<Spree::Variant id: 3234, sku: "ff45a39db332b2721eb4e989ae733008", weight: #<BigDecimal:7fd2221c553..."AUD", unit_value: 1.0, unit_description: "", display_name: nil, display_as: nil, import_date: nil>]
             got: [#<Spree::Variant id: 3235, sku: "91164e5c2524c93d21a29a2d92fcc28b", weight: #<BigDecimal:7fd2255be85..."AUD", unit_value: 1.0, unit_description: "", display_name: nil, display_as: nil, import_date: nil>]
      
        (compared using ==)
      
        Diff:
        @@ -1,3 +1,2 @@
        -[#<Spree::Variant id: 3234, sku: "ff45a39db332b2721eb4e989ae733008", weight: #<BigDecimal:7fd2221c5538,'0.1E-2',9(36)>, height: #<BigDecimal:7fd21e6c8a20,'0.18923E3',18(18)>, width: #<BigDecimal:7fd21e6c7e18,'0.3553E2',18(18)>, depth: #<BigDecimal:7fd21e6c71e8,'0.4276E2',18(18)>, deleted_at: "2020-03-02 18:47:24", is_master: false, product_id: 1283, cost_price: #<BigDecimal:7fd21e66ae20,'0.17E2',9(36)>, position: 3, cost_currency: "AUD", unit_value: 1.0, unit_description: "", display_name: nil, display_as: nil, import_date: nil>,
        - #<Spree::Variant id: 3235, sku: "91164e5c2524c93d21a29a2d92fcc28b", weight: #<BigDecimal:7fd21e26a2a8,'0.1E-2',9(36)>, height: #<BigDecimal:7fd222138728,'0.1146E2',18(18)>, width: #<BigDecimal:7fd222138340,'0.5447E2',18(18)>, depth: #<BigDecimal:7fd222137f08,'0.2331E2',18(18)>, deleted_at: nil, is_master: false, product_id: 1283, cost_price: #<BigDecimal:7fd221fc7a60,'0.17E2',9(36)>, position: 4, cost_currency: "AUD", unit_value: 1.0, unit_description: "", display_name: nil, display_as: nil, import_date: nil>]
        +[#<Spree::Variant id: 3235, sku: "91164e5c2524c93d21a29a2d92fcc28b", weight: #<BigDecimal:7fd2255be858,'0.0',9(18)>, height: #<BigDecimal:7fd2255be790,'0.1146E2',18(18)>, width: #<BigDecimal:7fd2255be650,'0.5447E2',18(18)>, depth: #<BigDecimal:7fd2255be560,'0.2331E2',18(18)>, deleted_at: nil, is_master: false, product_id: 1283, cost_price: #<BigDecimal:7fd2255be2b8,'0.17E2',9(18)>, position: 4, cost_currency: "AUD", unit_value: 1.0, unit_description: "", display_name: nil, display_as: nil, import_date: nil>]
        
      # ./spec/models/spree/shipment_spec.rb:19:in `block (4 levels) in <top (required)>'
```

**Comment by luisramos0** [comment]
Maybe this is related?

```
  39) Stock::Package#shipping_methods does not return shipping methods not used by the package's order distributor
      Failure/Error: expect(package.shipping_methods).to eq [shipping_method1]
      
        expected: [#<Spree::ShippingMethod id: 411, name: "UPS Ground", created_at: "2020-03-02 18:47:36", updated_at: ..., display_on: "", deleted_at: nil, require_ship_address: true, description: nil, tracking_url: nil>]
             got: []
      
        (compared using ==)
      
        Diff:
        @@ -1,2 +1,2 @@
        -[#<Spree::ShippingMethod id: 411, name: "UPS Ground", created_at: "2020-03-02 18:47:36", updated_at: "2020-03-02 18:47:36", display_on: "", deleted_at: nil, require_ship_address: true, description: nil, tracking_url: nil>]
        +[]
        
      # ./spec/models/stock/package_spec.rb:44:in `block (3 levels) in <module:Stock>'
```

**Comment by luisramos0** [comment]
For some reason [this change in spree](https://github.com/openfoodfoundation/spree/pull/41/files) is not working anymore and so shipment.manifest is not including deleted variants...
