### ISSUE TITLE
[Flaky spec] Fix services/exchange_products_renderer_spec (2 broken specs)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4899]
```

  21) ExchangeProductsRenderer#exchange_variants for an incoming exchange when OC is showing only the coordinators inventory renders visible inventory variants
      Failure/Error: let!(:hidden_inventory_item) { create(:inventory_item, enterprise: order_cycle.coordinator, variant: exchange_with_hidden_variant.variants.first, visible: false) }
      
      ActiveRecord::RecordInvalid:
        Validation failed: Variant has already been taken
      # ./spec/services/exchange_products_renderer_spec.rb:43:in `block (5 levels) in <top (required)>'

  22) ExchangeProductsRenderer#exchange_variants for an incoming exchange when OC is showing only the coordinators inventory does not render hidden inventory variants
      Failure/Error: let!(:hidden_inventory_item) { create(:inventory_item, enterprise: order_cycle.coordinator, variant: exchange_with_hidden_variant.variants.first, visible: false) }
      
      ActiveRecord::RecordInvalid:
        Validation failed: Variant has already been taken
      # ./spec/services/exchange_products_renderer_spec.rb:43:in `block (5 levels) in <top (required)>'
```

**Comment by luisramos0** [comment]
Some other PR must have fixed this one :+1:

**Comment by Matt-Yorkley** [comment]
This is a validates "uniqueness" error of some kind, I think it's triggered by the way factories are building the associated variants in the OC / exchanges...
