### ISSUE TITLE
[Spree 2.1] Fix new caching specs in rails 4 branch

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5462]
## Description
This spec is broken:
spec/features/consumer/caching/darkwarm_caching_spec.rb
I dont understand this problem
```
(byebug) Spree::Taxon.select("DISTINCT spree_taxons.id, ents_and_vars.enterprise_id")
*** ArgumentError Exception: wrong number of arguments (given 1, expected 0)

```

the build:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/3-0-stable/builds/81

**Comment by luisramos0** [comment]
ping @Matt-Yorkley any thoughts?

**Comment by Matt-Yorkley** [comment]
I'll take a look. This is the `Spree::Taxon.distributed_taxons` scope...

**Comment by Matt-Yorkley** [comment]
Well this is very odd, there are lots of places now where for example: calls to things like `Spree::Taxon.where...` are now saying we can't call `#where` on an `Array`. So `Spree::Taxon` is an array..?

If I change these bits to `Spree::Taxon.unscoped.where...` it seems to pass / work as expected.

Another odd thing: these bits of code are failing when loading pages in feature specs in the test suite, but are **not** failing when I boot the app and visit those same pages.

**Comment by Matt-Yorkley** [comment]
I think it might be related to this: https://github.com/rails/rails/issues/10658 

Jon Leighton's name is all over it again :sweat_smile:

**Comment by Matt-Yorkley** [comment]
Okay, it's only in these caching feature specs and not anywhere else... this is really strange.

**Comment by Matt-Yorkley** [comment]
Aha, it looks like this is caused by a new gem added in Spree 2.1 called `awesome_nested_set`. `acts_as_nested_set` is added to a few spree models now, including taxons...

```
"undefined method `where' for #<Array:0x00005575f41ca628>"
["/home/user/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/activerecord-4.0.13/lib/active_record/querying.rb:9:in `where'",
 "/home/user/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/awesome_nested_set-3.0.3/lib/awesome_nested_set/model.rb:84:in `nested_set_scope'",
 "/home/user/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/activerecord-4.0.13/lib/active_record/relation/delegation.rb:36:in `block in nested_set_scope'",
 "/home/user/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/activerecord-4.0.13/lib/active_record/relation.rb:270:in `scoping'",
 "/home/user/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/activerecord-4.0.13/lib/active_record/relation/delegation.rb:36:in `nested_set_scope'",
 "/home/user/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/awesome_nested_set-3.0.3/lib/awesome_nested_set/model.rb:148:in `nested_set_scope'",
 "/home/user/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/awesome_nested_set-3.0.3/lib/awesome_nested_set/model/relatable.rb:14:in `self_and_ancestors'",
 "/home/user/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/awesome_nested_set-3.0.3/lib/awesome_nested_set/model/relatable.rb:9:in `ancestors'",
 "/home/user/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/bundler/gems/spree-f9264ebca0d8/core/app/models/spree/taxon.rb:66:in `pretty_name'",
 "/home/user/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/active_model_serializers-0.8.4/lib/active_model/serializer.rb:99:in `block in attribute'",
 "(eval):6:in `_fast_attributes'",
 "/home/user/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/active_model_serializers-0.8.4/lib/active_model/serializer.rb:468:in `rescue in attributes'",
 "/home/user/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/active_model_serializers-0.8.4/lib/active_model/serializer.rb:455:in `attributes'",
 "/home/user/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/active_model_serializers-0.8.4/lib/active_model/serializer.rb:480:in `_serializable_hash'",
 "/home/user/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/active_model_serializers-0.8.4/lib/active_model/serializer.rb:359:in `serializable_hash'",
```

**Comment by sigmundpetersen** [comment]
I take it this can be closed
