### ISSUE TITLE
[Spree 2.1] Flaky variant_overrides_spec

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#5523]
Looks like a minor timing issue this spec:

```
     Failure/Error: expect(page).to have_content "I couldn't get authorisation to save those changes, so they remain unsaved."
       expected to find text "I couldn't get authorisation to save those changes, so they remain unsaved." in "Logged in as : ashleigh.kunze@bednar.com Account Logout Store DASHBOARD PRODUCTS ORDER CYCLES ORDERS REPORTS ENTERPRISES CUSTOMERS PRODUCTS INVENTORY IMPORT Inventory What's this? QUICK SEARCH SHOP Enterprise 28 Enterprise 28 PRODUCER All IMPORTED All There are 2 new products available to add to your inventory. × ACTIONS VIEWING: INVENTORY PRODUCTS COLUMNS Saving... PRODUCER PRODUCT PRICE ON HAND ON DEMAND? Enterprise 30 Product #16 - 7678 1g Use producer stock settings Yes No Enterprise 32 Product #18 - 8099 2g, S Use producer stock settings Yes No"
     # ./spec/features/admin/variant_overrides_spec.rb:202:in `block (7 levels) in <top (required)>'
     # ./spec/features/admin/variant_overrides_spec.rb:200:in `block (6 levels) in <top (required)>'
```

The page content includes `Saving...` but it looks like the test is looking for the post-save message.

**Comment by Matt-Yorkley** [comment]
Possibly flaky, it's not showing up now...

**Comment by luisramos0** [comment]
this is a duplciate of #4957
