### ISSUE TITLE
[Flaky spec] ./spec/features/consumer/caching/darkwarm_caching_spec.rb:32

### ISSUE THREAD

**Issue by sigmundpetersen** [openfoodfoundation/openfoodnetwork#5619]
```
  1) Darkswarm data caching caching injected taxons and properties invalidates caches for taxons and properties
     Failure/Error: expect(taxon_timestamp1).to_not eq taxon_timestamp2
     
       expected: value != 1592233121
            got: 1592233121
     
       (compared using ==)
     # ./spec/features/consumer/caching/darkwarm_caching_spec.rb:62:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:129:in `block (2 levels) in <top (required)>'
```

https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1496

**Comment by Matt-Yorkley** [comment]
Ah, I re-enabled this in the Spree upgrade branch when updating the caching code for Rails 4. It's still flaky though.

**Comment by sigmundpetersen** [comment]
This is still failing I'm afraid.
