### ISSUE TITLE
[Rails 4.1] Fix spec spec/controllers/api/order_cycles_controller_spec.rb (13 broken specs)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5631]
This error in this build:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-5611/builds/2

```
 46) Api::OrderCyclesController#products when tag rules apply does not return variants hidden for this specific customer
      Failure/Error: json_response.map{ |product| product['id'] }
      
      TypeError:
        no implicit conversion of String into Integer
      # ./spec/controllers/api/order_cycles_controller_spec.rb:225:in `[]'
      # ./spec/controllers/api/order_cycles_controller_spec.rb:225:in `block in product_ids'
      # ./spec/controllers/api/order_cycles_controller_spec.rb:225:in `each'
      # ./spec/controllers/api/order_cycles_controller_spec.rb:225:in `map'
      # ./spec/controllers/api/order_cycles_controller_spec.rb:225:in `product_ids'
      # ./spec/controllers/api/order_cycles_controller_spec.rb:135:in 
```

If I debug product_ids I see the controller looking for a template:
![image](https://user-images.githubusercontent.com/1640378/84952054-47ff3e80-b0e9-11ea-91b9-b811cdbcb853.png)

We need some trick in the controller to make it render the json using the serializer provided and not look for a template.

**Comment by jeduardo824** [comment]
@luisramos0 I will push a PR with a way I found to fix it
