### ISSUE TITLE
[Rails 4.1] Fix spec/models/spree/adjustment_spec.rb (4 broken specs)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5632]
Broken specs in this build
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-5611/builds/2

With this error:
```
 17) Spree::Adjustment recording included tax EnterpriseFee adjustments when enterprise fees have a fixed tax_category when enterprise fees are taxed per-item when the tax rate does not include the tax in the price records the tax on TaxRate adjustment on the order
      Failure/Error:
        per_item_fees_total = order.line_items.sum do |line_item|
          calculator.per_item_enterprise_fee_applicators_for(line_item.variant)
            .select { |applicator|
              (!applicator.enterprise_fee.inherits_tax_category && applicator.enterprise_fee.tax_category == rate.tax_category) ||
                (applicator.enterprise_fee.inherits_tax_category && line_item.product.tax_category == rate.tax_category)
            }
            .sum { |applicator| applicator.enterprise_fee.compute_amount(line_item) }
        end
      
      ArgumentError:
        wrong number of arguments (given 1, expected 2..3)
      # ./app/models/spree/calculator/default_tax_decorator.rb:19:in `compute_order'
      # ./app/models/spree/tax_rate_decorator.rb:15:in `adjust_with_included_tax'
      # ./spec/models/spree/adjustment_spec.rb:195:in `block (7 levels) in <module:Spree>'
```

Replacing sum with map and sum, fixes the specs:
![image](https://user-images.githubusercontent.com/1640378/84952777-73cef400-b0ea-11ea-93b4-c09d686289ee.png)

This needs to be done after #5613 is merged to avoid conflicts.

**Comment by jeduardo824** [comment]
I will check

**Comment by luisramos0** [comment]
This has now been fixed. Closing.
