### ISSUE TITLE
[Flaky spec] ./spec/features/admin/order_cycles/complex_updating_specific_time_spec.rb:14

### ISSUE THREAD

**Issue by sigmundpetersen** [openfoodfoundation/openfoodnetwork#5634]
```
1) 
    As an administrator
    I want to create/update complex order cycles with a specific time
 updating an order cycle
     Failure/Error: expect(page).to have_field("order_cycle_outgoing_exchange_2_pickup_time")
       expected to find visible field "order_cycle_outgoing_exchange_2_pickup_time" that is not disabled but there were no matches
     # ./spec/features/admin/order_cycles/complex_updating_specific_time_spec.rb:92:in `block (2 levels) in <top (required)>'
```

https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1501

**Comment by Matt-Yorkley** [comment]
There's a slightly different line in the file where this spec is also occasionally failing:
```
As an administrator
    I want to create/update complex order cycles with a specific time
 updating an order cycle
     Failure/Error: expect(exchange_row).to have_selector "tr", count: 2
       expected to find visible css "tr" within #<Capybara::Node::Element tag="tbody" path="/html/body/div[1]/div[4]/div/div/div/form/table/tbody[2]"> 2 times, found 1 match: "Enterprise 409 1 / 0 selected 0 Enterprise 406 Enterprise 407 Enterprise 408 Enterprise 409 My supplier My distributor Enterprise fee 55 Remove". Also found "", which matched the selector but not all filters.
     # ./spec/features/admin/order_cycles/complex_updating_specific_time_spec.rb:112:in `block (3 levels) in <top (required)>'
     # ./spec/features/admin/order_cycles/complex_updating_specific_time_spec.rb:109:in `block (2 levels) in <top (required)>'
```
So it's both line 92 and line 109...

**Comment by Matt-Yorkley** [comment]
There's actually a third one around line 74 as well. So this spec is flaky in three distinct places...
