### ISSUE TITLE
Home page not working in local environment

### ISSUE THREAD

**Issue by jhsu802701** [openfoodfoundation/openfoodnetwork#6153]
## Description
When I enter "docker-compose up" and try to view the app at http://localhost:3000/ PRIOR to seeding the database, I see the following messages:
```
ActiveRecord::StatementInvalid in HomeController#index
```
```
PG::UndefinedTable: ERROR: relation "enterprises" does not exist LINE 5: WHERE a.attrelid = '"enterprises"'::regclass ^ : SELECT a.attname, format_type(a.atttypid, a.atttypmod), pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod FROM pg_attribute a LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum WHERE a.attrelid = '"enterprises"'::regclass AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum 
```
The extracted source:
```
  def cached_count(statistic, query)
    CacheService.home_stats(statistic) do
      query.count
    end
  end
end
```
The application trace shows:
```
app/controllers/home_controller.rb:28:in `block in cached_count'
app/services/cache_service.rb:32:in `block in home_stats'
app/services/cache_service.rb:29:in `home_stats'
app/controllers/home_controller.rb:27:in `cached_count'
app/controllers/home_controller.rb:8:in `index'
```

**Comment by jhsu802701** [comment]
There is no test of the home controller.  As far as I can tell, there is no test of the home page.  This may be why this app still passes in continuous integration.

**Comment by jhsu802701** [comment]
Lines 28 to 34 in app/services/cache_service.rb:
```
  def self.home_stats(statistic)
    Rails.cache.fetch("home_stats_count_#{statistic}",
                      expires_in: HOME_STATS_EXPIRY,
                      race_condition_ttl: 10) do
      yield
    end
  end
```
Line 32 is "yield".

**Comment by RachL** [comment]
I'm closing as it has not happened recently. Please reopen if it is still happening! Thanks :)
