### ISSUE TITLE
[Flaky Spec] order_cycles/simple_spec.rb

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#6624]
```
As an administrator
    I want to manage simple order cycles
 as an enterprise user that is a manager of the coordinator creating a new order cycle
     Failure/Error: page.find("table.exchanges tr.supplier-#{supplier.id} td.products").click
     
     Capybara::ElementNotFound:
       Unable to find css "table.exchanges tr.supplier-230 td.products"
     # ./spec/features/admin/order_cycles/simple_spec.rb:615:in `select_incoming_variant'
     # ./spec/features/admin/order_cycles/simple_spec.rb:208:in `block (4 levels) in <top (required)>'
```
and:
```
As an administrator
    I want to manage simple order cycles
 as an enterprise user that is a manager of the coordinator creating a new order cycle
     Failure/Error: expect(page).to have_input 'order_cycle_outgoing_exchange_1_pickup_time'
       expected to find css "[name='order_cycle_outgoing_exchange_1_pickup_time']" but there were no matches
     # ./spec/features/admin/order_cycles/simple_spec.rb:224:in `block (4 levels) in <top (required)>'
```

**Comment by Matt-Yorkley** [comment]
This is failing quite often now, I think it's currently our flakiest spec.

**Comment by sigmundpetersen** [comment]
This is still failing in master https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/2056

**Comment by mkllnk** [comment]
I get a fail rate of 18% here. That's quite urgent.
