### ISSUE TITLE
[Rails 5.2] StackError on generating permalinks

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#7074]
Lots of these errors are filling the build:
```
OrderFeesHandler checking if a line item can be provided by the order cycle returns false when there is no order cycle
       Failure/Error: existing = others.where("permalink LIKE ?", "#{requested}%").pluck(:permalink)
       
       SystemStackError:
         stack level too deep
       # ./lib/open_food_network/permalink_generator.rb:29:in `create_unique_permalink'
       # ./app/models/spree/product.rb:477:in `sanitize_permalink'
       # ./spec/factories/order_cycle_factory.rb:42:in `block (4 levels) in <top (required)>'
       # ./spec/factories/order_cycle_factory.rb:41:in `each'
       # ./spec/factories/order_cycle_factory.rb:41:in `block (3 levels) in <top (required)>'
       # ./spec/services/order_fees_handler_spec.rb:6:in `block (2 levels) in <top (required)>'
       # ./spec/services/order_fees_handler_spec.rb:7:in `block (2 levels) in <top (required)>'
       # ./spec/services/order_fees_handler_spec.rb:10:in `block (2 levels) in <top (required)>'
       # ./spec/services/order_fees_handler_spec.rb:16:in `block (2 levels) in <top (required)>'
```

Looks like we need to update the `PermalinkGenerator` module, but we can probably pull in some upstream changes from Spree.

**Comment by luisramos0** [comment]
spree switched to friend_id long before reaching rails 5.
https://github.com/spree/spree/commit/d4d955017102f31980cc3cf3c0ca7ad9f5b053bd

**Comment by luisramos0** [comment]
hmmm, I  gave this one a try but couldnt find the issue.
I removed a lot of code relates to permalinks and got errors in other validators, so I am not sure this is even related to permalink but maybe just genericaly to validators on the product model...

**Comment by Matt-Yorkley** [comment]
Interesting.... if I comment out line 94 in Spree::Product (the validation on tax_category_id), the `StackError`s seem to disappear...

**Comment by Matt-Yorkley** [comment]
I think I got it! Changing the conditional in this validation to a proc seems to fix it.
```diff
-- validates :tax_category_id, presence: true, if: Spree::Config.products_require_tax_category
++ validates :tax_category_id, presence: true, if: proc { Spree::Config[:products_require_tax_category] }
```

**Comment by luisramos0** [comment]
Awesome!
