### ISSUE TITLE
[Rails 5.2] Sanitize calls in SQL

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#7075]
This one appears ~170 times in the build:

```
Api::OrdersController#index as an admin user retrieves a list of orders with appropriate attributes,
            including line items with appropriate attributes
      Failure/Error:
        joins("
          LEFT OUTER JOIN (SELECT *
                             FROM inventory_items
                             WHERE enterprise_id = #{sanitize enterprise.andand.id})
            AS o_inventory_items
            ON o_inventory_items.variant_id = spree_variants.id")
      
      NoMethodError:
        undefined method `sanitize' for #<ActiveRecord::Relation []>
      # ./app/models/spree/variant.rb:117:in `block in <class:Variant>'
      # ./app/models/enterprise.rb:284:in `inventory_variants'
      # ./app/models/order_cycle.rb:176:in `variants_distributed_by'
      # ./app/services/order_cycle_distributed_variants.rb:18:in `available_variants'
      # ./app/services/order_cycle_distributed_variants.rb:12:in `unavailable_order_variants'
      # ./app/services/order_cycle_distributed_variants.rb:8:in `distributes_order_variants?'
      # ./app/models/spree/order.rb:584:in `products_available_from_new_distribution'
      # ./spec/controllers/api/orders_controller_spec.rb:23:in `block (3 levels) in <module:Api>'
```

Probably fairly straightforward to fix...

**Comment by luisramos0** [comment]
I think we can just remore sanitize, I did it in https://github.com/openfoodfoundation/openfoodnetwork/pull/7053
