### ISSUE TITLE
[Rails 5.2] Params merge in controller tests

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#7076]
This and similar errors come up ~250 times in the current build:

```
Api::StatesController with two states gets all states for a country
       Failure/Error:
         process(action,
                 method,
                 params.reverse_merge!(use_route: :main_app),
                 session,
                 flash)
       
       ArgumentError:
         wrong number of arguments (given 5, expected 1)
       # ./spec/support/controller_requests_helper.rb:49:in `process_action_with_route'
       # ./spec/support/controller_requests_helper.rb:41:in `process_json_action'
       # ./spec/support/controller_requests_helper.rb:7:in `api_get'
       # ./spec/controllers/api/states_controller_spec.rb:56:in `block (3 levels) in <module:Api>'
```

**Comment by luisramos0** [comment]
fixed in 7053 :+1:
