### ISSUE TITLE
[Rails 5.2] Undefined helper methods

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#7091]
There's quite a few like this:
```
Check out with Stripe using Stripe SCA with a logged in user saving a card and re-using it allows saving a card and re-using it
       Failure/Error: super
       
       ActionView::Template::Error:
         undefined method `terms_and_conditions_activated?' for #<#<Class:0x00007f192b29c278>:0x00007f1920b0d390>
       # ./app/helpers/application_helper.rb:20:in `method_missing'
       # ./app/views/checkout/_terms_and_conditions.html.haml:1:in `_app_views_checkout__terms_and_conditions_html_haml___3882455399943719169_69872954490380'
       # ./app/views/checkout/_form.html.haml:18:in `block in _app_views_checkout__form_html_haml__1664303948059702347_69872956121000'
       # ./app/views/checkout/_form.html.haml:6:in `_app_views_checkout__form_html_haml__1664303948059702347_69872956121000'
       # ./app/views/checkout/edit.html.haml:32:in `_app_views_checkout_edit_html_haml__2217575113360240181_69872949687160'
       # ./lib/open_food_network/rack_request_blocker.rb:36:in `call'
       # ------------------
       # --- Caused by: ---
       # NoMethodError:
       #   undefined method `terms_and_conditions_activated?' for #<#<Class:0x00007f192b29c278>:0x00007f1920b0d390>
       #   ./app/helpers/application_helper.rb:20:in `method_missing'
```

Rails 5.2 has changed the way helpers are auto-loaded. I made a rough start on addressing this in [this commit](https://github.com/openfoodfoundation/openfoodnetwork/commit/d64ae9584ae5013d0ab252a71593f1f072cead76) which fixed the majority of the related errors, but not all of them.

**Comment by luisramos0** [comment]
#7096 continues this but there are still more specs because of this. I wont be able to come back to this soon.

**Comment by Matt-Yorkley** [comment]
Looks like there's a few more in the engines specs, but they're not showing up nicely in the build.

**Comment by luisramos0** [comment]
They are now showing up correctly in the build.
