### ISSUE TITLE
[Rails 5.2] Tax category factory

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#7092]
Not sure if it's an issue with the factory or not, but wherever we use the tax_category factory and pass in tax_rates as an argument, we get this validation error:
```
Spree::Adjustment recording included tax EnterpriseFee adjustments when enterprise fees inherit their tax_category from the product they are applied to when enterprise fees are taxed per-item when the tax rate does not include the tax in the price records the tax on TaxRate adjustment on the order
       Failure/Error: let(:product_tax_category) { create(:tax_category, tax_rates: [product_tax_rate]) }
       
       ActiveRecord::RecordInvalid:
         Validation failed: Tax rates is invalid
       # ./spec/models/spree/adjustment_spec.rb:350:in `block (5 levels) in <module:Spree>'
       # ./spec/models/spree/adjustment_spec.rb:353:in `block (5 levels) in <module:Spree>'
```

**Comment by luisramos0** [comment]
Something to do with the relationship between tax_category and its tax_rates.
teh spec becomes green if we comment the validator of tax_Category_id on the tax_rate:

```ruby
diff --git a/app/models/spree/tax_rate.rb b/app/models/spree/tax_rate.rb
index e0fe37a77..5453cc71c 100644
--- a/app/models/spree/tax_rate.rb
+++ b/app/models/spree/tax_rate.rb
@@ -20,7 +20,7 @@ module Spree

     validates :amount, presence: true, numericality: true
-    validates :tax_category_id, presence: true
+    #validates :tax_category_id, presence: true
     validates_with DefaultTaxZoneValidator

```

**Comment by Matt-Yorkley** [comment]
Is see `class_name: 'Spree::TaxCategory'` is missing in the definition of the `has_many :tax_rates` relationship in `Spree::TaxCategory`... that could be it? I think all of our other relationships with Spree classes define the class name.

**Comment by Matt-Yorkley** [comment]
Aha... I think `tax_category_id` needs to be `tax_category` in the that validation in `Spree::TaxRate`.

**Comment by luisramos0** [comment]
yes, that's it! #7186
