### ISSUE TITLE
[Rails 5.2] Empty TaxRate.calculators and ShippingMethod.calculators (~100 broken specs)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#7101]
Looks like this commit wasnt 100% successful: https://github.com/openfoodfoundation/openfoodnetwork/commit/224789193dfbfe17b1b8b416149ed75d0820f0bf

All these below are caused by calculators not being available in the objects like EnterpriseFee, ShippingMethod, PaymentMethod and TaxRate. 

This type of error:
```
 152) Spree::Admin::ShippingMethodsController#update updates details of a PriceSack calculator
       Failure/Error: @calculators = ShippingMethod.calculators.sort_by(&:name)
       
       NoMethodError:
         undefined method `sort_by' for nil:NilClass
       # ./app/controllers/spree/admin/shipping_methods_controller.rb:82:in `load_data'
       # ./spec/support/controller_requests_helper.rb:49:in `process_action_with_route'
       # ./spec/support/controller_requests_helper.rb:27:in `spree_post'
       # ./spec/controllers/spree/admin/shipping_methods_controller_spec.rb:82:in `block (3 levels) in <top (required)>'

```

This one:
```

 155) Spree::Admin::PaymentMethodsController#create and #update does not clear password on update
       Failure/Error: Gateway.providers.sort_by(&:name)
       
       NoMethodError:
         undefined method `sort_by' for nil:NilClass
       # ./app/controllers/spree/admin/payment_methods_controller.rb:107:in `load_data'
       # ./spec/support/controller_requests_helper.rb:49:in `process_action_with_route'
       # ./spec/support/controller_requests_helper.rb:31:in `spree_put'
       # ./spec/controllers/spree/admin/payment_methods_controller_spec.rb:20:in `block (3 levels) in <module:Spree>'
```

and tax rate one:
```
 188) Tax Rates while editing fields can be filled in and dropfdowns retains changes
       Failure/Error: @calculators = TaxRate.calculators.sort_by(&:name)
       
       NoMethodError:
         undefined method `sort_by' for nil:NilClass
       # ./app/controllers/spree/admin/tax_rates_controller.rb:51:in `load_data'
       # ./lib/open_food_network/rack_request_blocker.rb:36:in `call'
       # ./spec/features/admin/configuration/tax_rates_spec.rb:37:in `block (3 levels) in <top (required)>'

```

as well as these:
```
 24) 
    As an administrator
    I want to manage simple order cycles
 as an enterprise user that is a manager of the coordinator creating a new order cycle
      Failure/Error: spree_calculators.__send__(model_name_without_spree_namespace)
      
      NoMethodError:
        undefined method `enterprise_fees' for #<Spree::Core::Environment::Calculators:0x00005597f7c43788>
      # ./lib/spree/core/calculated_adjustments.rb:13:in `calculators'
      # ./app/controllers/admin/enterprise_fees_controller.rb:49:in `load_data'
      # ./lib/open_food_network/rack_request_blocker.rb:36:in `call'
      # ------------------
      # --- Caused by: ---
      # Capybara::ElementNotFound:
      #   Unable to find visible field "order_cycle_name" that is not disabled
      #   ./spec/features/admin/order_cycles/simple_spec.rb:189:in `block (4 levels) in <top (required)>'

```

**Comment by luisramos0** [comment]
@Matt-Yorkley fyi

**Comment by luisramos0** [comment]
Hi Matt, do you have a fix for this?

**Comment by Matt-Yorkley** [comment]
The last two commits in #7106 (dropping the previous change to initializers and adding a different fix). It's now in the main branch.

**Comment by luisramos0** [comment]
ok, thanks, so we can close this issue :+1:
