### ISSUE TITLE
bulk_order_management_spec.rb test fails due to timezone bug

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#7118]
### What we should change and why
Tests in `bulk_order_management_spec.rb` fails since commit #e341b044878792a64a8e39b1613434c4cee4b38a

File: `config/environments/test.rb`
```diff
- config.time_zone = ENV.fetch("TIMEZONE", "Melbourne")
+ config.time_zone = "UTC"
```

Output:
```
  1) 
  As an Administrator
  I want to be able to manage orders in bulk
 using page controls using date restriction controls only loads line items whose orders meet the date restriction criteria
     Failure/Error: expect(page).to have_no_selector "tr#li_#{li1.id}"
       expected not to find visible css "tr#li_52", found 1 match: "John Doe March 07, 2021 Enterprise 128 Product #90 - 8050: 1g, S 1"
     # ./spec/features/admin/bulk_order_management_spec.rb:466:in `block (4 levels) in <top (required)>'

  2) 
  As an Administrator
  I want to be able to manage orders in bulk
 using page controls using date restriction controls displays only line items whose orders meet the date restriction criteria, when changed
     Failure/Error: expect(page).to have_selector "tr#li_#{li3.id}"
       expected to find css "tr#li_58" but there were no matches
     # ./spec/features/admin/bulk_order_management_spec.rb:478:in `block (4 levels) in <top (required)>'
```

**Comment by Matt-Yorkley** [comment]
I think the Semaphore configs explicitly pass an ENV var for the Timezone, and I guess the Github CI setup does not, but it wants UTC. I wonder if going half-way between those two options is the best? We could do:
```ruby
config.time_zone = ENV.fetch("TIMEZONE", "UTC")
```

**Comment by jibees** [comment]
In term of strictly _green build_, I think you are right and we should quickly follow your recommendations.
But, to go further and regarding my investigations (I've updated the issue description), I think the issue is deeper than "just" timezone configuration into test env.  And I've no idea on how to fix this.

**Comment by Matt-Yorkley** [comment]
Cool, I made a one-line PR for that change. Happy to leave this issue open though if you think it needs more investigation :+1:

**Comment by jibees** [comment]
Thanks @Matt-Yorkley ! Now I think this is issue is no more tech debt, and its priority should slightly decrease (and it seems that no one was bothered by this behaviour)

**Comment by sauloperez** [comment]
Where do you see we're converting the dates to UTC? AFAIK we should send UTC dates to the backend and then localize them on the FE them depending on the user's timezone.

**Comment by jibees** [comment]
I don't see anything that convert in UTC in the backend (actually I haven't looked for). In my explanations I've just converted to UTC to understand and compare date between each others.
We send date with timezone to the server which can be a valid solution as it seems to be correctly understood (as we return the right orders)
