### ISSUE TITLE
[Raisl 5.2] Helper in bulk invoice renderer - 3 broken specs (test-engines-etc)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#7379]
3 broken specs in invoice renderer, adding the helper to the spec was not enough, I think it's because there's a delayed job between the spec and the template. this is the error:

```
2) BulkInvoiceService#start_pdf_job creates a PDF invoice
     Failure/Error: super
     
     ActionView::Template::Error:
       undefined method `payment_method_name' for #<#<Class:0x000055738043f3c0>:0x000055738043d6d8>
     # ./app/helpers/application_helper.rb:20:in `method_missing'
     # ./app/views/spree/shared/_payments_list.html.haml:12:in `block in _app_views_spree_shared__payments_list_html_haml___2124291698285014113_46977278418960'
     # ./app/views/spree/shared/_payments_list.html.haml:9:in `_app_views_spree_shared__payments_list_html_haml___2124291698285014113_46977278418960'
     # ./app/views/spree/shared/_payment.html.haml:15:in `_app_views_spree_shared__payment_html_haml___4052929526227959592_46977278544340'
     # ./app/views/spree/admin/orders/invoice.html.haml:73:in `_app_views_spree_admin_orders_invoice_html_haml__1616803015852987099_46977280762200'
     # ./app/services/invoice_renderer.rb:8:in `render_to_string'
     # ./app/jobs/bulk_invoice_job.rb:8:in `block in perform'
     # ./app/jobs/bulk_invoice_job.rb:7:in `perform'
     # ./app/services/bulk_invoice_service.rb:9:in `start_pdf_job'
     # ./spec/services/bulk_invoice_service_spec.rb:25:in `block (4 levels) in <top (required)>'
     # ./spec/services/bulk_invoice_service_spec.rb:24:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `payment_m
```

**Comment by Matt-Yorkley** [comment]
Adding `helper 'spree/admin/payments'` in `ApplicationController` works, but it's not pretty...
