### ISSUE TITLE
[Rails 6.0] Fix problem in erb template 

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#7558]
```
26) Spree::Admin::OrdersController#edit view does not show ineligible payment adjustments
      Failure/Error: = render :partial => 'spree/admin/shared/update_order_state', :handlers => [:erb]
      
      ActionView::Template::Error:
        Missing partial spree/admin/shared/_update_order_state with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb]}. Searched in:
          * "/home/runner/work/openfoodnetwork/openfoodnetwork/app/views"
          * "/home/runner/work/openfoodnetwork/openfoodnetwork/vendor/bundle/ruby/2.5.0/gems/view_component-2.31.1/app/views"
          * "/home/runner/work/openfoodnetwork/openfoodnetwork/vendor/bundle/ruby/2.5.0/gems/foundation-rails-5.5.2.1/app/views"
          * "/home/runner/work/openfoodnetwork/openfoodnetwork/vendor/bundle/ruby/2.5.0/gems/kaminari-core-1.2.1/app/views"
          * "/home/runner/work/openfoodnetwork/openfoodnetwork/vendor/bundle/ruby/2.5.0/gems/devise-4.8.0/app/views"
          * "/home/runner/work/openfoodnetwork/openfoodnetwork/engines/web/app/views"
          * "/home/runner/work/openfoodnetwork/openfoodnetwork/engines/order_management/app/views"
          * "/home/runner/work/openfoodnetwork/openfoodnetwork/vendor/bundle/ruby/2.5.0/gems/actiontext-6.0.3.6/app/views"
          * "/home/runner/work/openfoodnetwork/openfoodnetwork/vendor/bundle/ruby/2.5.0/gems/actionmailbox-6.0.3.6/app/views"
      # ./app/views/spree/admin/orders/_form.html.haml:29:in `block in _app_views_spree_admin_orders__form_html_haml___3896545621144349112_47235709899480'
      # ./app/views/spree/admin/orders/_form.html.haml:24:in `_app_views_spree_admin_orders__form_html_haml___3896545621144349112_47235709899480'
      # ./app/views/spree/admin/orders/edit.html.haml:29:in `_app_views_spree_admin_orders_edit_html_haml___2707275614111388923_47235724006520'
      # ./spec/support/controller_requests_helper.rb:49:in `process_action_with_route'
      # ./spec/support/controller_requests_helper.rb:23:in `spree_get'
      # ./spec/controllers/spree/admin/orders_controller_spec.rb:33:in `block (4 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # ActionView::MissingTemplate:
      #   Missing partial spree/admin/shared/_update_order_state with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb]}. Searched in:
      #     * "/home/runner/work/openfoodnetwork/openfoodnetwork/app/views"
      #     * "/home/runner/work/openfoodnetwork/openfoodnetwork/vendor/bundle/ruby/2.5.0/gems/view_component-2.31.1/app/views"
      #     * "/home/runner/work/openfoodnetwork/openfoodnetwork/vendor/bundle/ruby/2.5.0/gems/foundation-rails-5.5.2.1/app/views"
      #     * "/home/runner/work/openfoodnetwork/openfoodnetwork/vendor/bundle/ruby/2.5.0/gems/kaminari-core-1.2.1/app/views"
      #     * "/home/runner/work/openfoodnetwork/openfoodnetwork/vendor/bundle/ruby/2.5.0/gems/devise-4.8.0/app/views"
      #     * "/home/runner/work/openfoodnetwork/openfoodnetwork/engines/web/app/views"
      #     * "/home/runner/work/openfoodnetwork/openfoodnetwork/engines/order_management/app/views"
      #     * "/home/runner/work/openfoodnetwork/openfoodnetwork/vendor/bundle/ruby/2.5.0/gems/actiontext-6.0.3.6/app/views"
      #     * "/home/runner/work/openfoodnetwork/openfoodnetwork/vendor/bundle/ruby/2.5.0/gems/actionmailbox-6.0.3.6/app/views"
      #   ./app/views/spree/admin/orders/_form.html.haml:29:in `block in _app_views_spree_admin_orders__form_html_haml___3896545621144349112_47235709899480'
```

**Comment by Akashdee-gif** [comment]
Not working

**Comment by andrewpbrett** [comment]
Closed via https://github.com/openfoodfoundation/openfoodnetwork/pull/7566
