### ISSUE TITLE
[Rails 6.1] Rendering layouts from an absolute path is not supported.

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#7609]
### What we should change and why (this is tech debt)
This is a warning in rails 6.0 and an error in rails 6.1:
```
141) 
  Managing a hub's inventory
  I want to override the stock level and price of products
  Without affecting other hubs that share the same products
 as the manager of a hub when inventory_items exist for variants when a hub is selected with overrides updates on_demand settings
       Failure/Error: @app.call(env)
       
       ArgumentError:
         Rendering layouts from an absolute path is not supported.
       # ./lib/open_food_network/rack_request_blocker.rb:36:in `call'
       # ------------------
       # --- Caused by: ---
       # Capybara::ElementNotFound:
       #   Unable to find css "#s2id_hub_id"
       #   ./spec/support/request/web_helper.rb:123:in `open_select2'
```

The code was changed here: https://github.com/rails/rails/commit/2759addf2c01b1f490676ac68422b6f3b07a05d1

It is breaking in simple things like on the admin/subscriptions_controller
"render :setup_explanation"
For some reason it considers this an "absolute path", apparently treating it as /setup_explanation.
I couldnt find a fix for this.

**Comment by luisramos0** [comment]
yes, I tried all sorts of combinations
render "setup_explanation"
render "admin/subscriptions/setup_explanation"
render template: "admin/subscriptions/setup_explanation"
render template: "setup_explanation"

this last one gives me an error like this:
```
 ActionView::MissingTemplate:
       Missing template /setup_explanation with {:locale=>[:en], :formats=>[:haml], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :haml]}. Searched in:
         * "#<RSpec::Rails::ViewRendering::EmptyTemplateResolver::ResolverDecorator:0x0000556ee5ab5c80>"
         * "#<RSpec::Rails::ViewRendering::EmptyTemplateResolver::ResolverDecorator:0x0000556ee5ab5c08>"
```

I wonder if that / before the name is what's causing the error. I wonder why is it added...

**Comment by luisramos0** [comment]
ok, I went debugging rails and ended up finding the problem is on loading the layout.
Looking again at the error message, it does mention layout :-)
"Rendering layouts"...
Then I quickly fixed the specific error with this simple change:
![image](https://user-images.githubusercontent.com/1640378/117883411-4b705b00-b2a3-11eb-8e72-f3110959247f.png)

I will have a lok at the build now and see if this fixes all the errors.
