### ISSUE TITLE
Flaky spec: spec/features/consumer/shopping/checkout_spec.rb:147

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8268]
### What we should change and why (this is tech debt)

This spec passes locally but inconsistently on our build:

```
Failed examples:

rspec ./spec/features/consumer/shopping/checkout_spec.rb:147 # As a consumer I want to check out my cart login in as user with details filled out shows only applicable content
```

```
As a consumer I want to check out my cart login in as user with details filled out shows only applicable content

     Failure/Error: check "Shipping address same as billing address?"

     
If you need more of the backtrace for any of these deprecations to
     Capybara::ElementNotFound:
identify where to make the necessary changes, you can configure
       Unable to find visible checkbox "Shipping address same as billing address?" that is not disabled

```

### Context

Came up while running the build (passes locally).

### Impact and timeline

Make the build reliable.

**Comment by mkllnk** [comment]
Here's another one:
```
  1) Using embedded shopfront functionality using iframes redirects to embedded hub on logout when embedded
     # Temporarily skipped with xit
     # ./spec/features/consumer/shopping/embedded_shopfronts_spec.rb:99



Deprecation Warnings:
Failures:


Using `any_instance` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead. Called from /home/runner/work/openfoodnetwork/openfoodnetwork/spec/features/consumer/registration_spec.rb:20:in `block (3 levels) in <top (required)>'.
  1) As a consumer I want to check out my cart login in as user with details filled out when the user and customer have existing default addresses updates billing address and shipping address


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.
     Failure/Error: check "Shipping address same as billing address?"
     
     Capybara::ElementNotFound:
       Unable to find visible checkbox "Shipping address same as billing address?" that is not disabled
     # ./spec/support/request/checkout_request_helper.rb:54:in `fill_out_form'
     # ./spec/features/consumer/shopping/checkout_spec.rb:98:in `block (4 levels) in <top (required)>'
```
https://github.com/openfoodfoundation/openfoodnetwork/pull/8203/checks?check_run_id=3767205006
