### ISSUE TITLE
N+1 issues in Admin::SubscriptionsController#index

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#8694]
### What we should change and why (this is tech debt)

We've got 4 different N+1 issues in the `Admin::Subscriptions#index` action. For users that only manage few/small enterprises this isn't a big deal, but for users which manage many/large enterprises it can become a serious issue (for the user and for _the server_).

### Context

Partly contributed to some UK downtime (Jan 10th).

### Impact and timeline

Needs some improvement ASAP!

**Comment by Matt-Yorkley** [comment]
**Notes and backtraces**

High-impact N+1 on loading tags:
```
app/serializers/api/admin/payment_method/base_serializer.rb:10:in `tag_list'
app/serializers/api/admin/payment_method_serializer.rb:6:in `serializable_hash'
app/helpers/admin/injection_helper.rb:209:in `admin_inject_json_ams_array'
app/views/admin/subscriptions/_data.html.haml:5 
```

High-impact N+1 on payment method calculators:
```
app/models/spree/payment_method.rb:106:in `init'
app/helpers/admin/injection_helper.rb:209:in `admin_inject_json_ams_array'
app/views/admin/subscriptions/_data.html.haml:5
```

Small-medium impact N+1 on enterprises / exhanges:
```
app/helpers/admin/injection_helper.rb:209:in `admin_inject_json_ams_array'
app/views/admin/subscriptions/_data.html.haml:7
```

Small-medium impact N+1 around checks in `#subscriptions_setup_complete?`:
```
app/helpers/admin/subscriptions_helper.rb:8:in `block in subscriptions_setup_complete?'
app/helpers/admin/subscriptions_helper.rb:8:in `subscriptions_setup_complete?'
app/controllers/admin/subscriptions_controller.rb:18:in `block (2 levels) in index'
```

**Comment by Matt-Yorkley** [comment]
Note on N+1 issues with **loading tags** specifically; see [this previous issue](https://github.com/openfoodfoundation/openfoodnetwork/issues/5213) for more detail (and potential solution).
