### ISSUE TITLE
rake db:setup gives  Pych::SyntaxError

### ISSUE THREAD

**Issue by simnh** [openfoodfoundation/openfoodnetwork#918]
Hi, I tried to setup the openfoodnetwork to test it locally. I followed the steps from the "installation manual"
when running: 

`rake db:setup`

I got the following error:

```
`Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context at line 8 column 9
/home/simon/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/figaro-0.7.0/lib/figaro.rb:21:in `raw'
/home/simon/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/figaro-0.7.0/lib/figaro.rb:17:in `env'
/home/simon/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/figaro-0.7.0/lib/figaro/railtie.rb:7:in `block in <class:Railtie>'
/home/simon/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:34:in `call'
/home/simon/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:34:in `execute_hook'
/home/simon/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:43:in `block in run_load_hooks'
/home/simon/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:42:in `each'
/home/simon/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
/home/simon/.rvm/gems/ruby-2.1.5@openfoodnetwork/gems/railties-3.2.21/lib/rails/application.rb:67:in `inherited'
/home/simon/openfoodnetwork/config/application.rb:13:in `<module:Openfoodnetwork>'
/home/simon/openfoodnetwork/config/application.rb:12:in `<top (required)>'
/home/simon/openfoodnetwork/Rakefile:5:in `require'
/home/simon/openfoodnetwork/Rakefile:5:in `<top (required)>'
/home/simon/.rvm/gems/ruby-2.1.5@openfoodnetwork/bin/ruby_executable_hooks:15:in `eval'
/home/simon/.rvm/gems/ruby-2.1.5@openfoodnetwork/bin/ruby_executable_hooks:15:in `<main>'
```

I am not too much into ruby/rails, so maybe its a trivial problem? 

I am on master commit 2367b73d3a037a9d7e7a8b981aa29c382a2353b0
`rails -v` gives: Rails 3.2.21
`ruby --version` gives:  ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]

Thanks for help! 
Simon

**Comment by myriamboure** [comment]
Any idea @gnollet or @blancnic or maybe @pmackay ?

**Comment by sigmundpetersen** [comment]
A lot of new devs have setup ofn without this being seen, our devenv setup, wiki pages, ruby version etc updated. So this is outdated. A new ticket can be opened if seen again.
