### ISSUE TITLE
Deployment of master and v4.2.11 broken

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9622]
Deployment of v4.2.11 as well as current master is failing. I tried UK and FR. The previous official release v4.2.9 is working.

Maybe this log from semaphore can help:
```
TASK [deploy : clear transient data] *******************************************
fatal: [staging.openfoodnetwork.org.uk]: FAILED! => {"changed": true, "cmd": ["bash", "-lc", "bundle exec rake ofn:data:remove_transient_data RAILS_ENV=staging"], "delta": "0:00:03.021309", "end": "2022-09-01 14:51:28.349903", "msg": "non-zero return code", "rc": 1, "start": "2022-09-01 14:51:25.328594", "stderr": "rake aborted!\nLoadError: cannot load such file -- view_component/storybook\n/home/openfoodnetwork/.gem/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'\n/home/openfoodnetwork/.gem/ruby/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:332:in `block in require'\n/home/openfoodnetwork/.gem/ruby/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:299:in `load_dependency'\n/home/openfoodnetwork/.gem/ruby/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:332:in `require'\n/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2022-09-01-145031/config/application.rb:24:in `<top (required)>'\n/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2022-09-01-145031/Rakefile:7:in `require_relative'\n/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2022-09-01-145031/Rakefile:7:in `<top (required)>'\n/home/openfoodnetwork/.gem/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'\n/home/openfoodnetwork/.rbenv/versions/3.0.3/bin/bundle:23:in `load'\n/home/openfoodnetwork/.rbenv/versions/3.0.3/bin/bundle:23:in `<main>'\n(See full trace by running task with --trace)", "stderr_lines": ["rake aborted!", "LoadError: cannot load such file -- view_component/storybook", "/home/openfoodnetwork/.gem/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'", "/home/openfoodnetwork/.gem/ruby/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:332:in `block in require'", "/home/openfoodnetwork/.gem/ruby/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:299:in `load_dependency'", "/home/openfoodnetwork/.gem/ruby/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:332:in `require'", "/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2022-09-01-145031/config/application.rb:24:in `<top (required)>'", "/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2022-09-01-145031/Rakefile:7:in `require_relative'", "/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2022-09-01-145031/Rakefile:7:in `<top (required)>'", "/home/openfoodnetwork/.gem/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'", "/home/openfoodnetwork/.rbenv/versions/3.0.3/bin/bundle:23:in `load'", "/home/openfoodnetwork/.rbenv/versions/3.0.3/bin/bundle:23:in `<main>'", "(See full trace by running task with --trace)"], "stdout": "", "stdout_lines": []}
Thursday 01 September 2022  14:51:28 +0000 (0:00:03.271)       0:00:57.897 **** 
```

It seems to be since this commit had been merged: https://github.com/openfoodfoundation/openfoodnetwork/commit/d55a43d4b15c81334f9549633dd3ce39cefc3bf9

Thanks for the hint, @filipefurtad0!
Ping @mkllnk

**Comment by mkllnk** [comment]
I found the culprit, indeed #9599 caused it. I'm trying to load storybook but we have that gem only in development. So on staging we should ignore that.
