### ISSUE TITLE
[Flaky] spec/system/consumer/shopping/checkout_paypal_spec.rb

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#9638]
### What we should change and why (this is tech debt)

```
Failures:

  1) Check out with Paypal shared_examples as a logged in user behaves like checking out with paypal after logging-in completes the checkout after successful Paypal payment
     Failure/Error: fill_in "First Name", with: "Will"
     
     Capybara::ElementNotFound:
       Unable to find visible field "First Name" that is not disabled within #<Capybara::Node::Element tag="fieldset" path="//HTML[1]/BODY[1]/DIV[1]/DIV[2]/SECTION[1]/DIV[1]/ACCORDION[1]/DL[1]/CHECKOUT[1]/DIV[1]/DIV[1]/FORM[1]/FIELDSET[1]">
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_check_out_with_paypal_shared_examples_as_a_logged_in_user_behaves_like_checking_out_with_paypal_after_logging_in_completes_the_checkout_after_successful_paypal_payment_523.png

     
     Shared Example Group: "checking out with paypal" called from ./spec/system/consumer/shopping/checkout_paypal_spec.rb:98
     # ./spec/support/request/checkout_request_helper.rb:18:in `block in fill_out_details'
     # ./spec/support/request/checkout_request_helper.rb:17:in `fill_out_details'
     # ./spec/support/request/checkout_request_helper.rb:44:in `fill_out_form'
     # ./spec/system/consumer/shopping/checkout_paypal_spec.rb:53:in `block (4 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'

Failed examples:

rspec './spec/system/consumer/shopping/checkout_paypal_spec.rb[1:1:2:1:1:1]' # Check out with Paypal shared_examples as a logged in user behaves like checking out with paypal after logging-in completes the checkout after successful Paypal payment
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/runs/8183397718

### Impact and timeline

![failures_r_spec_example_groups_check_out_with_paypal_shared_examples_as_a_logged_in_user_behaves_like_checking_out_with_paypal_after_logging_in_completes_the_checkout_after_successful_paypal_payment_523](https://user-images.githubusercontent.com/3524483/188527915-2389e273-4d51-438f-9b59-411f08728596.png)

**Comment by mkllnk** [comment]
This hasn't been updated for a while and is probably not impacting us any more.
