### ISSUE TITLE
[Flaky] spec/system/admin/bulk_order_management_spec.rb

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#9757]
### What we should change and why (this is tech debt)

```
Failures:

  1) 
  As an Administrator
  I want to be able to manage orders in bulk
 using page controls using date restriction controls when the form is dirty shows a dialog and keeps changes when confirm dialog is rejected
     Failure/Error: expect(page).to have_selector "input[name=quantity].ng-dirty"
       expected to find css "input[name=quantity].ng-dirty" within #<Capybara::Node::Element tag="td" path="//HTML[1]/BODY[1]/DIV[1]/DIV[1]/DIV[4]/DIV[1]/DIV[1]/DIV[1]/DIV[1]/DIV[5]/FORM[1]/TABLE[1]/TBODY[1]/TR[2]/TD[11]"> but there were no matches
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_be_able_to_manage_orders_in_bulk_using_page_controls_using_date_restriction_controls_when_the_form_is_dirty_shows_a_dialog_and_keeps_changes_when_co_694.png

     
     # ./spec/system/admin/bulk_order_management_spec.rb:619:in `block (6 levels) in <top (required)>'
     # ./spec/system/admin/bulk_order_management_spec.rb:618:in `block (5 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'
```

I ran this spec ten times and it failed eight times. Pretty bad.

### Context

This came up when trying to remove retries:

* https://github.com/openfoodfoundation/openfoodnetwork/pull/9635

**Comment by mkllnk** [comment]
I tested this in the browser and the spec passes seem to be incorrect. We are expecting a confirmation which is not popping up for me. This patch makes the spec fail 100%:

```diff
diff --git a/spec/system/admin/bulk_order_management_spec.rb b/spec/system/admin/bulk_order_management_spec.rb
index d66832b66..d56840029 100644
--- a/spec/system/admin/bulk_order_management_spec.rb
+++ b/spec/system/admin/bulk_order_management_spec.rb
@@ -614,6 +614,7 @@ describe '
             find("input.datepicker").click
             select_dates_from_daterangepicker(today - 9.days, today)
           end
+          sleep 2
           expect(page).to have_selector "#save-bar"
           within("tr#li_#{li2.id} td.quantity") do
             expect(page).to have_selector "input[name=quantity].ng-dirty"
```

The save-bar was still visible from before and sometimes the page had not reloaded yet when the dirty input is tested. But selecting a date seems to not trigger the modal as expected in the spec.

**Comment by filipefurtad0** [comment]
When running both examples on this spec, I've noticed that despite wrapping it with accept_modal or dismiss_modal, we get several of these warnings anyway:

```
Modal window with text `Unsaved changes exist and will be lost if you continue.` has been opened, but you didn't wrap your code into (`accept_prompt` | `dismiss_prompt` | `accept_confirm` | `dismiss_confirm` | `accept_alert`), accepting by default
Modal window with text `Unsaved changes exist and will be lost if you continue.` has been opened, but you didn't wrap your code into (`accept_prompt` | `dismiss_prompt` | `accept_confirm` | `dismiss_confirm` | `accept_alert`), accepting by default
Modal window with text `Unsaved changes exist and will be lost if you continue.` has been opened, but you didn't wrap your code into (`accept_prompt` | `dismiss_prompt` | `accept_confirm` | `dismiss_confirm` | `accept_alert`), accepting by default

```

So, I've checked on staging, and the modal seems indeed to be triggered several times. I think this might be what is causing the spec to fail...

**Comment by mkllnk** [comment]
I got a success rate of 95% locally for `bulk_product_update_spec.rb:525`. Not easy to catch.
