### ISSUE TITLE
[Flaky] spec/system/admin/order_cycles/complex_creating_specific_time_spec.rb

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#9817]
### What we should change and why (this is tech debt)

```
Failures:

  1) 
    As an administrator
    I want to create/update complex order cycles with a specific time
 creating an order cycle with full interface
     Failure/Error: expect(page).to have_field "order_cycle_outgoing_exchange_0_pickup_time"
       expected to find field "order_cycle_outgoing_exchange_0_pickup_time" that is not disabled but there were no matches
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_create_update_complex_order_cycles_with_a_specific_time_creating_an_order_cycle_with_full_interface_176.png

     
     # ./spec/system/admin/order_cycles/complex_creating_specific_time_spec.rb:141:in `add_distributor_with_fees'
     # ./spec/system/admin/order_cycles/complex_creating_specific_time_spec.rb:69:in `block (2 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/3277527342/jobs/5395659632

### Impact and timeline

On my local machine I have a pass rate of only 61%.

**Comment by filipefurtad0** [comment]
Reoccurred here:

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/3479993701/jobs/5819225599

**Comment by filipefurtad0** [comment]
It seems that sometimes adding a distributor to the outgoing section of the order cycle works fine - clicking the `Add distributor` button; However, sometimes, clicking the button does not add a distributor - this error can be seen in the console - and for that reason the spec fails:

![Screenshot from 2022-11-23 12-38-54](https://user-images.githubusercontent.com/49817236/203539516-58ade565-2115-4f60-95ce-dd486621c193.png)

I'm not sure this can be improved by changing the spec.

**Comment by filipefurtad0** [comment]
Opened issue #10042.

**Comment by filipefurtad0** [comment]
Reoccurred here:
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/3651453204/jobs/6169483854
(despite the 3 retries :confused: )

**Comment by filipefurtad0** [comment]
Since the inconsistent failure seems to relate to issue #10042, I wonder if we should:
- increase the `:retry` number
- set the example as `pending`, till we close the underlying cause

What do you think @openfoodfoundation/core-devs ?

**Comment by jibees** [comment]
I've moved this one into `All the things` column
