### ISSUE TITLE
Spec order failure

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9938]
### What we should change and why (this is tech debt)

Documenting here as this is easily reproducible (at least in my) local system:

Running:

`bundle exec rspec --default-path spec "spec/system/admin/bulk_order_cancellation_spec.rb" "spec/system/admin/configuration/taxonomies_spec.rb" "spec/system/admin/enterprises/images_spec.rb" "spec/system/admin/payments_stripe_spec.rb" "spec/system/admin/schedules_spec.rb" "spec/system/consumer/account/developer_settings_spec.rb" "spec/system/consumer/multilingual_spec.rb" "spec/system/consumer/shopping/products_spec.rb" "spec/system/flatpickr_spec.rb" "spec/system/admin/order_cycles/complex_updating_specific_time_spec.rb"`

Fails with:

```
Failures:

  1) Developer Settings as a logged in user when show_api_key_view is true shows the developer settings tab
     Failure/Error: visit "/account"
     
     Ferrum::JavaScriptError:
       ReferenceError: Stripe is not defined
           at http://127.0.0.1:41851/account:962:30
     
     [Screenshot Image]: /home/ffurtado/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_developer_settings_as_a_logged_in_user_when_show_api_key_view_is_true_shows_the_developer_settings_tab_257.png

     
     # ./spec/system/consumer/account/developer_settings_spec.rb:12:in `block (3 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <main>'

  2) Developer Settings as a logged in user when show_api_key_view is true when the user has an api key shows the api key
     Failure/Error: visit "/account"
     
     Ferrum::JavaScriptError:
       ReferenceError: Stripe is not defined
           at http://127.0.0.1:41851/account:962:30
     
     [Screenshot Image]: /home/ffurtado/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_developer_settings_as_a_logged_in_user_when_show_api_key_view_is_true_when_the_user_has_an_api_key_shows_the_api_key_629.png

     
     # ./spec/system/consumer/account/developer_settings_spec.rb:12:in `block (3 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <main>'

  3) Developer Settings as a logged in user when show_api_key_view is true when the user has an api key lets the user regenerate the api key
     Failure/Error: visit "/account"
     
     Ferrum::JavaScriptError:
       ReferenceError: Stripe is not defined
           at http://127.0.0.1:41851/account:962:30
     
     [Screenshot Image]: /home/ffurtado/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_developer_settings_as_a_logged_in_user_when_show_api_key_view_is_true_when_the_user_has_an_api_key_lets_the_user_regenerate_the_api_key_568.png

     
     # ./spec/system/consumer/account/developer_settings_spec.rb:12:in `block (3 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <main>'

  4) Developer Settings as a logged in user when show_api_key_view is false does not show the developer settings tab
     Failure/Error: visit "/account"
     
     Ferrum::JavaScriptError:
       ReferenceError: Stripe is not defined
           at http://127.0.0.1:41851/account:945:30
     
     [Screenshot Image]: /home/ffurtado/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_developer_settings_as_a_logged_in_user_when_show_api_key_view_is_false_does_not_show_the_developer_settings_tab_383.png

     
     # ./spec/system/consumer/account/developer_settings_spec.rb:12:in `block (3 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <main>'

  5) Test Flatpickr orders opens the datepicker and closes it using the 'CLOSE' button
     Failure/Error: find(field).click
     
     Capybara::ElementNotFound:
       Unable to find visible css "#q_completed_at_gteq"
     
     [Screenshot Image]: /home/ffurtado/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_test_flatpickr_orders_opens_the_datepicker_and_closes_it_using_the__close__button_39.png

     
     # ./spec/system/flatpickr_spec.rb:42:in `open_datepicker'
     # ./spec/system/flatpickr_spec.rb:12:in `block (3 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <main>'

  6) Test Flatpickr orders opens the datepicker and sets date to today
     Failure/Error: find(field).click
     
     Capybara::ElementNotFound:
       Unable to find visible css "#q_completed_at_gteq"
     
     [Screenshot Image]: /home/ffurtado/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_test_flatpickr_orders_opens_the_datepicker_and_sets_date_to_today_308.png

     
     # ./spec/system/flatpickr_spec.rb:42:in `open_datepicker'
     # ./spec/system/flatpickr_spec.rb:24:in `block (3 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <main>'

  7) Test Flatpickr orders opens the datepicker and closes it by clicking outside
     Failure/Error: find(field).click
     
     Capybara::ElementNotFound:
       Unable to find visible css "#q_completed_at_gteq"
     
     [Screenshot Image]: /home/ffurtado/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_test_flatpickr_orders_opens_the_datepicker_and_closes_it_by_clicking_outside_232.png

     
     # ./spec/system/flatpickr_spec.rb:42:in `open_datepicker'
     # ./spec/system/flatpickr_spec.rb:31:in `block (3 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <main>'

Finished in 2 minutes 30.3 seconds (files took 8.42 seconds to load)
38 examples, 7 failures, 1 pending

Failed examples:

rspec ./spec/system/consumer/account/developer_settings_spec.rb:19 # Developer Settings as a logged in user when show_api_key_view is true shows the developer settings tab
rspec ./spec/system/consumer/account/developer_settings_spec.rb:29 # Developer Settings as a logged in user when show_api_key_view is true when the user has an api key shows the api key
rspec ./spec/system/consumer/account/developer_settings_spec.rb:33 # Developer Settings as a logged in user when show_api_key_view is true when the user has an api key lets the user regenerate the api key
rspec ./spec/system/consumer/account/developer_settings_spec.rb:44 # Developer Settings as a logged in user when show_api_key_view is false does not show the developer settings tab
rspec ./spec/system/flatpickr_spec.rb:10 # Test Flatpickr orders opens the datepicker and closes it using the 'CLOSE' button
rspec ./spec/system/flatpickr_spec.rb:22 # Test Flatpickr orders opens the datepicker and sets date to today
rspec ./spec/system/flatpickr_spec.rb:29 # Test Flatpickr orders opens the datepicker and closes it by clicking outside
```

### Context

This came up here:
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/3393780700/jobs/5641810234

### Impact and timeline

Build speed up; introducing Knapsack Pro

**Comment by filipefurtad0** [comment]
This narrows it down further:
`
bundle exec rspec --default-path spec "spec/system/admin/payments_stripe_spec.rb" "spec/system/consumer/account/developer_settings_spec.rb"
`

I guess we should be leaking the setup from stripe_spec into the next one.

**Comment by jibees** [comment]
Super strange that:
 - this spec fails --> will make a PR (if I manage to solve it :p)
 - Our build did no catch it!

**Comment by jibees** [comment]
Our build did not catch it, since the file is: `spec/system/flatpickr_spec.rb` and the regexp is 
https://github.com/openfoodfoundation/openfoodnetwork/blob/9ef07cb110129dd9e5c64696c6eb495bf0bcb6b8/.github/workflows/build.yml#L43-L46

which did not catch everything that is in the folder `/system/` (but it's the only one). 

We can either move the `flatpickr_spec` file nor change the build workflow.

**Comment by filipefurtad0** [comment]
Thanks for investigating this @jibees .

I think this one is an /admin spec, so I'd move it into `.spec/system/admin`

**Comment by filipefurtad0** [comment]
I think we have other similar issues: I can't seem to make any spec on the `./spec/performance` spec pass, locally. I'm not sure this is running on our build, either.

**Comment by jibees** [comment]
In our build, we run specs that match:

```
          - "spec/controllers"
          - "spec/models"
          - "spec/lib"
          - "spec/migrations"
          - "spec/serializers"
          - "spec/system/admin/[a-o0-9]*"
          - "spec/system/admin/[p-z]*"
          - "spec/system/consumer/[a-o0-9]*"
          - "spec/system/consumer/[p-z]*"
          - "engines/*/spec"
  ```

which is not the case of anything in `/spec/performance` ...

**Comment by filipefurtad0** [comment]
Yes, but we also have a second job - the test-the-rest, which should match the folder list below:

`run: bundle exec rake ofn:specs:run:excluding_folders["models,controllers,serializers,features,lib,migrations,system"]`

So, I'd expect `/performance` to run, right?

**Comment by jibees** [comment]
Ah yes, now I see. 

Regarding 
```
bundle exec rake ofn:specs:run:excluding_folders["models,controllers,serializers,features,lib,migrations,system"]
```
I agree with we should run `performance` stuff... 


I'm also wondering if we should add `engines` and remove `features` in this `ofn:specs:run:excluding_folders` array

**Comment by filipefurtad0** [comment]
I've opened a PR [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/9946). I have a question on syntax, maybe best to move the discussion to that issue :-)
